### ISSUE TITLE
Connection fails to restart on network switch

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#1]
**What?**
1. connect 2 peers
2. switch network on one of the peers (e.g. connect to a different wifi net or just turn wifi off/on) 
3. peer will attempt to reconnect but will fail in some cases
4. connection won't be established anymore

**Why?**
When a peer goes offline (e.g. wi-fi network switch) a connection to signal drops. While it will be reestablished later, a process of Connection.Restart() has been already triggered and an attempt to signal fails. Restart doesn't continue.

**Comment by amrhamidafarhataboouf-prog** [comment]
https://www.facebook.com/SpiderAmrHamid
