### ISSUE TITLE
Breaking Changes documentation?

### ISSUE THREAD

**Issue by maaft** [netbirdio/netbird#1002]
**Describe the problem**

Are there any breaking changes e.g. when updating **self-hosted** netbird from **0.16.0** to the latest release (e.g. **0.21.8**)?

A quick search for "break" on the release page didn't yield any results. Is this really the case? I'm afraid to break my production environment.

Thanks!

**Comment by mlsmaycon** [comment]
Hello @maaft can you confirm what is the error, is it with the management or clients? We might have missed a change, and we aim to always be compatible with older versions.

**Comment by oskardotglobal** [comment]
From my experience there's no real breaking changes, I had a v11 something client work with a v21 something server, although you'd probably want to keep your clients updated anyways

**Comment by braginini** [comment]
@maaft 
We don't have breaking changes. Try upgrading the Management server first then clients.

**Comment by maaft** [comment]
@braginini thanks, will do!
