### ISSUE TITLE
Windows: DNS via netbird Peer.

### ISSUE THREAD

**Issue by dragon2611** [netbirdio/netbird#1022]
**Describe the problem**
When you create split DNS in the management control panel and set the DNS server to a netbird Peer IP windows clients do not seem to be able to resolve any DNS in the split domain.

Additionally, if you add a second DNS server using the Peers LAN IP and then add a route it seems to just crash the netbird service on Windows.

Using just the LAN interface IP (e.g 10.0.0.2) and adding a route works, the problems only manifest if you try and use a netbird peer IP as the DNS server you send to the netbird clients.

For instance create a DNS entry in the netbird UI to match internal.mydomain.com
Run a DNS server on netbird peer 100.1.2.3 (I used a PDNS-Recursor container and set it up so that internal.mydomain was an authoritative zone)

Set DNS to 100.1.2.3 for this split domain.
Ensure ACL allows traffic

Linux clients would work as expected, sending queries for internal.mydomain.com to the PDNS-recursor and getting the approprate reply.

I could not get any useful logs from netbird when the service crashed.

**Comment by mlsmaycon** [comment]
Hello @dragon2611 is this issue fixed with the latest 0.21.10 version?

**Comment by dragon2611** [comment]
I think upgrading from 0.21.8 to 0.21.9 fixed it (Or at least it was no longer crashing after updating and DNS appeared to be working as expected)
