### ISSUE TITLE
API lowercases setup key group names

### ISSUE THREAD

**Issue by clarkmcc** [netbirdio/netbird#1060]
**Describe the problem**
When creating setup keys through the API, group names are lowercased, but are still case sensitive -- title cased group names are not found.

**To Reproduce**
When I POST to the endpoint `/api/setup-keys` with the following payload

```json
{
  "name": "Testing key",
  "type": "one-off",
  "expires_in": 86400,
  "revoked": false,
  "auto_groups": [
    "Foobars"
  ],
  "usage_limit": 1
}
```

I get this error

```json
{"message":"group foobars doesn't exist","code":404}
```

But I can create a setup key with "Foobars" through the UI.

**Expected behavior**
The setup key should be properly created

**Comment by mlsmaycon** [comment]
Hello @clarkmcc the auto_groups expect group IDs instead of names. You can get that with 

GET /API/groups

**Comment by clarkmcc** [comment]
Ah, thanks
