### ISSUE TITLE
android, typo: entering invalid server reports "ivalid server address"

### ISSUE THREAD

**Issue by smithed** [netbirdio/netbird#1067]
**Describe the problem**
on android, entering invalid server reports "ivalid server address"

**To Reproduce**
On android:
Enter "H" in the custom server field

**Expected behavior**
correct spelling :)

**Comment by mlsmaycon** [comment]
Hello @smithed thanks for reporting this. We will fix for the next release.

**Comment by mlsmaycon** [comment]
that has been fixed in the latest release 0.0.16.
