### ISSUE TITLE
android: netbird does not follow URI standard for custom servers 

### ISSUE THREAD

**Issue by smithed** [netbirdio/netbird#1068]
**Describe the problem**
In android app, entering a valid https uri generates an error stating it is invalid, exacerbated by using a keyboard entry format that causes gboard to capitalize H by default.
ie, per rfc3986, "Https" is just as valid as "https" 
aka case insentivity is the bane of humanity

**To Reproduce**
1. Try to enter custom url on android app
2. Even though "Https://netbird....." is valid, and how the app prompts you to enter it, it reports an '[ivalid](https://github.com/netbirdio/netbird/issues/1067)' server name

**Expected behavior**
accept valid URI

**Comment by mlsmaycon** [comment]
Thanks @smithed to report this issue. The fix will be in the next release as well.

**Comment by mlsmaycon** [comment]
that has been fixed in the latest release 0.0.16.
