### ISSUE TITLE
Implement a device posture hook inside the client

### ISSUE THREAD

**Issue by qdrop17** [netbirdio/netbird#1085]
**Is your feature request related to a problem? Please describe.**
We want to make sure our clients fulfill some basic criteria (such as an enabled AV or an up-to-date patchlevel of the OS) before connecting to our backends.

**Describe the solution you'd like**
It would be great if we could implement some pre-connect-hook so we can run custom scripts and checks before the client connects to a network. Of course this can be tinkered with but it still would improve our security by a good margin.

https://ferrumgate.com/docs/configuration/settings/device-posture/ offers a potential way how this could be implemented.

**Describe alternatives you've considered**
If we can approve devices conditionally based on their endpoint protection status which is queried from a backend - that could be a viable workaround too.

**Comment by qdrop17** [comment]
This is no longer relevant as we're using another method to check device posture.

**Comment by acrow-geo** [comment]
Can you enlighten us as to what you chose for posture management please?

**Comment by braginini** [comment]
Hey @acrow-geo 
Would you mind joining NetBird Slack? We have a few thoughts about these features too
https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A
