### ISSUE TITLE
Peers not reaching each other

### ISSUE THREAD

**Issue by asamarco** [netbirdio/netbird#1094]
Hi,

My peers cannot connect to each other, despite default configurations. On the admin page they result connected but they can not ping each other. It is a problem of my selfhosting attempt, the same peers on the official server work perfectly.

docker logs -f tmp-signal-1 shows connection and disconnection correctly and no errors.

I have no idea how to further diagnose this issue, but i am considering another possibility.
Is there any know issue in selfhosting netbird on Oracle Cloud? netmaker for instance warns against hosting there.
Could be some networking quirk of the cloud provider?

Thanks!

**Comment by braginini** [comment]
Hey @asamarco 
Would you mind joining our slack and pinging us there in the general chat? 
Please also refer to this issue in your message there. Let's figure out the issue together!

https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A

**Comment by risturiz** [comment]
Any update on this? I´m having some issues with some peers

**Comment by braginini** [comment]
hey @risturiz 
Could you please ping me in Slack? (Misha)

**Comment by htc10** [comment]
> Hi,
> 
> My peers cannot connect to each other, despite default configurations. On the admin page they result connected but they can not ping each other. It is a problem of my selfhosting attempt, the same peers on the official server work perfectly.
> 
> docker logs -f tmp-signal-1 shows connection and disconnection correctly and no errors.
> 
> I have no idea how to further diagnose this issue, but i am considering another possibility. Is there any know issue in selfhosting netbird on Oracle Cloud? netmaker for instance warns against hosting there. Could be some networking quirk of the cloud provider?
> 
> Thanks!

Oracle Cloud having this problem.maybe arm cpu or network.

**Comment by asamarco** [comment]
Hi, I tried again netbird just yesterday and I have found the cause of my
problems. I did the stupid mistake of opening UDP ports in the security
list of the wrong subnet. Once this was corrected I could finally connect
all the nodes. I am using an AMD VM though not the ARM ones.
