### ISSUE TITLE
Netbird Android app source code, privacy and ethical concerns

### ISSUE THREAD

**Issue by Darin755** [netbirdio/netbird#1109]
## The problem

As you might be aware, the new netbird app is completely proprietary. Its is developed in secret and spits in the face of Foss. What's worse is that it contains analytics and spyware. So not only does it violate your freedom to study, modify and distribute the source code but it also sends your data back in order to track your activities. This seems like a pretty clear violation of the morals set by free/libre software.

## The impact

This course of action has broken a lot of trust. I can no longer expect them to do the right thing and to be on the side of the community. I personally will be moving away from them and I encoage others to do the same unless they change.

## what should of happened

Netbird should of created a new repo and walked with the community in order to develop an app that works for all of us. Such an app wouldn't need to be dependent on google analytics and could be shaped by the needs of the community.

## what netbird can do in response

I don't think it would be asking to much to get an apology from netbird and to have them open up all the sources. They should have reproducible builds that are Foss and free of spyware.

Please note: I am putting this as a issue as I think it is of great importance. If this issue gets to heated or is polluting the issue tracker then move it to a discussion

**Comment by braginini** [comment]
Hey @Darin755 
Are you in our Slack channel? If not, we'd be happy to see you there :) 
https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A

We have publicly communicated in our Slack channel that we will open source the Andorid app. We will do this as soon as we added more tests and cleaned up the code. Stay tuned!

**Comment by Darin755** [comment]
I don't use slack because of its proprietary nature and also due to privacy concerns. (I know I'm a minority)

Thank you for your response though. I do appreciate what you do

**Comment by mlsmaycon** [comment]
Hello @Darin755 , we also have a matrix channel, you will find us at https://matrix.to/#/#netbird:matrix.org, it is connected to our Slack general channel, but we can chat there.

**Comment by Ginner** [comment]
+1 To open sourcing the Android app! I actually choose Netbird over Nebula (after spending considerable time learning about it and setting up lighthouses with Ansible) because of their failure to properly license their Android app (although it is 'source available') and their response to concerns in this regard. 

It seems that the will is here and I'm really looking forward to finding the app on f-droid :)

**Comment by HammyHavoc** [comment]
How's this going? I'm super curious about NetBird, but admittedly sceptical with how much time has transpired since announcing the intent to publish the source.

**Comment by LibreTechnica** [comment]
Once the Android is open-sourced, would it be available on F-droid without the Google Crashlytics and Google Firebase Analytics trackers?

**Comment by HammyHavoc** [comment]
> Once the Android is open-sourced, would it be available on F-droid without the Google Crashlytics and Google Firebase Analytics trackers?

That would be excellent. I would be so happy to see this happen.

**Comment by LibreTechnica** [comment]
What timing! I just checked back and saw the Android app was open-sourced two days ago.  I'm a huge step closer to installing it on my phone.  Now I wonder if there will be a build for F-droid without the trackers or if I could be steered to how I can compile it myself without those.  Android development isn't my bread and butter, but I'm always willing to learn!

**Comment by HammyHavoc** [comment]
> What timing! I just checked back and saw the Android app was open-sourced two days ago.  I'm a huge step closer to installing it on my phone.  Now I wonder if there will be a build for F-droid without the trackers or if I could be steered to how I can compile it myself without those.  Android development isn't my bread and butter, but I'm always willing to learn!

Fascinating stuff, thanks for letting us know, this had completely flown under my radar.

Also very interested in a tracker-free version and feel that it's important for it to be taken seriously in terms of trust.

**Comment by Darin755** [comment]
I just wanted to come back to this issue in order to express my satisfaction with Netbird. I am glad that they are sticking to open values and I look forward to what comes next.

**Comment by thunder-007** [comment]
https://github.com/netbirdio/android-client

**Comment by Darin755** [comment]
> https://github.com/netbirdio/android-client

I guess I can close this issue now that they released the source code
