### ISSUE TITLE
Hostname can't be resolved in ubuntu server 22.04

### ISSUE THREAD

**Issue by caiomendonca** [netbirdio/netbird#1127]
**Describe the problem**
Name resolution for netbird.cloud does not work if not have configured dns server in netbird cloud. I did a clean installation of ubuntu 22.04 in lxc container and installed the netbird client via script provided in the docs. 
When i try resolve a device name connected in the network, the message like "name or service not know" displayed. 
When i configure any dns server like cloudflare or google in netbird cloud, the netbird.cloud names can be resolved normally, but if I enable the "Match Domains" option, the problem happens again. This problem does not happen on Windows.

I don't know if it's a bug or incorrect configuration, but I did several tests and I couldn't solve this problem

**To Reproduce**
Install ubuntu 22.04
Execute script provided on https://pkgs.netbird.io/install.sh and up the netbird client
disable dns server for this host in netbird.cloud

**Expected behavior**
any hostname in .netbird.cloud name resolved without needing dns server configuration

**Screenshots**
/var/log/netbird/client.log output:
![error_netbird](https://github.com/netbirdio/netbird/assets/12699381/960eeec7-8a92-405f-b263-572bb4072e93)

**Additional context**
My test host is installed in lxc container on Proxmox

**Comment by pappz** [comment]
This situation is a well known limitation in case the Linux distribution support the resolv.conf type DNS settings only.  The reason is very simple, for the resolv.conf we can not set match domain settings. What is interesting for me is why do not available the systemd approach.

**Comment by pappz** [comment]
@caiomendonca could you share with me the /etc/resolv.conf file and the /etc/resolv.conf.original.netbird file?

**Comment by caiomendonca** [comment]
@pappz thanks for the reply.

follows the contents of /etc/resolv.conf file

# --- BEGIN PVE ---
search net.clm.local
nameserver 192.168.1.10
nameserver 8.8.8.8
nameserver 1.1.1.1
# --- END PVE ---

I couldn't find the /etc/resolv.conf.original.netbird file

the netbird client version is 0.23.0.

**Comment by caiomendonca** [comment]
I understand, thanks for the help!
