### ISSUE TITLE
Hello, how can I set my certificate to Netbird and a custom SSL port?

### ISSUE THREAD

**Issue by Pinkpiglet** [netbirdio/netbird#1151]
Hello, how can I set my certificate to Netbird and a custom SSL port?

**Comment by Pinkpiglet** [comment]
![image](https://github.com/netbirdio/netbird/assets/38532706/3f8ed080-4d72-4530-b01e-38fbcc4e7942)
The port has been changed, but there will be a 401 error message

**Comment by surik** [comment]
Hi @Pinkpiglet, could you please take a look at the error logs of the management service via `docker-compose logs management`? Also, can you share more about your IDP setup?

**Comment by Pinkpiglet** [comment]
`
{
    "Stuns": [
        {
            "Proto": "udp",
            "URI": "stun:netbird.xxxx.com:3478",
            "Username": "",
            "Password": null
        }
    ],
    "TURNConfig": {
        "Turns": [
            {
                "Proto": "udp",
                "URI": "turn:netbird.xxxx.com:3478",
                "Username": "self",
                "Password": "GwbSf9uOYN6OQilqNnXzV8xU2sgjPnyuZq0hut1WRXc"
            }
        ],
        "CredentialsTTL": "12h",
        "Secret": "secret",
        "TimeBasedCredentials": false
    },
    "Signal": {
        "Proto": "http",
        "URI": "netbird.xxxx.com:10000",
        "Username": "",
        "Password": null
    },
    "Datadir": "",
    "HttpConfig": {
        "Address": "0.0.0.0:33073",
        "AuthIssuer": "https://authentik.xxxx.com:9443/application/o/netbird/",
        "AuthAudience": "rEy9QLhxhRQyvqVyBUkVJdqUE22i0PfYVMa2G5sZ",
        "AuthKeysLocation": "https://authentik.xxxx.com:9443/application/o/netbird/jwks/",
        "AuthUserIDClaim": "",
        "CertFile":"/etc/letsencrypt/live/netbird.xxxx.com/fullchain.pem",
        "CertKey":"/etc/letsencrypt/live/netbird.xxxx.com/privkey.pem",
        "OIDCConfigEndpoint":"https://authentik.xxxx.com:9443/application/o/netbird/.well-known/openid-configuration"
    },
    "IdpManagerConfig": {
        "ManagerType": "authentik",
        "ClientConfig": {
            "Issuer": "https://authentik.xxxx.com:9443/application/o/netbird/",
            "TokenEndpoint": "https://authentik.xxxx.com:9443/application/o/token/",
            "ClientID": "rEy9QLhxhRQyvqVyBUkVJdqUE22i0PfYVMa2G5sZ",
            "ClientSecret": "",
            "GrantType": "client_credentials"
        },
        "ExtraConfig": {
  "Password": "QW4TqXjF7JD5VTj1NH0KQzovk1FYBK8U36GscTKCdT7vxuDpGLkjcGi968H4",
  "Username": "Netbird"
}
     },
    "DeviceAuthorizationFlow": {
        "Provider": "hosted",
        "ProviderConfig": {
          "Audience": "rEy9QLhxhRQyvqVyBUkVJdqUE22i0PfYVMa2G5sZ",
          "Domain": "",
          "ClientID": "rEy9QLhxhRQyvqVyBUkVJdqUE22i0PfYVMa2G5sZ",
          "TokenEndpoint": "https://authentik.xxxx.com:9443/application/o/token/",
          "DeviceAuthEndpoint": "https://authentik.xxxx.com:9443/application/o/device/",
          "Scope": "openid",
          "UseIDToken": false
         }
    },
    "PKCEAuthorizationFlow": {
        "ProviderConfig": {
            "Audience": "rEy9QLhxhRQyvqVyBUkVJdqUE22i0PfYVMa2G5sZ",
            "ClientID": "rEy9QLhxhRQyvqVyBUkVJdqUE22i0PfYVMa2G5sZ",
            "ClientSecret": "",
            "AuthorizationEndpoint": "https://authentik.xxxx.com:9443/application/o/authorize/",
            "TokenEndpoint": "https://authentik.xxxx.com:9443/application/o/token/",
            "Scope": "openid profile email offline_access api",
            "RedirectURLs": ["http://localhost:53000"],
            "UseIDToken": false
        }
    }
}
`
![image](https://github.com/netbirdio/netbird/assets/38532706/a1adaf7c-7748-4b27-842f-8f401e1743e4)
@surik

**Comment by Pinkpiglet** [comment]
I guess it should be related to this:

Grant_types_supported:[
          Authorization_code ",
         Refresh_token,
         Implicit,
        **Client_credentials ",**
        Password,
        Urn: ietf: params: oauth: grant type: device_code
] @surik

**Comment by Pinkpiglet** [comment]
@surik Two devices are already online, but they cannot ping each other. Which service's logs do I need to view?

**Comment by Pinkpiglet** [comment]
![image](https://github.com/netbirdio/netbird/assets/38532706/3ab3d588-5599-4a3a-bea0-6f53aeadb549)

**Comment by Pinkpiglet** [comment]
@surik 
windows11：
![image](https://github.com/netbirdio/netbird/assets/38532706/aaf70dd5-9cd5-46aa-b99a-ec7bbd988e14)

debian12
![image](https://github.com/netbirdio/netbird/assets/38532706/57f05bf7-b5e3-49c4-bb3f-1e3ffdf94246)

**Comment by surik** [comment]
@Pinkpiglet that might be a TURN issue. Can you perform the same test as described in this comment? https://github.com/netbirdio/netbird/issues/798#issuecomment-1502430133

**Comment by Pinkpiglet** [comment]
@surik 
![image](https://github.com/netbirdio/netbird/assets/38532706/1ad6e12e-063f-4bb4-b950-df8dd4c0b061)
Prompted authentication failures

**Comment by surik** [comment]
@Pinkpiglet Yes, looks like TURN is not configured properly. Maybe you can try to change the password and restart the TURN service? Please let me know if this works.

**Comment by Pinkpiglet** [comment]
@surik 
![image](https://github.com/netbirdio/netbird/assets/38532706/7fb468df-805c-4f4c-8ff0-875508f30af1)
After resetting the port and password, the test was normal, but still unable to ping the other party's device

**Comment by surik** [comment]
@Pinkpiglet please show the output of the status command I'm assuming that we have TURN properly up and running we can see something new there

**Comment by surik** [comment]
@Pinkpiglet Also, could you confirm that the TURN credentials are in sync in `management.json` and `turnserver.conf` and that both services restarted?

**Comment by Pinkpiglet** [comment]
> @Pinkpiglet Also, could you confirm that the TURN credentials are in sync in `management.json` and `turnserver.conf` and that both services restarted?

Yes, all have been restarted.

**Comment by surik** [comment]
@Pinkpiglet thank you. I will need more logs to understand how the status of connection from netbird to TURN. On the Linux machines can you do the following:

```
sudo mkdir -p /etc/sysconfig
echo 'PIONS_LOG_DEBUG=all' | sudo tee -a /etc/sysconfig/netbird
echo 'NB_LOG_LEVEL=debug' | sudo tee -a /etc/sysconfig/netbird
sudo netbird service restart
```

After at least 1 minute please collect the following files:
```
/var/log/netbird/client.log
/var/log/netbird/netbird.out
/var/log/netbird/netbird.err
```
You can share them here or another option is to join our [Slack group](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A).

**Comment by Pinkpiglet** [comment]
> /var/log/netbird/
[netbird.log](https://github.com/netbirdio/netbird/files/12675820/netbird.log)

[client.log](https://github.com/netbirdio/netbird/files/12675810/client.log)

**Comment by surik** [comment]
```
ice WARNING: 2023/09/21 01:08:25 failed to resolve stun host: netbird.xxxx.com:3478: lookup netbird.xxxx.com on 114.114.114.114:53: no such host
ice WARNING: 2023/09/21 01:08:25 Failed to build new turn.Client netbird.xxxx.com:3478 lookup netbird.xxxx.com on 114.114.114.114:53: no such host
ice WARNING: 2023/09/21 01:08:25 failed to resolve stun host: netbird.xxxx.com:3478: lookup netbird.xxxx.com on 114.114.114.114:53: no such host
```

The machine you used to test with https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ was able to resolve that domain. Wonder why this is not the case for the instance above.

**Comment by Pinkpiglet** [comment]
> ```
> ice WARNING: 2023/09/21 01:08:25 failed to resolve stun host: netbird.xxxx.com:3478: lookup netbird.xxxx.com on 114.114.114.114:53: no such host
> ice WARNING: 2023/09/21 01:08:25 Failed to build new turn.Client netbird.xxxx.com:3478 lookup netbird.xxxx.com on 114.114.114.114:53: no such host
> ice WARNING: 2023/09/21 01:08:25 failed to resolve stun host: netbird.xxxx.com:3478: lookup netbird.xxxx.com on 114.114.114.114:53: no such host
> ```
> 
> 您用来测试[https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ 的](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)机器能够解析该域。想知道为什么上面的例子不是这种情况。

I have used another server and it is already possible, but the Windows client cannot access the network with routing settings, and my phone can access it.

**Comment by surik** [comment]
Unfortunately, only Linux is supported as a [routing peers](https://docs.netbird.io/how-to/routing-traffic-to-private-networks#routing-peer) right now.

**Comment by Pinkpiglet** [comment]
> 不幸的是，目前仅支持 Linux 作为[路由对等点。](https://docs.netbird.io/how-to/routing-traffic-to-private-networks#routing-peer)

Approximately when will this support the Windows system

**Comment by Pinkpiglet** [comment]
> Unfortunately, only Linux is supported as a [routing peers](https://docs.netbird.io/how-to/routing-traffic-to-private-networks#routing-peer) right now.

Android client using non 443 port prompts for invalid address

**Comment by surik** [comment]
@Pinkpiglet 

> Approximately when will this support the Windows system

We don't have an estimation for this unfortunately

> Android client using non 443 port prompts for invalid address

Can you elaborate on this? You may have logs to demonstrate the issue.
