### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by QBANIN** [netbirdio/netbird#1154]
**Describe the problem**
Installed Netbird by using getting-started-with-zitadel.sh on a OVH VPS but after accessing console I'm gettin 502 error 
![obraz](https://github.com/netbirdio/netbird/assets/487657/f10dd779-4f66-4e09-a9fa-2b46cf6c27b8)

netbird-management-1 container keep crashing with following error message
`2023-09-19T19:46:44Z INFO management/server/telemetry/app_metrics.go:161: enabled application metrics and exposing on http://0.0.0.0:8081
Error: failed to write out store encryption key: rename /etc/netbird/.2772331671management.json /etc/netbird/management.json: device or resource busy
`

**To Reproduce**

Follow Quickstart guide

**Expected behavior**
Working console

**Comment by mlsmaycon** [comment]
Hello @QBANIN, this is an issue caused by our attempt to generate a secret key for audit events.  The Pr #1155 will fix the issue. While we are reviewing, you can update the generated docker-compose.yml and update the image for the management service to use the tag 0.23.1:

```yaml
...
  management:
    image: netbirdio/management:0.23.1
...
```

Then you can run the following command to restart the management service:

```
docker compose up -d
```

**Comment by liuyishengaaa** [comment]
I'm also experiencing this error, the management container keeps restarting and I can't find a solution.
![image](https://github.com/netbirdio/netbird/assets/132032777/cb394ee4-61a7-4d32-8e59-43565e87b807)
![image](https://github.com/netbirdio/netbird/assets/132032777/c3a71f5f-180b-4c5c-9105-ab6e91548d92)
![image](https://github.com/netbirdio/netbird/assets/132032777/3ed80c76-6823-4288-be53-23e4ab94967a)

**Comment by mlsmaycon** [comment]
hello @liuyishengaaa, it seems like the management service is unable to fetch the OIDC configuration endpoint, resulting in a failure to start. 

Can you check if the endpoint is reachable from the management container?

**Comment by liuyishengaaa** [comment]
Dear, mlsmaycon, my management container is constantly restarting. How can I check the endpoint? Could you provide me with some testing methods?
