### ISSUE TITLE
How to ensure that edge clients can continue to join during server control migration and which key files need to be backed up

### ISSUE THREAD

**Issue by 13653216371** [netbirdio/netbird#1162]
Docker deployment, requesting guidance on how to migrate the server. Thank you

**Comment by pascal-fischer** [comment]
Hi, the most important files are the config file (usually `/etc/netbird/config.json` and the store files `/var/lib/netbird/store.json` which contain basically all the configured devices, routes, etc. and `/var/lib/netbird/events.db` that contains the activity log in case you want to keep the history.

Currently, it is not possible to have multiple instances of the management service running in parallel so it is impossible to guarantee that clients can continue to join during migration. Luckily existing peers are able to communicate even if management is offline for a bit. It should be possible to migrate by creating a replica of the management service and a copy of the store and testing if everything is working as expected. Once you are ready to migrate stop the new management and override the store with a copy of the current store and start it again. Meanwhile, change the DNS record of your management to point to the IP of the new management. This should trigger a quick reconnect between peers and management but should cause minimal interruption to the existing mesh. During this short period of switching no new peers should be joining though.

**Comment by 13653216371** [comment]
Thank you. The migration has been successful and all clients have been launched.

Correct the configuration path:

```
/Etc/netbird/management. json
/Var/lib/netbird/store.json
/Var/lib/netbird/events. db
```
