### ISSUE TITLE
selfhosted-quickstart : Request failed with status code 401. Please refresh the page if the issue continues. invalid jwt

### ISSUE THREAD

**Issue by htc10** [netbirdio/netbird#1164]
**Describe the problem**
<img width="1230" alt="image" src="https://github.com/netbirdio/netbird/assets/3377944/8082fa9f-7486-4cee-be63-088925f06111">

Installation method：
https://docs.netbird.io/selfhosted/selfhosted-quickstart

netbird-management-1 log:
2023-09-25T03:15:14Z INFO management/server/account.go:1335: overriding JWT Domain and DomainCategory claims since single account mode is enabled
2023-09-25T03:15:14Z ERRO management/server/telemetry/http_api_metrics.go:181: HTTP response 3203182402: GET /api/users status 401

**Comment by mlsmaycon** [comment]
Hello @htc10 the issue has been fixed in the latest version, you can run `docker compose pull` followed by `docker compose up -d --force-recreate management` to upgrade.

**Comment by htc10** [comment]
> Hello @htc10 the issue has been fixed in the latest version, you can run `docker compose pull` followed by `docker compose up -d --force-recreate management` to upgrade.

very good it's Succeeded
