### ISSUE TITLE
Client install script not working on system without sudo

### ISSUE THREAD

**Issue by stevendbrady** [netbirdio/netbird#1170]
**Describe the problem**
The sudo command is not present on the Proxmox Virtual Environment. When apt is detected, it's assumed sudo is also present so all commands containing it fail.

**To Reproduce**
- Run the script on the website: curl -fsSL https://pkgs.netbird.io/install.sh | sh

**Expected behavior**
- Check for presence of sudo, if not present make sure running as root, then install without using sudo command.

**Comment by mlsmaycon** [comment]
fixed on #1176
