### ISSUE TITLE
netbird on a win10

### ISSUE THREAD

**Issue by 985119** [netbirdio/netbird#1189]
The settings button cannot be opened when installing netbird on a win10 virtual machine. As a result, the self-deployment server cannot be entered. Is this a bug?

email:985119@gmail.com

**Comment by bcmmbaga** [comment]
> The settings button cannot be opened when installing netbird on a win10 virtual machine. As a result, the self-deployment server cannot be entered. Is this a bug?
> 
> email:[985119@gmail.com](mailto:985119@gmail.com)

Hello @985119 , which version of Netbird you have installed?

**Comment by Fantu** [comment]
I also spotted this issue today on a windows 2019 standard, netbird 0.23.7 I edited config.json as workaround

**Comment by mlsmaycon** [comment]
Thanks for sharing the issue @Fantu and @985119 , we will investigate and issue a fix

**Comment by bcmmbaga** [comment]
@Fantu are you running over RDP? The GUI client depends on OpenGL that is disabled by default for RDP

**Comment by Fantu** [comment]
@bcmmbaga thanks for reply, you're right, on the physical PC it works while on all those connected in RDP it doesn't.
why is OpenGL needed for such a basic operations window?
now we have the majority of customer users who use rdp as they have virtual machines or connect to terminal servers and the only major problems they have are with programs that require 3d acceleration (like autocad), such as technicians in municipalities but in those cases they use physical PC

**Comment by bcmmbaga** [comment]
> @bcmmbaga thanks for reply, you're right, on the physical PC it works while on all those connected in RDP it doesn't. why is OpenGL needed for such a basic operations window? now we have the majority of customer users who use rdp as they have virtual machines or connect to terminal servers and the only major problems they have in few cases are with programs that require 3d acceleration (like autocad), such as technicians in municipalities but in those cases they use physical PC

we are using [fyne GUI toolkit](https://github.com/fyne-io/fyne) to build the netbird-ui and fyne is using OpenGL to provide cross-platform graphics.

**Comment by Fantu** [comment]
checking with glview seems that with rdp use the windows builtin opengl 1.1 driver (in software mode) but from https://github.com/fyne-io/fyne/issues/410 atleast opengl 2.0 is required :(
years ago FWIR we tried to activate greater support without a physical graphics card assigned to the VMs but we discarded it for issues
I suppose I'll must set these parameters with commandline (found today with --admin-url and --management-url), faster that manual edit of config.json and also faster that gui with a single "copy/paste" from rdp clipboard

**Comment by mlsmaycon** [comment]
Hello folks, the issue was fixed in 0.25.3.
