### ISSUE TITLE
ACLs do not have any impact on Network Routes

### ISSUE THREAD

**Issue by mkapra** [netbirdio/netbird#1216]
**Describe the problem**
It is possible to reach private networks even if there is no ACL allowing it.

**To Reproduce**
1. Register 2 peers
2. Add a new Network Route and append it to one of the peers
3. Disable default ACL that allows every traffic
4. e.g. ping the internal network created in Network Routes

**Expected behavior**
The ping should not go through because there is no ACL for it. I would expect that I need to create an ACL that allows the traffic to either the peer that routes to this internal network or to the internal network itself.

**Comment by braginini** [comment]
hey @mkapra 
If there is no connection between a peer and a routing peer, ping to the internal network shouldn't be possible.
The connection is created only if there is an ACL allowing the access. 

Could you please double check if there is no any other ACL allowing the connection between your pinging peer and the routing peer?
Is it possible that the network range that the routing peer routes overlaps with some local range of the pinging peer?

**Comment by mkapra** [comment]
Hi @braginini,

sorry for bothering you. It seems that there was a syncing issue for the ACL or something like that. The problem is gone now and netbird behaves like you explained.

**Comment by mlsmaycon** [comment]
Not a bother, thanks for the feedback @mkapra
