### ISSUE TITLE
Unable to receive verification code for netbird self-hosted email registration account

### ISSUE THREAD

**Issue by luobobo896** [netbirdio/netbird#1220]
I use the self-hosting platform built by Ubuntu, use the ui interface to register, and go to the interface receiving the verification code, but I never received the verification code. How can I solve this problem?

**Comment by mlsmaycon** [comment]
Hello @luobobo896, have you followed this [guide](https://docs.netbird.io/selfhosted/selfhosted-quickstart) with Zitadel? If so, Zitadel requires a SMTP configuration, see guide here: https://zitadel.com/docs/guides/manage/console/instance-settings#smtp

**Comment by braginini** [comment]
> I use the self-hosting platform built by Ubuntu, use the ui interface to register, and go to the interface receiving the verification code, but I never received the verification code. How can I solve this problem?

The script from this [guide](https://docs.netbird.io/selfhosted/selfhosted-quickstart) generates a user and a password for the administartor. You don't need to register. In case you want to add a new user in addition to the administrator, then you need set up the SMTP integration as @mlsmaycon pointed out.

**Comment by pigers** [comment]
link is borked , please provide new one.

**Comment by manojsomase** [comment]
> Hello @luobobo896, have you followed this [guide](https://docs.netbird.io/selfhosted/selfhosted-quickstart) with Zitadel? If so, Zitadel requires a SMTP configuration, see guide here: https://zitadel.com/docs/guides/manage/console/instance-settings#smtp

Link is not working....can please update....

**Comment by gecube** [comment]
@mlsmaycon https://zitadel.com/docs/guides/manage/console/instance-settings#smtp link is not working, unfortunately.

**Comment by mlsmaycon** [comment]
Try this one: https://zitadel.com/docs/guides/manage/console/default-settings#smtp

**Comment by gecube** [comment]
@mlsmaycon Hey! Thanks, but it is not what I expect. I want to configure Zitadel self-hosted. Preferably - in headless mode. Like with config file or better - ENV variables.

**Comment by krystofkrticka** [comment]
I'm also facing this issue even though I setup smtp access using netbid.[domainname].com/ui/console but it's still not sending emails. I clicked setup smtp in zitadel dashboard to set it up.

**Comment by braginini** [comment]
Hey guys, 
You should contact Zitadel support as this issue is not related to NetBird: https://github.com/zitadel/zitadel

**Comment by toriningen** [comment]
For anyone who has encountered this issue, it's easily resolved by logging with your admin account into https://your.domain.example/ui/console/instance?id=smtpprovider, then creating and activating SMTP provider there. It will also walk you through testing if it works. Voila, emails arrive.
