### ISSUE TITLE
Lock Settings

### ISSUE THREAD

**Issue by mrbluecoat** [netbirdio/netbird#1233]
Awesome project and I love how you support Ansible with API access tokens. Quick question: once I remotely deploy and configure a large set of school machines, how do I prevent someone disabling or modifying the settings on the device? Is there a "Lock Settings" option in the UI or API?

**Comment by braginini** [comment]
> Awesome project and I love how you support Ansible with API access tokens. Quick question: once I remotely deploy and configure a large set of school machines, how do I prevent someone disabling or modifying the settings on the device? Is there a "Lock Settings" option in the UI or API?

Hey @mrbluecoat 
What kind of settings do you mean? The network access is controled by the administrator in the web UI. The end users shouldn't be able to change settings.

**Comment by mlsmaycon** [comment]
Hello @mrbluecoat, it supports always-on on Android.

**Comment by mrbluecoat** [comment]
I was able to install NetBird on Android, connect, then configure the device (via Relution MDM) to use NetBird as always-on VPN + deny connections if disconnected. However, two issues arise:

1) A user can easily open the NetBird app and click the big disconnect button and the device loses all connectivity. To avoid help desk calls it would be nice to disable the disconnect button in the NetBird UI if configured as always-on.
2) The user loses all Internet connectivity (since exit nodes aren't supported yet: #289 )

**Comment by mlsmaycon** [comment]
Hello @mrbluecoat, thanks for the feedback, we would like to discuss your use case in detail. Would you join our [Slack workspace](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A) and reach out?

**Comment by mrbluecoat** [comment]
Thanks for the invite, @mlsmaycon, but I'm not on Slack. My use case is pretty straightforward: routing school Android device traffic through a gateway for content filtering. We're currently using IKEv2 since it's native on Android but would love the performance boost from WireGuard. Since our use case requires a hub-and-spoke architecture and NetBird is designed for mesh, it's not a perfect fit but we like your simplified UI and exclusively centralized settings management approach.

I'll close this ticket since it was noted above `end users shouldn't be able to change settings` and keep an eye on any future developments that may better fit our needs.
