### ISSUE TITLE
Error while trying to brew it in a m1 Mac

### ISSUE THREAD

**Issue by thinmanj** [netbirdio/netbird#124]
brew install wiretrustee/client/wiretrustee
==> Tapping wiretrustee/client
Cloning into '/opt/homebrew/Library/Taps/wiretrustee/homebrew-client'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 18 (delta 4), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), done.
Resolving deltas: 100% (4/4), done.
Error: Invalid formula: /opt/homebrew/Library/Taps/wiretrustee/homebrew-client/wiretrustee.rb
formulae require at least a URL
Error: Cannot tap wiretrustee/client: invalid syntax in tap!

**Comment by kneely** [comment]
I am having this issue as well

**Comment by mlsmaycon** [comment]
Hi @kneely  and @thinmanj, we are working on it and should be added in the next minor release.

**Comment by kneely** [comment]
@mlsmaycon I was able to install this on my M1 Mac Book Pro

**Comment by mlsmaycon** [comment]
> @mlsmaycon I was able to install this on my M1 Mac Book Pro

Thank you for confirming @kneely, appreciate you taking the time to check it.
