### ISSUE TITLE
Setup Keys Filters

### ISSUE THREAD

**Issue by hbzhost** [netbirdio/netbird#1259]
**Describe the problem**
When no setup keys are active I'm unable to see unused setup keys. In order to view them, I need to create temp key and then UI allows me to view old keys that were generated.

**To Reproduce**
1. Generate couple of keys.
2. Revoke all active keys
3. Go into UI and see if you can see old keys when no active keys are present.

**Expected behavior**
I would expect to view old keys even if I don't have active keys.
**NetBird status -d output:**
NA
**Screenshots**

<img width="1302" alt="image" src="https://github.com/netbirdio/netbird/assets/145801687/4b7a9cb4-fe9d-4823-bbc1-4794eb1f735a">

**Additional context**

**Comment by pascal-fischer** [comment]
Hi @hbzhost,
thanks for reporting this. You are totally right, this does not make sense.
We will be fixing it with the next release.

**Comment by hbzhost** [comment]
Thank you @pascal-fischer for quick response!

**Comment by mlsmaycon** [comment]
Hello @hbzhost, the fix was done in #291 and will be in the next release.
