### ISSUE TITLE
2FA For Non External IDP Accounts

### ISSUE THREAD

**Issue by hbzhost** [netbirdio/netbird#1260]
**Is your feature request related to a problem? Please describe.**
Allow non external IDP accounts to configure 2fa on Netbird. 

**Describe the solution you'd like**
Allow admins to enforece 2fa and to allow users to configure 2fa using something as simple as Google Auth. Another option is to use email as secondary auth, but using something like Google Auth is preferred. 

**Describe alternatives you've considered**
No alternative since right now if using non external IDP when accessing Netbird.
**Additional context**

**Comment by mlsmaycon** [comment]
Hello @hbzhost , currently, we support 2fa enforcement in our cloud-hosted service in the team plan. You can request this by sending an email to support@netbird.io. We also support different IDPs with OIDC support; if you need to enable them for your cloud account, please include this in the request to our support email.
