### ISSUE TITLE
Netbird 2FA Re-Prompt on Refresh

### ISSUE THREAD

**Issue by hbzhost** [netbirdio/netbird#1273]
**Describe the problem**
I'm being prompted each time I refresh my page to add my 2FA code when using Netbird.io internal IDP.

**To Reproduce**
1. Enable Netbird.io on account.
2. Configure your 2fa.
3. Log into your account using 2fa.
4. Go to any Netbird page and refresh your browser.
5. Browser will prompt you to re-auth with 2fa.

**Expected behavior**
I would expect that 2fa would only prompt when im logged out of my session.

**NetBird status -d output:**
NA
**Screenshots**
NA
**Additional context**

**Comment by mlsmaycon** [comment]
Hello @hbzhost this is happening when you mark the `Remember this browser` check box? See example below:

![image](https://github.com/netbirdio/netbird/assets/7747744/7d75f82b-f5cd-4175-a1ed-eb2462e85398)

**Comment by hbzhost** [comment]
Seems like selecting "remember this browser" fixes the issue. I would think this feature would only be used when signing in and it wouldn't prompt me again until my session is over and I re-login again. 

Thanks,

**Comment by mlsmaycon** [comment]
It should be like that. 

We will look into the behavior when renewing the authentication in the background and provide you a feedback.

**Comment by hbzhost** [comment]
Thank you!

**Comment by mlsmaycon** [comment]
Hello @hbzhost, this is fixed now. Let us know if you find other issues.
