### ISSUE TITLE
Self-hosted UI - How to copy reusable key?

### ISSUE THREAD

**Issue by WGandy** [netbirdio/netbird#1277]
There doesn't appear to be a way to copy a reusable key in the management UI after the initial setup. 
The way it used to work... You could click on the key and it would automatically copy it to your clipboard. Perhaps not the most secure option but very convenient. Now I can't find a way to reuse a key except to save it when I set it up. 

![image](https://github.com/netbirdio/netbird/assets/81717633/3e6e21f3-89ac-49e1-99ab-2b5ff2132d78)

**Comment by braginini** [comment]
@WGandy 
There is no way to do it. The key is shown one time after creation. You should save it somewhere safe.

**Comment by DENightOne** [comment]
I trick I use is to copy the reusable key as a note in my password manager....then I can retrieve on computer or phone.
