### ISSUE TITLE
Apple Silicon client - Does not accept setup key - invalid

### ISSUE THREAD

**Issue by WGandy** [netbirdio/netbird#1279]
![image](https://github.com/netbirdio/netbird/assets/81717633/b41f35e4-d1d6-471c-a58d-ff5061e74f47)

If I create a setup-key and then paste it into the Pre-shared Key field of the client UI, I get an error that the key value is invalid.

**Comment by dennispg** [comment]
I believe setup key is different from preshared key. To use a setup key you'll need to use the command line:

`netbird up --setup-key XXXXX`

**Comment by surik** [comment]
@dennispg thank you for helping with this issue. Much appreciated.

@WGandy I hope the reply above helps. I'm closing this for now. If you have any more questions about this please feel free to reopen.
