### ISSUE TITLE
Allow Peer "All" Group Removal

### ISSUE THREAD

**Issue by hbzhost** [netbirdio/netbird#1290]
**Is your feature request related to a problem? Please describe.**
We are looking to utilize Netbird in a way of multi tenancy by separating peer using groups. Currently, this works just fine without any issues from technical side of Netbird. However, we noticed a confusing issue that could come up from clients because of All group that is assigned to all peers. 

When client checks status by "netbird status" it shows all of the peers since they are all part of All group. This is very confusing and does now allow true separation of clients by their group. 

**Describe the solution you'd like**
Allow removal of All group from peers.

**Describe alternatives you've considered**
There isn't really alternative since right now its hard coded.
**Additional context**

**Comment by mlsmaycon** [comment]
Hello @hbzhost thanks for submitting the issue. This is happening not necessarily because of the group All. But it is happening because of an access control rule that is enabled and is using the group, perhaps the Default rule is still enabled. 

Can you check if that is the case and what is the behavior when disabling it?

**Comment by hbzhost** [comment]
That seems to be the case here. Is there a reason All is not allowed to be removed from peers?

**Comment by mlsmaycon** [comment]
This is a default system group for all peers in the account. 

When a peer is registered, it is added to the group automatically, which allows administrators to apply configurations to all peers and not worry about adding new peers to the group.

**Comment by hbzhost** [comment]
Sounds good and thank you!
