### ISSUE TITLE
Egress routing for internet

### ISSUE THREAD

**Issue by brandonkal** [netbirdio/netbird#1301]
**Is your feature request related to a problem? Please describe.**
I want to be able to route to the internet out of any of my nodes. Netbird does this easily through egress but netbird restricts routes to /7.

**Describe the solution you'd like**
Netmaker has the concept of Egress. I can route to 0.0.0.0/0 through another node. This cannot be done with netbird.

**Comment by surik** [comment]
Hi @brandonkal, I feel that this is similar to what was requested as Exit node in https://github.com/netbirdio/netbird/issues/289. I'm closing this one as duplicated.
