### ISSUE TITLE
Is it possible not to use third-party OIDC authentication but only local authentication?

### ISSUE THREAD

**Issue by 13653216371** [netbirdio/netbird#1304]
Is it possible not to use third-party OIDC authentication but only local authentication?
It feels like deploying keycloak is very troublesome!

**Comment by surik** [comment]
Hi @13653216371, unfortunately, there is no support for local authentication. The third-party Identity Provider is a requirement for now. Take a look at Zitadel, the installation process would not take more than 5 minutes. https://docs.netbird.io/selfhosted/selfhosted-quickstart

**Comment by mlsmaycon** [comment]
Hello @13653216371 have you got the chance to try the quickstart guide?

**Comment by 13653216371** [comment]
> 您好，您有机会尝试快速入门指南吗？



> Hello @13653216371 have you got the chance to try the quickstart guide?

Hello. The quick guide has been completed, and the business has been launched. Looking back on the whole process feels too complicated and not suitable for promotion to friends

**Comment by clywm520** [comment]
I run getting-started-with-zitadel.sh   
type in use-ip 10.0.12.7

http://10.0.12.7/nb-auth?code=umVFc729U0-k1nTv2LEEVhdEPPCBJOldB6eKucoS5UEbjQ&state=6mYZPE3dsy

but it is show  "Login Error: User state: Unauthenticated"

How to solve it？？？

@surik

**Comment by 0FiRE0** [comment]
> I run getting-started-with-zitadel.sh type in use-ip 10.0.12.7
> 
> http://10.0.12.7/nb-auth?code=umVFc729U0-k1nTv2LEEVhdEPPCBJOldB6eKucoS5UEbjQ&state=6mYZPE3dsy
> 
> but it is show "Login Error: User state: Unauthenticated"
> 
> How to solve it？？？
> 
> @surik

Same here

**Comment by surik** [comment]
@clywm520 @0FiRE0 Having a public domain is a requirement for self-hosted, please see https://docs.netbird.io/selfhosted/selfhosted-quickstart#requirements

**Comment by gaby** [comment]
@surik Like real domain name, or does a one generated via certmonger/ldap work (Lab setup)?
