### ISSUE TITLE
Add “official” systemd units?

### ISSUE THREAD

**Issue by hg** [netbirdio/netbird#1316]
Hello,

netbird has been [maintained](https://aur.archlinux.org/packages/netbird) in the Arch Linux User repository since 2021, and recently Arch developers [have expressed](https://aur.archlinux.org/packages/netbird#comment-944094) interest in packaging it in the official repository.

Would you be willing to merge hand-rolled systemd `.service` files instead of (or in addition to) `netbird service install`?

- the client config is a templated unit which allows the user to create & start multiple client instances by using `systemctl enable --now netbird@foo netbird@bar netbird@baz` (the part after the `@` matches the name of the config file in `/etc/netbird`)
- all units provide partial sandboxing from the rest of the system (#378, although netbird pretty much requires root or `CAP_NET_ADMIN` these days, they were much stricter in the past). The flags have been there for years and are pretty well tested by now.
- they can be used by other Linux distributions as the project gets more adoption

The files are [here](https://github.com/hg/aur/tree/master/netbird). I can prepare a PR if you're interested, or you can just copy them from there.

If you'd rather stay with `netbird service install`, Arch (and others in the future) will probably ship their own units.

Thanks.

**Comment by mlsmaycon** [comment]
Hello @hg this is awesome. We are interested in the PR. 

We are organizing the packaging files in the [release_files](https://github.com/netbirdio/netbird/tree/main/release_files) path, but we are open to suggestions to make it clear. 

Thanks for reaching out and for maintaining the package in the Arch Linux User repository.

**Comment by lfarkas** [comment]
i also vote for a separate service file not the generated one. it'd be much easier on all distro to use the same official service file!
