### ISSUE TITLE
Peer groups between web UI and API are inconsistent

### ISSUE THREAD

**Issue by kent-hydra** [netbirdio/netbird#1336]
**Describe the problem**
When using the API to retrieve peers, the groups listed on each peer are incorrect. I am seeing 2 different cases. The first seems to be more prevalent, most peers will lists all groups even if they are not part of those groups. The second case, peers are missing groups from the list that they belong to.

**To Reproduce**
1. Go to 'https://app.netbird.io/peers' to view a peers groups.
2. Use the API to pull list of peers from 'https://api.netbird.io/api/peers'.
3. Compare the list of groups from the JSON body to what is visible in the web UI.
4. See inconsistent data between the two.

**Expected behavior**
Group lists for each peer to be the same between the web UI and the API response.

**NetBird status -d output:**
N/A

**Screenshots**
Case 1, extra groups in JSON response that are not present in UI:

Note that the JSON lists a bunch of groups that should not be present. I would expect the "All" and "* Compute - Kansas - 1" group to be present as this is what was set via API and appears in the web UI.

![image](https://github.com/netbirdio/netbird/assets/120897091/ff7513fe-e7d3-4df7-826e-af05466789b6)

![image](https://github.com/netbirdio/netbird/assets/120897091/55549a48-95f9-48a7-8970-7b986c972c5d)

Case 2, group that should be present is missing:

Note that the "* - Texas 1" group should be present in the JSON body but it is not.

![image](https://github.com/netbirdio/netbird/assets/120897091/73e9b8d7-499d-4221-b8fd-81c962c3623e)

![image](https://github.com/netbirdio/netbird/assets/120897091/654f4ad8-ae4f-4587-b122-81a8e7820dec)

**Additional context**
N/A

**Comment by mlsmaycon** [comment]
Hello @kent-hydra thanks for reporting this. We found a bug that is fixed in #1337
