### ISSUE TITLE
No access to admin functions in Management UI

### ISSUE THREAD

**Issue by acrow-geo** [netbirdio/netbird#1372]
**Describe the problem**
I set up Netbird with Keycloak according to instructions from the official documentation, and can log in with the user from Keycloak, but the only menu item showing is "Peers", and I have no admin access to /settings, /users etc.

**To Reproduce**
1. Install Keycloak and set up as per netbird docs
2. Install netbird (on separate machine on EC2) and configure according to netbird docs
3. Access netbird UI in browser
4. Only menu item seen is "Peers"

![image](https://github.com/netbirdio/netbird/assets/141134655/58a818b2-9a25-4db8-a52c-eecd59b4a06d)

**Expected behavior**
Netbird dashboard should show Settings, Users etc menus.

Any help much appreciated, I'm sure I hit this once before and solved it with a bit of googling, but google fails me now!

**Comment by surik** [comment]
This was sorted out in Slack. It was an upgrade related leftover, deleting management volume and restarting helped. I'm closing it for now.

**Comment by surik** [comment]
Hi @JonnyBDev your case may be different. If I remember it right the original problem here was about leftover data after the upgrade of IdP server. We can try to solve your case on Slack or you can create a new GitHub issue.

**Comment by ic3cool** [comment]
> @surik Just an information. Not sure if it's about a wrongly configured Compose, but we are using paths for our deployments.
> 
> For example:
> 
> ```
>     volumes:
>       - ./coturn/turnserver.conf:/etc/turnserver.conf:ro
> ```
> 
> We are not using docker volumes at all (managed by Docker) but still, the deployment of Netbird added one volume without any content in it. ![image](https://private-user-images.githubusercontent.com/20868670/300760820-fe16b3c9-eaa7-4c7d-9ecb-4fef6919a292.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDY0MjcsIm5iZiI6MTcwODYwNjEyNywicGF0aCI6Ii8yMDg2ODY3MC8zMDA3NjA4MjAtZmUxNmIzYzktZWFhNy00YzdkLTllY2ItNGZlZjY5MTlhMjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEyNDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOGRiYWJkZWYyMDI3YzQ3MDcyN2FkZWQ0OGNhMzY1YTcxNzFlOTFjYTYwYWFkZWRhMTRiYzc5NDFkMDVjNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YSUps2r1YeT_rJyJtH9e9gbA_dv7H8oXn9C_qoV5E9Q)
> 
> We are facing this issue too. As I said we've deleted all volumes but still nothing more than the "Peers" category. We did not change any configuration. It's not an upgrade, it's a reinstall.

Hi,
Getting exact the samme issue.
Im using docker and the volume is empty when i start up the application.
Ive done the guide using Authentik as an IDP for self hosting and gone through the config several times. still the Netbird-user only get peer option in management-UI
