### ISSUE TITLE
Each machine gets assigned the same IP address when using a setup key (selfhost)

### ISSUE THREAD

**Issue by MacRentals** [netbirdio/netbird#1376]
When attempting to automate deployment of machines via a setup key, only the first machine gets recorded as a peer, and each subsequent machine seems to connect but is only assigned the same IP address as the first peer and is not accessible.

We are using netbird to have different groups of rental laptops on vpn for remote management. A scheduled task runs one time after the machine is imaged to run "netbird up --setup-key <key>", which seems to be working correctly but results in the above behavior. We are very interested in switch to netbird for our vpn, since currently about half of the hands-on time for preparing each laptop is installing and configuring Hamachi, and being able to use one key for as many machines as needed would be perfect for our use case.

NetBird status -d output on the second machine:

PS C:\Windows\system32> netbird status -d
Peers detail:
 commandbackup.netbird.selfhosted:
  NetBird IP: 100.80.227.71
  Public key: obMuR+RHyy3SevEOla/qXuMeAunWmLdy89scCSBB4Uo=
  Status: Disconnected
  -- detail --
  Connection type:
  Direct: false
  ICE candidate (Local/Remote): -/-
  Last connection update: 0000-12-31 16:00:00

Daemon version: 0.24.3
CLI version: 0.24.3
Management: Connected to https://[redacted].com:443
Signal: Connected to https://[redacted].com:443
FQDN: e86a64d91d8c.netbird.selfhosted
NetBird IP: 100.80.240.58/16
Interface type: Userspace
Peers count: 0/1 Connected

The FQDN here is identical to the first machine, despite the second laptop having a different hostname. What are we doing wrong?

**Comment by surik** [comment]
Hi @MacRentals, could it be that the client config is shared on all the machines? For example, if the config is part of the image.

**Comment by MacRentals** [comment]
That seems to have been the problem. I tried a fresh install without imaging and it worked properly. I guess we will need to figure out installing netbird via a script after imaging takes place.

Thanks for your help!

**Comment by natcl** [comment]
Didi you ever figure this out ? I am facing the sae issue on Linux, we have a base image with Netbird installed (but not registered) and as as soon as I register en instance on first boot it overwrites my peer instead of creating a new one...
