### ISSUE TITLE
How to turn off NetBird from autorun.

### ISSUE THREAD

**Issue by KirMozor** [netbirdio/netbird#1382]
How to turn off NetBird from autorun.

I have an openSUSE Leap 15.5 operating system

**Comment by KirMozor** [comment]
у меня как-то включился netbird и я забыл об этом, у моего интернета безлимитный трафик через впн не работает и я потерял 5 - 8 гигабайт впустую

**Comment by surik** [comment]
Hi @KirMozor, the current behavior is that if agent service is installed it will auto-connect after reboot. There is PR with an attempt to improve it https://github.com/netbirdio/netbird/pull/1161
