### ISSUE TITLE
Context Deadline Exceeded/Exception occurred. (Invalid class )

### ISSUE THREAD

**Issue by robertgro** [netbirdio/netbird#1418]
**Describe the problem**
I'm unable to connect a windows 10 peer to the network. There is no network adapter/interface anymore and I'm also unable to change settings as well as the netbird service is unable to start. My client.log throws the exceptions as mentioned in the title. Even re-installing didn't fix the issue.

**To Reproduce**
1. Have a 'malfunctioning' windows 10 client and install the latest netbird release
2. Receive the following errors
```
2023-12-28T22:32:16+01:00 ERRO management/client/grpc.go:64: failed creating connection to Management Service context deadline exceeded
2023-12-28T22:32:38+01:00 FATL client/system/info_windows.go:39: Exception occurred. (Invalid class )
```

**Expected behavior**
A working connection from the peer to the network.

**NetBird status -d output:**
```
Error: failed to connect to daemon error: context deadline exceeded
If the daemon is not running please run:
netbird service install
netbird service start
```

**Screenshots**
From the Event Viewer
![Screenshot 2023-12-28 235703](https://i.imgur.com/A23ooxv.png)
![Screenshot 2023-12-28 235754](https://i.imgur.com/CLl3YVJ.png)

XML
```
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/netbirdio/netbird/issues/new?assignees=&labels=&projects=&template=bug-issue-report.md&title=#) <System>
  <Provider Name="Service Control Manager" Guid="{555908d1-a6d7-4695-8e1e-26931d2012f4}" EventSourceName="Service Control Manager" /> 
  <EventID Qualifiers="49152">7034</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8080000000000000</Keywords> 
  <TimeCreated SystemTime="2023-12-28T21:40:12.7564885Z" /> 
  <EventRecordID>368114</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="412" ThreadID="500" /> 
  <Channel>System</Channel> 
  <Computer>XYZ</Computer> 
  <Security /> 
  </System>
[-](https://github.com/netbirdio/netbird/issues/new?assignees=&labels=&projects=&template=bug-issue-report.md&title=#) <EventData>
  <Data Name="param1">Netbird</Data> 
  <Data Name="param2">1</Data> 
  <Binary>4E006500740062006900720064000000</Binary> 
  </EventData>
  </Event>
```

**Additional context**
I already did 
```
netbird service uninstall
netbird service install --log-level debug
netbird service start
```
as mentioned in [https://github.com/netbirdio/netbird/issues/1361#issuecomment-1846979994](https://github.com/netbirdio/netbird/issues/1361#issuecomment-1846979994) but that didn't work either.

**Comment by mlsmaycon** [comment]
Hello @robertgro, it seems to be an issue with a WMI call we do to get the OS name, can you run the following command in Powershell?
```powershell
$os = Get-WmiObject -Class Win32_OperatingSystem
$osName = $os.Caption
Write-Host "Operating System: $osName"
```

**Comment by robertgro** [comment]
Hello @mlsmaycon, thank you for your reply. Issuing your snippet returns the following output on the affected peer
![Screenshot 2024-01-01 183550](https://i.imgur.com/KdyKZQY.png)

**Comment by mlsmaycon** [comment]
Thanks @robertgro for sharing the output. 

So, the class exists, but the client is unable to access it. Do you have a strict GPO that could cause this?

**Comment by robertgro** [comment]
The following GPO Administrative Templates Settings of the Local Computer Configuration Policy are applied to the client in question:
![Screenshot 2024-01-01 194903](https://github.com/netbirdio/netbird/assets/34941707/182d7109-670a-4bc1-b804-8705ea864f4c)

I'm pretty sure the RDP configuration didn't affect the process of the client being unable to access the class mentioned. The only change I would take into further consideration is maybe the '_Allow remote server management through WinRM_' key, whereby the configuration looks as follows:
![Screenshot 2024-01-01 195747](https://github.com/netbirdio/netbird/assets/34941707/7a718603-b850-48a5-88ae-0029351ee57c)

So I don't know if that is the root cause. If you need any additional information, don't hesitate to ask.

**Comment by mlsmaycon** [comment]
Thanks, @robertgro. We will take a deeper look into the issue. As a workaround, PR #1426 will return a default value in case of WMI call failure.

**Comment by robertgro** [comment]
I appreciate your effort @mlsmaycon and the PR you created. This should fix the issue in case the ```wmi.Query``` returns an error. I'll close this issue as soon as I've tested successfully.

**Comment by robertgro** [comment]
Closing this due to the peer is working now with the latest release. Thanks again @mlsmaycon for your contribution.
