### ISSUE TITLE
proxy peers FQDN in the management server

### ISSUE THREAD

**Issue by magixus** [netbirdio/netbird#1436]
**Is your feature request related to a problem? Please describe.**

Well, although it's not a problem yet but it's wasn't clear to me when I had my first impression with Netbird. 
I have a self-hosted netbird install with Zitadel, I have configured a bunch of peers, and they seem to connect to each other via domain name/IP. all worked as expected. nothing wrong. 

![image](https://github.com/netbirdio/netbird/assets/7642058/1b2b8fbe-0e72-4cf2-806a-ed4c61861922)

my domain is : `eu-vpn.domain.ltd`
I have added a wildcard CNAME in my DNS zone as : `*.eu-vpn.domain.ltd CNAME eu-vpn.domain.ltd.` in the hope that each peer FQDN would resolve to its instance. 

But  I think (I could be wrong) Netbird is not designed in such way ? isn't ? 

**Describe the solution you'd like**
I would like to be able to reach peers from internet using their FQDN, and not only between peers.

**Describe alternatives you've considered**
still looking for a workaround

**Comment by surik** [comment]
Hi @magixus, just to confirm do you want to be able to access private NetBird peers using their private IPs from other machines on the Internet that don't have the NetBird network? I'm afraid that this is not how it is designed right now as this is P2P mesh VPN. If you can describe your use-case we may try to find a workaround.

**Comment by magixus** [comment]
Hi @surik , Not exactly using Netbird peers' private IP but their address names. 
### Use case
Connect multiple edge devices (SBCs {raspberry pi mainly}) to the Netbird network. These SBCs act as an NVR and cameras gateway. I want to be able to reach each camera behind the SBC using peers FQDN like (edge-xxxxx.netbird.selfhosted/cam1 .../cam2 .../rtsp1 ...etc)
of course I have a reverse proxy installed in each SBC/peer to proxy each path (/camx) to its respective camera/device.
in general use case, I can configure different proxy_pass in my peers to reach various services behind them. like (RTSP, RTMP, WS ...etc)

**Comment by surik** [comment]
Ok, I see. Unfortunately, this is how it is designed right now. The `edge-xxxxx.netbird.selfhosted` is only accessible from the NetBird network. So to access that the client needs to have netbird agent up and running.

**Comment by magixus** [comment]
Thanks for confirming, that's what I thought. Would be interesting to see a workaround though

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
