### ISSUE TITLE
Add support for Windows as a routing peer

### ISSUE THREAD

**Issue by grahamIT** [netbirdio/netbird#1452]
## The problem

Currently Netbird is limited to just Linux hosts for routing peers. This is fine for a homelab or Linux server use case but becomes a problem for companies that need a way to remotely access devices on a network with 2-3 windows machines. I have tried installing it in WSL2 but the results have been a mixed bag and I would not recommend. 

## What it would look like

It should look the same on the dashboard as the Linux hosts. I want to be able route traffic out of windows hosts into the network just like I can with Linux hosts. 

## Other solutions I've considered

I have played around with Tailscale but there UI is frankly unpolished and permission controls are a massive pain. It also requires client intervention which makes it more of a headache.

**Comment by surik** [comment]
Hi @grahamIT, this is indeed missing right now. I will close this for now as we already have a similar request https://github.com/netbirdio/netbird/issues/1248. Please feel free to add there any relevant information.
