### ISSUE TITLE
What is the problem when installing?

### ISSUE THREAD

**Issue by HKbool** [netbirdio/netbird#1465]
export NETBIRD_DOMAIN=netbird.mydomain.com; curl -fsSL https://github.com/netbirdio/netbird/releases/latest/download/getting-started-with-zitadel.sh | bash
Rendering initial files...

Initializing Zitadel's CockroachDB

main: 第 63 行： 33828 段错误               $DOCKER_COMPOSE_COMMAND up -d crdb

**Comment by lixmal** [comment]
Hi @HKbool,

please check if running the command `docker compose up -d crdb` works without the script

**Comment by HKbool** [comment]
@lixmal   Thanks!  problem solved
