### ISSUE TITLE
netbird pre-shared not persistent again on linux and windows

### ISSUE THREAD

**Issue by support-tt** [netbirdio/netbird#1472]
**Describe the problem**
after upgrade netbird from 24.X to 25.X and saw, that my PSK was missing. Maybe this happened before and I dont saw it because all my peers lost theis PSK. When I do a manualy disconnect and connect (in UI and Shell version same problem) my PSK get removed from the configuration.

**To Reproduce**
1. Connect with PSK (netbird up --pre-shared-key "XXXXXX" or in UI)
2. Disconnect (netbird down or in UI disconnect)
3. Connect with netbird up or in UI
4. Key missing .. 

**Expected behavior**
PSK should be persistent over updates and disconnects/connects.

**NetBird status -d output:**
I see all my peers and connection is working im running the newest 0.25.4 version.

**Screenshots**
see #887 and #845 its the same problem then in the past 

**Additional context**
this was fixed I opened the issues #887 and #845 and tested it. So something changed again with the persistence of the configuration.

**Comment by support-tt** [comment]
tested it on windows now too some problem after reboot the PSK is also gone so no traffic encryption with PSK anymore. For me this is a central feature because if the netbird server gets hacked the hacker cant decrypt the traffic without the PSK.

**Comment by mlsmaycon** [comment]
@support-tt thanks for reporting the issue. I've tested and can confirm the bug since v0.24.3.

We will fix the issue and make a new release today.
