### ISSUE TITLE
Is there a way to disable signup on frontend page?

### ISSUE THREAD

**Issue by xoraingroup** [netbirdio/netbird#1490]
Hi,

 I don't have an issue or reporting bug. But my use case is I want to have one single admin account through which i can manage netbird. The rest I want to connect machines with netbird and don't want any user to sign up.

Is that possible?

thanks

**Comment by braginini** [comment]
I think that the best way to do it is via your IdP.
NetBird doesn’t have this feature it by itself.

**Comment by xoraingroup** [comment]
Thank you very much. I got it. Closing it now. :)
