### ISSUE TITLE
 Is the APP code open source?

### ISSUE THREAD

**Issue by HKbool** [netbirdio/netbird#1497]
https://github.com/netbirdio/netbird/tree/main/client/android

APP UI code and other information,Only GO code information

**Comment by HKbool** [comment]
How to compile  https://github.com/netbirdio/netbird/tree/main/client/android

**Comment by mlsmaycon** [comment]
Hello @HKbool it is not open-source yet, but it will be next month. 

As on how to compile the client lib, you can follow the steps from our workflows: https://github.com/netbirdio/netbird/blob/main/.github/workflows/mobile-build-validation.yml#L14

**Comment by HKbool** [comment]
@mlsmaycon   That's great  , Looking forward to APP source code

**Comment by lixmal** [comment]
https://github.com/netbirdio/ios-client
https://github.com/netbirdio/android-client
