### ISSUE TITLE
OpenWRT package not connecting

### ISSUE THREAD

**Issue by Darin755** [netbirdio/netbird#1498]
**Describe the problem**
I have installed the openwrt package but for Netbird but it seems to be unable to connect. I am running netbird version 0.23.4-1 and I get the error "Error: unable to get daemon status: rpc error: code = Unknown desc = couldn't check or load tun module
"

**To Reproduce**
Install the Netbird OpenWRT package from github and run Netbird up. 

**Expected behavior**
I expected it to work out if the box.

**NetBird status -d output:**
Error: status failed: couldn't check or load tun module

**Additional context**
I am running Netbird on a router with a mips CPU. It is possible this is related to the CPU arch.

**Comment by braginini** [comment]
The required drivers are missing. What you could try it installing WireGuard. This should bring kernel module to the device:
`opkg install wireguard`

**Comment by Darin755** [comment]
So I installed the wireguard kmod package and after doing a modprobe it started working. Thanks.
