### ISSUE TITLE
Network routes not working with iOS client

### ISSUE THREAD

**Issue by EnterTheC** [netbirdio/netbird#1525]
**Describe the problem**

I've installed self hosted netbird version 0.25.5, identity provider is microsoft azure/entra. Added custom DNS to resolve my private AD domain (internal.example.com) and added a network route to my private network range (10.0.0.0/24), routing peer is a ubuntu linux vm with installed netbird client and connected as a peer. If i connect my windows notebook via netbird I am able to connect to internal services within my private network via iPhone hotspot. So in my opinion everything's fully working right now except one thing: If i connect my iPhone (iPhone 14, iOS 17.3 i think) then all peers connect the same way they do when I connect my notebook but neither ips are resolved nor dns names (e.g. test-client.internal.example.com or 10.0.0.5). As far as it seems I'm getting a IPv4 adress via cellular and via hotspot this is working. This issue is just with the iOS-client :/

**To Reproduce**

1. Install netbird self hosted
2. Add DNS with internal nameserver and dns name
3. Install VM (or barebone) ubuntu / linux machine and connect netbird client
4. Add network route to private network via linux machine mentioned in 3.
5. Connect via windows / macOS notebook - fully working
6. Connect via iPhone...
9. See error

**Expected behavior**

I'd like to use my internal services via iPhone

**Are you using NetBird Cloud?**

Self-hosted netbird

**NetBird version**

`netbird version 0.25.5`

**NetBird status -d output:**

Not applicable

**Screenshots**

Not applicable I guess.

**Additional context**

n/a

Is there anything I can do to get this one working? :)
 

Regards
Chris

**Comment by pappz** [comment]
Hello @EnterTheC,
Could you double check the iOS is in the same group than your other devices?

**Comment by EnterTheC** [comment]
@pappz checked it, they're all in the same group (default 'all').

**Comment by pappz** [comment]
When you open the NetBird app on your iPhone device what shows the "Peers connected" page? The connection between the router peer and your device has been established?

**Comment by EnterTheC** [comment]
Yep, the routing peer is in status 'connected' within the peers-page.

**Comment by EnterTheC** [comment]
Wanna let you know that I just updated to iOS app version 0.0.3 and everything's fully working now on my iPhone. Thank you so much 🫡

**Comment by mlsmaycon** [comment]
That's great, thanks for confirming @EnterTheC

**Comment by imtpot** [comment]
I have the same problem but only when my iPhone connected to WiFi. With cellular all seems good.
MacBook works without any issues through WiFi.
iPhone netbird version 0.0.3

**Comment by wgfilho** [comment]
Hi!

I have a similar intermittent problem. I'm not using self-hosted NetBird. This is what I do:

- Network route is configured
- On iOS, connect to Netbird
- Try to ping any internal ip/name, it doesn't work
- Connect/disconnect a few times, eventually it works.
- Sometimes, I try on the iOS client to disable/reenable the network route and everything starts working.

It's weird because it's intermittent, sometimes I'm able to ping, sometimes not. So, I guess that means that the configuration is correct. 

What information do you need me to provide to help debug it? 

Thanks!
