### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MANKUD** [netbirdio/netbird#153]
Hello,

It would be really great if the peers tab on https://app.wiretrustee.com/peers would allow us to rename the displayed computer name for easy identification and also please add the current public IP address of the peer to the column.

**Comment by braginini** [comment]
@MANKUD thank you for creating this issue.
I think it all makes sense and shouldn't be complicated to add.
I will let you know once we plan this features

**Comment by MANKUD** [comment]
@braginini 
 
That would be great Thank You :)
