### ISSUE TITLE
"Add Rule" button opens "Add Route" dialog if no rules are present

### ISSUE THREAD

**Issue by b00nish** [netbirdio/netbird#1561]
**Describe the problem**

If there is a total of 0 rules existing, the button "Add **Rule**" will open the "Add **Route**" dialog instead of the "Add Rule" dialog. Therefore you can't create any more rules.

**To Reproduce**

1. Go to "Access Control" in the web interface
2. Delete all rules
3. Click on "New Rule"
4. See the "New Route" dialog appear instead of the "New Rule" dialog

**Expected behavior**

It is expected and necessary that the "New Rule" button brings up the "New Rule" dialog because otherwise one is stuck with no rules and therefore an unuseable Netbird instance.

**Are you using NetBird Cloud?**

Self-Hosted

**NetBird version**

I assume 0.25.6 because I installed today

**Comment by surik** [comment]
Fix: https://github.com/netbirdio/dashboard/pull/326

**Comment by surik** [comment]
This should be fixed. Please feel free to reopen it if you are still experiencing the same.
