### ISSUE TITLE
`netbird-ui` rolls back the daemon to default interface and port

### ISSUE THREAD

**Issue by nazarewk** [netbirdio/netbird#1581]
**Describe the problem**

A complete opposite of https://github.com/netbirdio/netbird/issues/1562 : `netbird-ui` rolls back the daemon to default configuration `wt0:51820` no matter what I set up on the actual `systemd` service.

https://github.com/NixOS/nixpkgs/pull/287236#issuecomment-1941859301

**To Reproduce**

**Expected behavior**

**Are you using NetBird Cloud?**

Please specify whether you use NetBird Cloud or self-host NetBird's control plane.

**NetBird version**

`netbird version`

**NetBird status -d output:**

If applicable, add the `netbird status -d' command output.

**Screenshots**

**Additional context**

**Comment by nazarewk** [comment]
I tried locating the issue in the code, but cannot pinpoint anything.

**Comment by surik** [comment]
Hi @nazarewk I was trying to reproduce the issue but not luck. Can you give more information about the version you use and maybe do an additional checks of the `/etc/netbird/config.json`. Where do you notice that values are reverted to the defaults?

**Comment by nazarewk** [comment]
It happens when I *Connect*/login through the UI

**Comment by surik** [comment]
Can you make an additional test to prove an assumption. 
1. Run `netbird down`
2. Try to connect via CLI: `netbird up --interface-name wt1 --wireguard-port 51840` or any other name/port
3. Check `/etc/netbird/config.json`
4. Disconnect via UI
5. Connect via UI
6. Check `/etc/netbird/config.json`

**Comment by nazarewk** [comment]
During Slack conversation it was pointed out I was starting without any config whatsoever and neither `netbird service up` nor `netbird-ui` support passing the interface/port configuration.

So this is issue caused by #1562
