### ISSUE TITLE
Android app invalid server address

### ISSUE THREAD

**Issue by chrisguen** [netbirdio/netbird#1583]
**Describe the problem**

Trying to change the server  to my selfhosted server gives "invalid server address" error. Tried on Galaxy S24 and S23 Ultra. Working perfectly fine on multiple Linux clients and site is reachable on the mobile browser. Netbird Cloud connection also works.  Also worked on previous Versions.

**To Reproduce**

1. Download app
2. go to change server to selfhosted
3. See error

**Expected behavior**

Can change the server and connect to Netbird network.

**Are you using NetBird Cloud?**

No

**NetBird version**

Mobile: 0.0.20 as stated in the app (in the cloud interface it says 0.25.6)
Management: 0.25.8

**Comment by surik** [comment]
Hi @chrisguen I just tested this and could not confirm. How do you insert the URL? Does it have `https://`?

**Comment by chrisguen** [comment]
Yes, with and without https, with or without port but it won't work.

**Comment by surik** [comment]
Oh, then I have two suggestions:
1. Clean up storage and cache. This is somewhere in the Android menu -> Settings/apps/app info/NetBird. Please take a look at the screenshot.
2. If there is no luck, let's get some debug logs from the server. Extend management service command in docker-compose with `"--log-level", "debug"` and restart the service. Try to connect and then see if something in the log. You also can share it here if you feel comfortable.

<img width="640" alt="image" src="https://github.com/netbirdio/netbird/assets/708165/82502c94-46fe-4f25-8212-d3846ccfba6b">

**Comment by chrisguen** [comment]
I already cleared the storage, still the same. And nothing in the Logs. Is there an easy way to debug the app?

**Comment by surik** [comment]
@chrisguen Will you be able to share the logs here or send them to our support email? Regarding additional debugging, I can suggest the following:

Enable the ADB in the developer menu on the Android device. In the app please set the the Trace log level setting. It is a checkbox in the advanced menu.
With the ADB tool, you can get the logs from your device. The ADB is part of the SDK platform tools pack (zip file). You can download it from [here](https://developer.android.com/tools/releases/platform-tools). Please extract it and run the next command in the case of Linux: `sudo adb logcat -v time | grep GoLog`. Please share the results with us.

**Comment by chrisguen** [comment]
This is the error im getting: `(16546): [WARN] client/android/login.go:224 retrying Login to the Management service in 5.328879868s due to error invalid provider configuration received from management: PKCE Redirect URLs value is empty. Contact your NetBird administrator
`

**Comment by surik** [comment]
Any recent changes in the management.json? Check `PKCEAuthorizationFlow.RedirectURLs`, this should not be empty.

**Comment by surik** [comment]
@chrisguen please follow the manual: https://docs.netbird.io/selfhosted/identity-providers#step-1-create-o-auth2-open-id-provider

**Comment by mlsmaycon** [comment]
@chrisguen in the mean time, how did you authenticate your other peers?

**Comment by chrisguen** [comment]
> @chrisguen in the meantime, can you share how you authenticated your other peers?

It just worked like normal, netbird up and logging in via the link.
Im doing a full reinstall right now, that fixed the PKCE redirect url and another problem I was having with the coturn server. But Im still having a couple problems. For some reason NB is not getting the  correct Name and email from Authentik, its just using the Authentik user ID as Email and nothing else. BTW I think you should add the Android debugging command to the docs.

**Comment by moontide** [comment]
In my case, I had to change server port to `33073` (full url will be `https://my-netbird-host:33073`) to get it work.

**Comment by HammyHavoc** [comment]
> In my case, I had to change server port to `33073` (full url will be `https://my-netbird-host:33073`) to get it work.

Just experienced the same problem. Is this as-expected?

**Comment by heroes1412** [comment]
> In my case, I had to change server port to `33073` (full url will be `https://my-netbird-host:33073`) to get it work.

at the moment, it not works. still show "Invalid server address"
