### ISSUE TITLE
failed to login Windows 10 localhost:53000 refused

### ISSUE THREAD

**Issue by raptaml** [netbirdio/netbird#1696]
**Describe the problem**

When I click login on the windows GUI client, it seems to redirect to localhost:53000 and that gives me: connection refused.

**To Reproduce**

1. Right-click GUI Connect
2. Wait for browser window to open
3. Wait for redirect to happen

**Expected behavior**

Redirect should work and you should be presented with auth provider list (MS, google etc)
Problem most likely has to do with: 
[https://ardalis.com/attempt-made-to-access-socket/](https://ardalis.com/attempt-made-to-access-socket/)
and
[https://support.microsoft.com/en-us/topic/february-13-2018-kb4074588-os-build-16299-248-b4e2ca66-dd7a-6fd5-a8f3-dc6683d4922b](https://support.microsoft.com/en-us/topic/february-13-2018-kb4074588-os-build-16299-248-b4e2ca66-dd7a-6fd5-a8f3-dc6683d4922b)
because `netsh interface ipv4 show excludedportrange protocol=tcp` shows:

```
Portausschlussbereiche für das Protokoll tcp

Startport      Endport
----------    --------
      2869        2869
      5357        5357
     49280       49379
     49380       49479
     49480       49579
     49713       49812
     49813       49912
     50000       50059     *
     50060       50159
     50389       50488
     52679       52778
     52830       52929
     52930       53029
     53030       53129
     53439       53538
     53539       53638
     53639       53738
     53739       53838
     53839       53938
     54039       54138
     56577       56676
     56678       56777
     58089       58188
     58189       58288
     62778       62877
```

But I cannot change the port 53000 Netbird service binds to.

**Are you using NetBird Cloud?**

Yes, Netbird Cloud is used.

**NetBird version**

0.26.2 and 0.26.3 tested

**Comment by raptaml** [comment]
OK managed to fix it with the advice given here:
[](https://superuser.com/questions/1579346/many-excludedportranges-how-to-delete-hyper-v-is-disabled)

**Comment by pappz** [comment]
Hi! @raptaml 
Thank you for the feedback! Can we close the issue?

**Comment by raptaml** [comment]
Hi,
yes you can close it.
