### ISSUE TITLE
SSO Setting wont save

### ISSUE THREAD

**Issue by servinformaticaelche** [netbirdio/netbird#1708]
When we update in **Settings - Authentication** the **peer login expiration time** changing from **hours** to **days** and save, Netbird returns that the changes have been updated but in reality if we move through the app and go back to the configuration the combo box has been changed to hours.

**Are you using NetBird Cloud?**

self-host NetBird's

**NetBird version**

Latest docker recreated

**Screenshots**

https://github.com/netbirdio/netbird/assets/54945582/6be50ced-cd1a-4dd1-b38d-f111aa821653

**Comment by pappz** [comment]
Thank you for the report! We will fix it in the next release.

**Comment by pappz** [comment]
The Dashboard has been refreshed. Could you take a test?

**Comment by servinformaticaelche** [comment]
Yes. I used instead Shift+F5 to refresh cache and changes not saved.

**Comment by mlsmaycon** [comment]
@servinformaticaelche can you update your setup? you can follow this guide: https://docs.netbird.io/selfhosted/selfhosted-quickstart#upgrade

**Comment by servinformaticaelche** [comment]
Ok. I updated the docker and now works fine.

thanks

**Comment by mlsmaycon** [comment]
Thanks for confirming.
