### ISSUE TITLE
Add IPV6 support on apt repo 

### ISSUE THREAD

**Issue by Askotion** [netbirdio/netbird#1714]
**Is your feature request related to a problem? Please describe.**
Im not able to install the package on linux on IPV6 only server as the package repo is v4 only. 
Sadly even Github is v4 only so im not even able to download it through the releases. 

pkgs.netbird.io

**Describe the solution you'd like**
Add IPV6 support for the package repo

**Comment by mlsmaycon** [comment]
Hello @Askotion, we've just added support to ipv6 for the pkgs.netbird.io domain.
