### ISSUE TITLE
User invites not avaliable on self-hosted deloyment using Authentik

### ISSUE THREAD

**Issue by callumgare** [netbirdio/netbird#1717]
**Describe the problem**

The "Invite User" button you get on the cloud version of Netbird is not available when using the self-hosted service with Authentik IdP.

Cloud:
<img width="1512" alt="image" src="https://github.com/netbirdio/netbird/assets/346340/111418ac-7b61-436c-ba3e-ea2e8468fa85">

Self-hosted with Authentik:
<img width="1512" alt="image" src="https://github.com/netbirdio/netbird/assets/346340/01c4a77f-8921-40cc-8486-3b515fe7003c">

**To Reproduce**

1. Setup self-hosted Netbird with Authentik for the IdP following the [official guide](https://docs.netbird.io/selfhosted/identity-providers#authentik)
2. Go to the users tab in the Netbird web interface
3. Observe that there is not "Invite User" button

**Expected behavior**

An "Invite User" button to be visible.

**Are you using NetBird Cloud?**

Self-hosted

**NetBird version**

[0.26.3](https://hub.docker.com/layers/netbirdio/management/0.26.3/images/sha256-d6e26bad5f1aa1b8aac9b43a040c8f0748d8cdfda3852743ad9abf5ad64c523b?context=explore)

**NetBird status -d output:**

N/A

**Additional context**

[This issue](https://github.com/netbirdio/netbird/issues/855) is related but was for the "User Invites" button not showing for self-hosted developments in general and was closed after support was added for self-hosted setups using Keycloak which solved the problem for the original poster.

**Comment by braginini** [comment]
Hi @callumgare 
There are two points here:
1. In our opinion it doesn’t make sense to support invites in the self-hosted version as the administrators of self-hosted NetBird setups usually have a full control of the identity provider. They can create and invite users from there. It is more flexible and less error prone. 
2. Supporting this in the self-hosted might become a complex task as we would need to support different IdPs with different APIs. It can also cause a confusion because some users might assume that it would work out of the box, however a proper SMTP server must be configured in the IdP beforehand.


What do you think?

**Comment by callumgare** [comment]
If it's possible to achieve the same result by adding users in the IdP that would certainly work for me. However when I create a new user (with an email in the same domain or not), grant that user access to Netbird then attempt to login to Netbird with that user, it always puts that user in new team rather than adding it to the existing team.

<img width="1313" alt="image" src="https://github.com/netbirdio/netbird/assets/346340/f69a2973-f2c5-4a10-bfca-c505a0ae343a">

<img width="1180" alt="image" src="https://github.com/netbirdio/netbird/assets/346340/87be1621-533a-4ac2-b540-0a0cf4b0c8dc">

Is it possible to add to the same team and do you know how I'd do that?

**Comment by callumgare** [comment]
The only documentation I could find on the subject suggested the opposite should be happening:

"This feature isn't available in the self-hosted setup. By default, all users are joining the same network instead" -https://docs.netbird.io/how-to/add-users-to-your-network

**Comment by braginini** [comment]
It is possible @callumgare. 
You have probably disabled the single account mode. By default netbird puts everyone under the same account in the self-hosted setups.

It will be now hard to reset the configuration as you already have multiple accounts. It will require a manual adjustment to merge the accounts. 

Alternatively, you could just recreate NetBird management volumes to start with a clean state. Make sure that you keep the management section in the docker compose as in the example: https://github.com/netbirdio/netbird/blob/416f04c27a10309f70f1f376a0e8db0ed57f1aad/infrastructure_files/docker-compose.yml.tmpl#L58

**Comment by callumgare** [comment]
Ah I see! When I was setting up netbird I figured "disable single account" ment that it enabled the use of multiple users and thus that's what I wanted. I've reset everything and removed that flag and things seem to be working as expected now. Even if I add a user who's email has a different domain to the owner user. Thanks very much!
![Screenshot 2024-03-18 at 14 26 16](https://github.com/netbirdio/netbird/assets/346340/b628f839-61d7-4129-86ba-abe973d20b33)

**Comment by BJorah** [comment]
Hi !@callumgare 
Are you disable signal-account-mode so that you can create multiple net on one self-hosted server?
Would you please tell me how to config it to disable the signal-account-mode?

**Comment by AndreKR** [comment]
@braginini Above you said

> In our opinion it doesn’t make sense to support invites in the self-hosted version as the administrators of self-hosted NetBird setups usually have a full control of the identity provider. They can create and invite users from there. It is more flexible and less error prone.

In non-single-user-mode, after I have created a user in the IdP, by default the user ends up in a new Netbird account, correct? How do I move the user into an existing account?
