### ISSUE TITLE
[SELF-HOSTED] Peer Public IP showing local docker network gateway

### ISSUE THREAD

**Issue by sgtaziz** [netbirdio/netbird#1728]
**Describe the problem**

On a self-hosted installation, all clients have a "Public IP Address" set as the docker network gateway. Using "host" network mode for the management service changes that IP to 127.0.0.1.

**To Reproduce**

1. Self-host netbird
2. Join a peer
3. Open Peers page on Netbird UI
4. See peer IP Address and Region "Unknown"

**Expected behavior**

Peer IP Addresses should be correctly set. Perhaps from the COTURN server?

**Are you using NetBird Cloud?**

No, self-hosted

**NetBird version**

```
netbird version
0.26.3
```

**Screenshots**

![image](https://github.com/netbirdio/netbird/assets/5303104/b51cfde9-5e9a-4a6e-b57c-1d70a927b74d)

**Comment by somnium78** [comment]
I have the same problem on almost all my docker hosts with a single exception where the correct ip is displayed.

**Comment by sgtaziz** [comment]
Just to clarify, all my peers having this issue are normal clients. iOS, Linux, and Windows. The selfhosted instance is the only thing running on docker.

**Comment by Askotion** [comment]
Hi,

unfortunately this doesn't fix it for setups without reverse proxy. My "Public IP-Address" always shows the docker gateway for my netbird server on all linux peers. MacOS peers are not affected.

**Comment by turbotorsten** [comment]
> Hi,
> 
> unfortunately this doesn't fix it for setups without reverse proxy. My "Public IP-Address" always shows the docker gateway for my netbird server on all linux peers. MacOS peers are not affected.

Can confirm, public IP is broken for almost all my docker hosts. Strangely, some do display the correct public IP.

**Comment by pomology** [comment]
I have the same issue.  Someone above said MacOS peers were not affected, but mine are.

**Comment by mlsmaycon** [comment]
Guys, can you open a new issue and share more details about your setups? The IP address are checked using regular reverse proxy headers. So it will be important for us to learn what is your current setup, like are you using a reverse-proxy like nginx?

**Comment by pomology** [comment]
[https://github.com/netbirdio/netbird/issues/1970](url)
