### ISSUE TITLE
Netbird.io dead ?

### ISSUE THREAD

**Issue by ayoahha** [netbirdio/netbird#1730]
Hi
Is [netbird.io](https://netbird.io) dead ?

I cannot join the URL.
Thanks
Best regards

**Comment by lixmal** [comment]
Can you share the exact issue that you face?

Is it netbird.io or app.netbird.io?

**Comment by ayoahha** [comment]
> Can you share the exact issue that you face?
> 
> Is it netbird.io or app.netbird.io?

Ive just tried right now. And all is ok
It seems it was a DNS issue !

Sorry for this issue
