### ISSUE TITLE
Unable  to setup Entra ID 

### ISSUE THREAD

**Issue by arnokretschmer** [netbirdio/netbird#1739]
Hello,
I don't know what I'm doing wrong - can somebody help me please?
The Management Container logs:
024-03-21T15:34:47Z WARN management/server/account.go:888: failed warming up cache due to error: unable to get https://graph.microsoft.com/v1.0/users?%24select=id%2CdisplayName%2Cmail%2CuserPrincipalName&%24top=500, statusCode 403
2024-03-21T15:35:14Z INFO management/server/account.go:1582: overriding JWT Domain and DomainCategory claims since single account mode is enabled
2024-03-21T15:35:14Z ERRO management/server/http/middleware/auth_middleware.go:88: Error when validating JWT claims: unable to get https://graph.microsoft.com/v1.0/users?%24select=id%2CdisplayName%2Cmail%2CuserPrincipalName&%24top=500, statusCode 403

my setup.env:
...
NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT="https://login.microsoftonline.com/TENANTID/v2.0/.well-known/openid-configuration"
NETBIRD_AUTH_AUDIENCE="APP-ID"
NETBIRD_AUTH_CLIENT_ID="APP-ID"
NETBIRD_AUTH_SUPPORTED_SCOPES="openid profile email offline_access api://APP-ID/api"
NETBIRD_AUTH_USER_ID_CLAIM="oid"
NETBIRD_USE_AUTH0="false"
NETBIRD_AUTH_DEVICE_AUTH_PROVIDER="none"
NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID=""
NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE=$NETBIRD_AUTH_AUDIENCE
NETBIRD_AUTH_DEVICE_AUTH_SCOPE="openid"
NETBIRD_AUTH_DEVICE_AUTH_USE_ID_TOKEN=false
NETBIRD_AUTH_PKCE_REDIRECT_URL_PORTS="53000"
NETBIRD_MGMT_IDP="azure"
NETBIRD_IDP_MGMT_CLIENT_ID=$NETBIRD_AUTH_CLIENT_ID
NETBIRD_IDP_MGMT_CLIENT_SECRET="SECRET"
NETBIRD_IDP_MGMT_EXTRA_GRAPH_API_ENDPOINT="https://graph.microsoft.com/v1.0"
NETBIRD_IDP_MGMT_EXTRA_OBJECT_ID="Object-ID-REGISTERED-APP"
NETBIRD_AUTH_REDIRECT_URI="/auth"
NETBIRD_AUTH_SILENT_REDIRECT_URI="/silent-auth"

Thanks

**Comment by arnokretschmer** [comment]
I made an Error on the Permissions at Entra

**Comment by Bastika07** [comment]
What kind of errors did you had? I have the same issue and can´t find it.

**Comment by arnokretschmer** [comment]
I mixed up the permission type;
the API must be a delegated  permission and the User.Read.All must be an application permission.
