### ISSUE TITLE
Update Android (and iOS?) Apps.

### ISSUE THREAD

**Issue by emielpopla** [netbirdio/netbird#1758]
**Is your feature request related to a problem? Please describe.**
I have quite some services running on an internal network. These services are only accessible via their domain names using the internal DNS server running on my OPNsense router. To gain access to these services using NetbirdI set up a network route and defined the DNS server in Netbird. This works flawlessly on my laptop but doesn't work on my android devices. I assume it is because the android devices are still running version 0.25.6? 

**Describe the solution you'd like**
Update the android (and iOS? haven't tested those yet) apps to the newest Netbird version to be able to use networking routes and nameservers on internal networks. 

**Describe alternatives you've considered**
Alternatively, add OPNsense support for netbird, which I saw was on the roadmap for Q2, but a faster solution would be preferred.

**Additional context**
Having this functionality is crucial for me to rollout Netbird as an easy to use and setup vpn to my family to use these services.

**Comment by iball** [comment]
![image](https://github.com/netbirdio/netbird/assets/1633825/7ce287de-574d-4963-befa-26576f2cdb57)
Yeah, it's kind of annoying that the Peers web GUI keeps telling me I should upgrade my Android and iOS Netbird clients to the latest version when they *are* already on the latest version that has been released for those platforms.

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
Can't wait for the exit node feature on Android. Is there a reason why the app is behind?

**Comment by mlsmaycon** [comment]
Hello Folks, the mobile apps are following a different cycle as they don't get fundamental changes on every release of the main clients.

That said, we plan to update the iOS app next week with support for exit nodes, and Android support will follow soon after that.

**Comment by emielpopla** [comment]
Exit nodes are now supported so closing the issue. Thanks for the good work!
