### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by davinellulinvega** [netbirdio/netbird#1761]
**Describe the problem**

After updating the Linux Netbird Client via the AUR repository from version 0.26.3-1 to version 0.26.4-1, the client cannot connect to the network anymore.
Running any `netbird` related command simply returns the following error message: `Error: status failed: init route manager: setup routing: add rule v6 netbird: add routing rule: address family not supported by protocol`

**To Reproduce**

1. Update netbird client to version 0.26.4-1 on linux
2. Run `sudo netbird service start` from command line

**Expected behavior**

I expected the client to connect to the existing network, but no such luck.

**Are you using NetBird Cloud?**

I am currently self-hosting the NetBird control panel on an AWS instance.

**NetBird version**

Installed version is 0.26.4

**NetBird status -d output:**

As with any other command, at the moment the output is just an error message: `Error: status failed: init route manager: setup routing: add rule v6 netbird: add routing rule: address family not supported by protocol`

**Additional context**

In an attempt to make the debugging process easier, I have enabled the debug logs. Here is the file resulting from simply starting the netbird client via systemd: [client.log](https://github.com/netbirdio/netbird/files/14783798/client.log)
It should be noted that no messages are being written to either the `nebird.out` or `netbird.err` files.

**Comment by davinellulinvega** [comment]
A few additional pieces of information:

- I have now updated the self-hosted control panel to the latest version as well.  
- The issue does not reproduce on armbian, as far as I can tell it is limited to Arch Linux (kernel 6.8.2).  
- I tried setting up the binary variant of the netbird package which is available on [AUR](https://aur.archlinux.org/packages/netbird-bin) with similar results.

**Comment by lixmal** [comment]
Hi @davinellulinvega,

this is an issue that pops up when ipv6 is disabled. I'll work on a fix.
Can you enable IPv6 as a temporary workaround to see if that fixes the issue? Basically the inverse of https://wiki.archlinux.org/title/IPv6#Disable_functionality

**Comment by davinellulinvega** [comment]
@lixmal You are entirely correct, after enabling IPv6 again the client works as expected.
This also means that my previous statement was wrong. It is not linked to the OS.

Regardless, thank you very much for the help.
