### ISSUE TITLE
Enable an always up option.

### ISSUE THREAD

**Issue by Leopere** [netbirdio/netbird#182]
It seems that the `wiretrustee up` command needs ran at regular intervals to ensure that the service never disconnects without any warning and self-healing.  Is it possible to have a baked-in option to auto-heal the connection?

**Comment by braginini** [comment]
Hey @Leopere 
What version are you using?
In the recent versions we do self-healing and the only time the client app should stop is when it tried to connect unsuccessfully for 3 days in a row.

If you are using the latest version (0.3.2) then there must be a bug

**Comment by Leopere** [comment]
ok good to know, I tend to update frequently and I'm doing it from the Ubuntu repo so it should have the latest.

**Comment by Leopere** [comment]
Being revisited by this wonderful gem, I really want to stay with Netbird its such a useful tool but I'm getting to a point where I'm losing my mesh about once every 12 hours or so and its becoming very functionality inhibitive.  I'm running a docker swarm over this mesh and its consistently breaking my GlusterFS mounts.  Pls halp!

**Comment by mlsmaycon** [comment]
Hi @Leopere, sorry to hear that you are running into these issues. 

I would like to get more information from your setup to troubleshoot the issue. Is it possible for you to reach out to me on our slack? this will make things much faster to check.

**Comment by Leopere** [comment]
Oh sure yes I'll pop in over the next couple days I need this fixed if possible sooner than later I just recently upgraded to 0.8.6 and that's about when it started to melt.  It seems my hybrid mesh between 20 something local devices on my LAN and 2 or three in the cloud at DigitalOcean.

**Comment by mlsmaycon** [comment]
the issue was caused by a race condition in our signal system, which was fixed here in #431
