### ISSUE TITLE
OpenSUSE Tumbleweed netbird-ui not working

### ISSUE THREAD

**Issue by jWXZSCsqrpZRSVwauBjn** [netbirdio/netbird#1850]
**Describe the problem**
There isn't an official way of installing it on OpenSUSE Tumbleweed and using the yum repository doesn't work as expected for netbird-ui. Probably I'm missing a package. The cli works as expected.

**To Reproduce**

1. I added the repository to Zypper using following command:
`sudo zypper ar https://pkgs.netbird.io/yum/ netbird`

2. Then installed it using:
`zypper in netbird netbird-ui`

3. Start netbird-ui
`Gtk-CRITICAL **: 11:09:13.246: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed`

**Expected behavior**
netbird-ui starting

**Are you using NetBird Cloud?**
No.

**NetBird version**
0.27.3

**NetBird status -d output:**
Not needed, only problems with netbird.ui

**Screenshots**
![image](https://github.com/netbirdio/netbird/assets/38642711/cf91dd55-a45b-4832-9564-582908cbb3f8)

**Additional context** 
Read that it might have something to do with appindicators. Those packages are available and "libappindicator3-1" and "typelib-1_0-AppIndicator3-0_1" are installed

![image](https://github.com/netbirdio/netbird/assets/38642711/212d870f-2b50-4067-a615-e042a903bd6e)

**Comment by lixmal** [comment]
Can you try installing the ayatana packages instead?

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
Still same issue

**Comment by jWXZSCsqrpZRSVwauBjn** [comment]
fixed it by installing https://github.com/ubuntu/gnome-shell-extension-appindicator
