### ISSUE TITLE
label "triage-needed" should be renamed to " cant-help-you"

### ISSUE THREAD

**Issue by PavelNiedoba** [netbirdio/netbird#1854]
I understand that resources are limited, but you should inform us, that help should not be expected

**Comment by HammyHavoc** [comment]
As with any FOSS project, the assumption is you will help yourself, wait for community-based support, or pay for a plan with support, or go with an alternative solution. "Some assembly required".

**Comment by mlsmaycon** [comment]
Hello @PavelNiedoba I understand your frustration when there are no answers to your Github issues. Please understand that as you said we are unable to answer all requests and some will pass unnoticed by us or by the community which tries to support the project and is doing a great job doing so.

We review from time to time the issues, but you can always post again in the same issues you've opened in the past and ask if someone can assist you.
