### ISSUE TITLE
'Add Exit Node' button missing in self-hosted setup

### ISSUE THREAD

**Issue by LickABrick** [netbirdio/netbird#1857]
**Describe the problem**

A clear and concise description of what the problem is.

**To Reproduce**

1. Go to 'the Linux peer in the Peers page'
2. See the 'Add Exit Node' button missing from the page as described in (https://docs.netbird.io/how-to/configuring-default-routes-for-internet-traffic#make-the-peer-an-exit-node-routing-peer)

**Expected behavior**

As described in the documentation linked above a buttons should be visible

**Are you using NetBird Cloud?**

No, selfhosted

**NetBird version**

`0.27.3`

**Comment by lixmal** [comment]
This was added ~1 hour ago: https://github.com/netbirdio/dashboard/commit/2272a1d2a46775ff1b0a8ead6da0fb3838498147

**Comment by LickABrick** [comment]
Oh :) only just started with NetBird and came acros the docs page. I assume this will be in the next release?
