### ISSUE TITLE
DNS Nameservers not working on MacBook Air

### ISSUE THREAD

**Issue by gabricc** [netbirdio/netbird#1860]
**Describe the problem**

Hi there! We have a problem with the **DNS > Nameservers** feature. It works fine for most of our users, but we have two specific peers that don’t work at all. What they have in common is their laptop, both **MacBook Air**, and the operating system is **Darwin 14.4.1**. One of them is running client version **0.26.5** and the other, **0.26.7**.

**To Reproduce**

1. Setup netbird self-hosted server with DNS server;
2. In a MacBook Air, connect to the server;
3. DNS configuration won't be propagated.

**Expected behavior**

DNS resolution should work for all peers.

**Are you using NetBird Cloud?**

Self-hosted NetBird's control plane.

**NetBird version**

Server is running Netbird version: "0.26.2"

**NetBird status -d output:**

**Comment by joshymg** [comment]
This is true for Sonoma 14.4.1 Mac too. But iOS 17.4.1 works fine. 
I am eagerly waiting for this this to work across all devices, before migrating from tailscale!! 
The other show stopper right now is the equivalent of 'Exit node'.

**Comment by joshymg** [comment]
This seems to have been fixed by the latest Mac client v0.27.3

**Comment by lixmal** [comment]
@gabricc Does this still appear with `0.27.3`?

**Comment by gabricc** [comment]
Hi @lixmal ! Sorry for the delayed reply! I confirm that it works on mac air running version `0.27.3`! Thanks!
