### ISSUE TITLE
Split Wiretrustee Client into a service daemon app and a cmd tool

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#187]
**What?**
Right now, the client app is just a single process with a UP command that installs the service and detaches.
The idea is to have a separate daemon process that will run as a systems service or windows service exposing API (e.g. gRPC).
A 2nd part is a cmd tool which will be just a go CLI calling the API of the daemon:
- up
- down
- login

**Why?**
This is a more generic solution allowing to run more operations on the app - e.g getting stats of the peer.
Also allows for separating UI clients from the core
**How?**

**Comment by chmis8000** [comment]
Split increases software complexity and increases user learning costs

**Comment by mlsmaycon** [comment]
Done in https://github.com/netbirdio/netbird/pull/239
