### ISSUE TITLE
after netbird up, can not conntecting to the nodes in same LAN

### ISSUE THREAD

**Issue by hurricane1026** [netbirdio/netbird#1889]
```
╰─λ netbird status                                                                                          0 (5.701s) < 02:11:44
Daemon version: 0.27.1
CLI version: 0.27.3
Management: Disconnected
Signal: Disconnected
Relays: 3/3 Available
Nameservers: 0/0 Available
FQDN:
NetBird IP: N/A
Interface type: N/A
Quantum resistance: false
Routes: -
Peers count: 0/0 Connected
```

Other status is Same As the Issue #1806 

And, I install the netbird with homebrew, the daemon version is 0.27.1 is the root cause, I guess.
I download 0.27.2 manaully, and uninstall homebrew version, then it works well.

**Comment by hurricane1026** [comment]
I wonder why the daemon version is 0.27.1, I guess the version is buggy for routing in same LAN.

**Comment by hurricane1026** [comment]
this is my linux servers
netbird status' output:

```
~> netbird status
Daemon version: 0.27.3
CLI version: 0.27.3
Management: Connected
Signal: Connected
Relays: 3/3 Available
Nameservers: 0/0 Available
FQDN: leopard.stdb.node
NetBird IP: 100.102.178.139/16
Interface type: Kernel
Quantum resistance: false
Routes: -
Peers count: 6/48 Connected
hurricane@leopard ~>
```

**Comment by hurricane1026** [comment]
I guess the bug is a result of incorrect packaging.

**Comment by taylorwilsdon** [comment]
I don't see any bug, you're just not connected - your initial netbird status shows a mismatched daemon and cli version (should have both on the same) but you're not seeing anything because you aren't connected at all and don't have a netbird IP or any peers. Have you confirmed that the /etc/netbird/config.json has the appropriate values for your deployment and that you've even attempted to connect? `netbird up`

```
Management: Disconnected
Signal: Disconnected
Peers count: 0/0 Connected
```

**Comment by hurricane1026** [comment]
> I don't see any bug, you're just not connected - your initial netbird status shows a mismatched daemon and cli version (should have both on the same) but you're not seeing anything because you aren't connected at all and don't have a netbird IP or any peers. Have you confirmed that the /etc/netbird/config.json has the appropriate values for your deployment and that you've even attempted to connect? `netbird up`
> 
> 
> 
> ```
> 
> Management: Disconnected
> 
> Signal: Disconnected
> 
> Peers count: 0/0 Connected
> 
> ```

if I make netbird up, my proxy is broken, then I can not post my issue to github, so I said my status is same as #1806

**Comment by hurricane1026** [comment]
> I don't see any bug, you're just not connected - your initial netbird status shows a mismatched daemon and cli version (should have both on the same) but you're not seeing anything because you aren't connected at all and don't have a netbird IP or any peers. Have you confirmed that the /etc/netbird/config.json has the appropriate values for your deployment and that you've even attempted to connect? `netbird up`
> 
> ```
> Management: Disconnected
> Signal: Disconnected
> Peers count: 0/0 Connected
> ```

Please read my post again carefully, I add some more details.

**Comment by hurricane1026** [comment]
maybe "brew update" didn't kill daemon, and complete the replacement?
