### ISSUE TITLE
Coturn relay HA error: turn is Unavailable, reason: allocate: attribute not found

### ISSUE THREAD

**Issue by debin-ge** [netbirdio/netbird#1898]
**Describe the problem**

I want to get HA relay service. after i checked some information and code, i stripped coturn from the container and deployed it separately. At this point, the connection between turn and stun on peers is Available. everything seems to be working fine.
When I added the `--alternate-server` parameter to the coturn configuration, turn is unavailable.
![image](https://github.com/netbirdio/netbird/assets/21329997/74fe3651-508b-4337-9070-4095702bad76)
I didn't find any error messages in clinet.log

But I tested the turnserver using the turnutils_uclient tool and it shows that everything is fine
![image](https://github.com/netbirdio/netbird/assets/21329997/480b85fe-b951-43d6-8119-cf5389591744)

**To Reproduce**

I modified the management.json file to get the configuration information from the environment variable
![image](https://github.com/netbirdio/netbird/assets/21329997/10de2b9b-1180-4bc5-b8f6-11f7925698ba)

Start the turnserver service in the coturn-master device:
```
turnserver --syslog -a -L 0.0.0.0 -E xxx.xxx.xxx.xxx --allow-loopback-peers --max-bps=3000000 -f -m 3 --min-port=32355 --max-port=65535 --user=admin:admin@1234 -r xxxx.com --log-file=stdout -v --no-dtls --no-tls --alternate-server=SLAVE-1-IP:3478 --alternate-server=SLAVE-2-IP:3478  --cli-password=secret $@
```

Start the service in coturn-slave-1 and coturn-slave-2 in the simplest way possible, which is not described in detail here
Finally I started all the netbird services and they all work fine!

**Are you using NetBird Cloud?**

self-host NetBird

**NetBird version**

`netbird version：0.27.3`

**Comment by debin-ge** [comment]
I have communicated with @braginini  and learned that netbird supports HA relay configurations and I will close this issue.
This configuration:
https://netbirdio.slack.com/archives/C05T5K65X7U/p1714393315451359?thread_ts=1714358203.066829&cid=C05T5K65X7U

**Comment by dkrhodes** [comment]
> I have communicated with @braginini and learned that netbird supports HA relay configurations and I will close this issue. This configuration: https://netbirdio.slack.com/archives/C05T5K65X7U/p1714393315451359?thread_ts=1714358203.066829&cid=C05T5K65X7U

can you please tell what the configuration is? Can't visit the page in slack. Than you

**Comment by netandreus** [comment]
I also can't open this page. @debin-ge @braginini can you please tell me how can we resolve this  issue?

**Comment by Popo8701** [comment]
I'd like to re-open this because I have the exact same error and I don't know how to solve it. My login/password are matching and even if they don't I get the same error.
