### ISSUE TITLE
Unclean Shutdown DNS

### ISSUE THREAD

**Issue by mustafaulukaya** [netbirdio/netbird#1911]
**Describe the problem**

I created a network via Netbird cloud. There are 4 peers and 4 users in the network actively. Everyone except me can communicate with each other correctly. Even though I am connected to the network, when I ping to see the IP address of a host name given by Netbird, I get this message "Ping request could not find host xxx.netbird.cloud. Please check the name and try again."

**To Reproduce**

Unfortunately, I don't know the steps required to repeat the error. I could not cause this error on a different device, but I constantly encounter this error on my own device.

**Expected behavior**

Successfully resolving FQDNs as xxx.netbird.cloud

**Are you using NetBird Cloud?**

Yes, I am using Netbird Cloud

**NetBird version**

v0.27.4

**NetBird status -d output:**

Peers detail:
 laptop-ogul.netbird.cloud:
  NetBird IP: 100.87.38.136/32
  Public key: pL8G23YIba0xxwq008MO5kSju1krCKxPOmyeXGZIqQA=
  Status: Disconnected
  -- detail --
  Connection type: P2P
  Direct: false
  ICE candidate (Local/Remote): host/host
  ICE candidate endpoints (Local/Remote): 192.168.0.103:51820/193.17.4.67:51820
  Last connection update: 34 seconds ago
  Last WireGuard handshake: 32 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 0s

 laptop-guludogan.netbird.cloud:
  NetBird IP: 100.87.122.5/32
  Public key: KkBra8P7Wf6CXl0ctxAy+RZop8Y3drbF0xPj26yhfAc=
  Status: Disconnected
  -- detail --
  Connection type: P2P
  Direct: false
  ICE candidate (Local/Remote): host/host
  ICE candidate endpoints (Local/Remote): 192.168.0.103:51820/193.17.4.67:51820
  Last connection update: 34 seconds ago
  Last WireGuard handshake: 32 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 0s

 laptop-mulukaya.netbird.cloud:
  NetBird IP: 100.87.52.19/32
  Public key: RrPwc5lALgeTPVZtB2k/T+7WlpCCksfpep6+ZHtc7BE=
  Status: Disconnected
  -- detail --
  Connection type: P2P
  Direct: false
  ICE candidate (Local/Remote): host/host
  ICE candidate endpoints (Local/Remote): 192.168.0.103:51820/193.17.4.67:51820
  Last connection update: 34 seconds ago
  Last WireGuard handshake: 32 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 0s

 erolaslan.netbird.cloud:
  NetBird IP: 100.87.15.197/32
  Public key: gXYaMVEGpSBV8nrg90lDEFWbtk7k1kgyxM2Yjdkk82M=
  Status: Disconnected
  -- detail --
  Connection type: P2P
  Direct: false
  ICE candidate (Local/Remote): host/host
  ICE candidate endpoints (Local/Remote): 192.168.0.103:51820/193.17.4.67:51820
  Last connection update: 34 seconds ago
  Last WireGuard handshake: 32 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 0s

 appousedev-app.netbird.cloud:
  NetBird IP: 100.87.56.207
  Public key: wuGzGySMTLWzCU2H3gaFramU2fM/2CCLX+okcaSPwlM=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): srflx/srflx
  ICE candidate endpoints (Local/Remote): 159.146.42.69:44713/193.17.4.68:51820
  Last connection update: 32 seconds ago
  Last WireGuard handshake: 32 seconds ago
  Transfer status (received/sent) 156 B/180 B
  Quantum resistance: false
  Routes: -
  Latency: 8.8119ms

 appouselive-app.netbird.cloud:
  NetBird IP: 100.87.73.95
  Public key: dYC3NlJ5hEkYLCM93VQTukpmmpzhpr9blNudqwKB618=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): host/srflx
  ICE candidate endpoints (Local/Remote): 127.0.0.1:51820/193.17.4.65:51820
  Last connection update: 31 seconds ago
  Last WireGuard handshake: 27 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 10.9757ms

 appouse-devdb.netbird.cloud:
  NetBird IP: 100.87.93.11
  Public key: sVaIAp619EGU/ZbARr43mbjcjrhf547W7OoKVQauEhE=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): host/host
  ICE candidate endpoints (Local/Remote): 192.168.0.103:51820/193.17.4.67:51820
  Last connection update: 32 seconds ago
  Last WireGuard handshake: 32 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 10.9838ms

 appousepostgrelive.netbird.cloud:
  NetBird IP: 100.87.216.92
  Public key: g0+FPDQ1repxz74J6edmeoQ2gHRIpu6mRlDCmGibXWM=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): host/host
  ICE candidate endpoints (Local/Remote): 192.168.0.103:51820/193.17.4.66:51820
  Last connection update: 32 seconds ago
  Last WireGuard handshake: 29 seconds ago
  Transfer status (received/sent) 212 B/304 B
  Quantum resistance: false
  Routes: -
  Latency: 9.5262ms

OS: windows/amd64
Daemon version: 0.27.4
CLI version: 0.27.4
Management: Connected to https://api.netbird.io:443
Signal: Connected to https://signal.netbird.io:443
Relays:
  [stun:stun.netbird.io:5555] is Available
  [turns:turn.netbird.io:443?transport=tcp] is Available
Nameservers:
FQDN: dws-mulukaya.netbird.cloud
NetBird IP: 100.87.238.119/16
Interface type: Userspace
Quantum resistance: false
Routes: -
Peers count: 4/8 Connected

**Screenshots**

![image](https://github.com/netbirdio/netbird/assets/24412394/f74b67f6-41e6-43b0-b79b-b4341815a8c8)

![image](https://github.com/netbirdio/netbird/assets/24412394/1b7be46c-2d28-4d32-9cf3-d4032281bbe2)

**Additional context**

I restarted the computer, deleted and reinstalled the application, but it did not help.

**Comment by mustafaulukaya** [comment]
I solved issue, thanks everybody.

**Comment by pascal456** [comment]
> I solved issue, thanks everybody.

How? I probably have the same problem.
