### ISSUE TITLE
client/server/server.go->Status() returns connected when WiFi Dropouts

### ISSUE THREAD

**Issue by hurricanehrndz** [netbirdio/netbird#1932]
**Describe the problem**

[client/server/server.go->Status() ](https://github.com/netbirdio/netbird/blob/main/client/server/server.go#L597) returns a status connected when WiFi is suddenly disconnected this contradicts the output of `netbird status` that accurately reflects the connection state

This results in the menubar/systray item inaccurately reflecting the connection state, is this oversight or an actual design decission?

**To Reproduce**

On macOS
1. Connect
2. Turn off WiFi
3. Icon indicates I am successfully connected when it is impossible

**Expected behavior**

Icon should accurately reflect the connection state

**Are you using NetBird Cloud?**
Nope

**NetBird version**
0.27.3

**NetBird status -d output:**

NA

**Comment by mlsmaycon** [comment]
@hurricanehrndz, the connected status has the following behavior:

1. connection to the management and signal servers: they are handled by the grpc client and have a 10s timeout; this may cause an invalid status during this timeout
2. P2P connections are not considered in the status response; they are additional to the management/signal status

If the status is not updating after a few seconds, that's an issue.

We are working on a network monitor, https://github.com/netbirdio/netbird/pull/1904, which will respond to network changes, especially the ones that touch the default gateway.

**Comment by hurricanehrndz** [comment]
I will attempt to test with the network monitor and report my findings

**Comment by hurricanehrndz** [comment]
Network monitor will not work in our testing. It does too much and creates more issues than it helps solves. I maybe able to work around it, if I can change https://github.com/netbirdio/netbird/blob/main/client/server/server.go#L615 to optionally run probes.

**Comment by hurricanehrndz** [comment]
Never mind, network monitor does help
