### ISSUE TITLE
[macOS] Failed to login with netbird v0.27.4

### ISSUE THREAD

**Issue by greatbody** [netbirdio/netbird#1949]
**Describe the problem**

Cannot login on macOS through SSO and setup key.

**To Reproduce**

1. Start netbird app on macOS Sonoma 14.4.1
2. Click on 'Connect'
3. Login using Github
<img width="826" alt="image" src="https://github.com/netbirdio/netbird/assets/6984599/7279a094-7c11-42d8-a4cb-26685143f1a7">

**Expected behavior**

Successful login, and can be seen as online on app.netbird.io

**Are you using NetBird Cloud?**

YES

**NetBird version**

`netbird version`

GUI v0.27.4
Daemon v0.27.4

**NetBird status -d output:**

Daemon status: NeedsLogin

**Screenshots**

<img width="826" alt="image" src="https://github.com/netbirdio/netbird/assets/6984599/7279a094-7c11-42d8-a4cb-26685143f1a7">

**Additional context**

Should not be account and network issue, because same account works on Android in the same network.

**Comment by mlsmaycon** [comment]
@greatbody its possible that this peer was added by another user?

**Comment by greatbody** [comment]
> @greatbody its possible that this peer was added by another user?

Not possible.

It was working, and after upgrade netbird on this macBook Pro, I found that we cannot login.

**Comment by greatbody** [comment]
> @greatbody its possible that this peer was added by another user?

I resolved this issue by:

sudo rm /var/log/netbird/client.log
sudo rm /etc/netbird/config.json
