### ISSUE TITLE
Issue with Group Sync from Okta in Netbird

### ISSUE THREAD

**Issue by calibratedcat** [netbirdio/netbird#1951]
**Describe the problem**

We are currently setting up group synchronization with Okta in Netbird and have followed the provided manual for Okta integration. However, the documentation lacks specifics on how to properly configure group synchronization (using JWT?). Additionally, there is uncertainty around the use of the Okta API token set up during the integration—specifically, whether it should automatically pull group information.

Any help on how to set up group syncing will be much appreciated. 

**To Reproduce**

https://docs.netbird.io/selfhosted/identity-providers#okta

**Expected behavior**

Groups sync from Okta

**Are you using NetBird Cloud?**

self-hosted

**Comment by mlsmaycon** [comment]
Hello @calibratedcat you can ask the folks in NetBird's [Slack self-hosted](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A) channel, maybe someone from the community already configured Okta with JWT group sync.

**Comment by calibratedcat** [comment]
Key to solve this problem was adding `groups` to these vars:
`NETBIRD_AUTH_SUPPORTED_SCOPES="openid profile email groups"`
`NETBIRD_AUTH_DEVICE_AUTH_SCOPE="openid email groups"`

**Comment by mlsmaycon** [comment]
Awesome @calibratedcat , did you have to configure anything on the Okta side too?

**Comment by calibratedcat** [comment]
In Okta, you need to configure the OpenID Connect ID Token section. You need to define `Group Claim Filter`. In my case, I chose any group by using `.*` expression. `groups` is a claim name that will be used in your token. Should match in env listed above. 
<img width="755" alt="image" src="https://github.com/netbirdio/netbird/assets/50356247/05b603b4-3765-49d9-acf2-db521ae91669">
