### ISSUE TITLE
Dashboard - Setup Key status filter

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#196]
**What?**
Introduce a status filter for the Setup key.
Default - valid keys.

**Why?**
Keys tend to expire and the list might just grow.
It is also unnecessary to see all of the keys.

**How?**

- Add a selector field on top of the table with a drop-down showing all possible statuses.
- update React state when field changes.
- we should not modify server for now, implementing this on a client side should be fine.

**Comment by mlsmaycon** [comment]
this was done
