### ISSUE TITLE
Whats wrong with the netbird.io website

### ISSUE THREAD

**Issue by mrpastewart** [netbirdio/netbird#1963]
Project Website appears dead when i try to connect is the site permanently down or?

**Comment by greatbody** [comment]
https://netbird.io/ the website is active available.

<img width="1401" alt="image" src="https://github.com/netbirdio/netbird/assets/6984599/8db26a8b-09d6-4006-8986-a02ebd85b3ed">

**Comment by mrpastewart** [comment]
Interesting I can't access it from my location/connection been trying for a week

![Screenshot from 2024-05-10 20-32-17](https://github.com/netbirdio/netbird/assets/1747808/3361b4e3-9245-45f2-97a0-e9c2f4bf43d8)

**Comment by greatbody** [comment]
> Interesting I can't access it from my location/connection been trying for a week
> 
> ![Screenshot from 2024-05-10 20-32-17](https://private-user-images.githubusercontent.com/1747808/329750657-3361b4e3-9245-45f2-97a0-e9c2f4bf43d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDc3NjYsIm5iZiI6MTcxNTQwNzQ2NiwicGF0aCI6Ii8xNzQ3ODA4LzMyOTc1MDY1Ny0zMzYxYjRlMy05MjQ1LTQ1ZjItOTdhMC1lOWMyZjRiZjQzZDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTFUMDYwNDI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM3NGMxN2ZlNjViNDQ2ZTk5ZjJlYWFkMTU5M2VmNWZjZGE3NTExNWYwZTlkODNmMjE3Nzk4MTNmNTMzYzZlYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.4TAFnMenxfrosMV6qGoQbR3m2JWpWMUdh_lKapp4W6w)
> 
> I'm not behind a firewall or proxy so I am at a loss for why I can't browse the site on my laptop I can reach it on my phone

If your phone and laptop are connected to the same network and your laptop cannot access the website, it must be an laptop issue.

**Comment by mlsmaycon** [comment]
@mrpastewart can you try generating a HAR file? it might that some image of file is too large on your desktop and is taking time to load. 

To generate a HAR file you can follow the steps from; https://help.okta.com/oag/en-us/content/topics/access-gateway/troubleshooting-with-har.htm

**Comment by euh2** [comment]
I can't access netbird.io when connected to a VPN, primarily from M247 networks .  I guess some firewall is dropping the traffic.

**Comment by mrpastewart** [comment]
Here is my HAR file for chrome it does this in firefox and MS Edge as well and my phone and my laptop are both on the AT&T network. Laptop is connected via wifi router and the phone is on the network.

{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "WebInspector",
      "version": "537.36"
    },
    "pages": [],
    "entries": [
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "request": {
          "method": "GET",
          "url": "https://netbird.io/",
          "httpVersion": "",
          "headers": [
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            },
            {
              "name": "sec-ch-ua",
              "value": "\"Chromium\";v=\"124\", \"Google Chrome\";v=\"124\", \"Not-A.Brand\";v=\"99\""
            },
            {
              "name": "sec-ch-ua-mobile",
              "value": "?0"
            },
            {
              "name": "sec-ch-ua-platform",
              "value": "\"Linux\""
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 0,
          "statusText": "",
          "httpVersion": "",
          "headers": [],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": "net::ERR_ABORTED"
        },
        "serverIPAddress": "",
        "startedDateTime": "2024-05-11T13:33:56.352Z",
        "time": 3001.8210000000636,
        "timings": {
          "blocked": 3001.8210000000636,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 0,
          "receive": 0,
          "_blocked_queueing": -1
        }
      },
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "request": {
          "method": "GET",
          "url": "http://netbird.io/",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Accept",
              "value": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.9"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Host",
              "value": "netbird.io"
            },
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": 413,
          "bodySize": 0
        },
        "response": {
          "status": 408,
          "statusText": "Request Time-out",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown",
            "compression": 52
          },
          "redirectURL": "",
          "headersSize": 52,
          "bodySize": -52,
          "_transferSize": 0,
          "_error": null
        },
        "serverIPAddress": "",
        "startedDateTime": "2024-05-11T13:33:59.384Z",
        "time": 3023.8540000000285,
        "timings": {
          "blocked": 3023.8540000000285,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": -3007.4999999999363,
          "receive": 0,
          "_blocked_queueing": 3023.8540000000285
        }
      },
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "request": {
          "method": "GET",
          "url": "https://netbird.io/",
          "httpVersion": "http/1.1",
          "headers": [
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 307,
          "statusText": "Temporary Redirect",
          "httpVersion": "http/1.1",
          "headers": [
            {
              "name": "Location",
              "value": "http://netbird.io/"
            },
            {
              "name": "Non-Authoritative-Reason",
              "value": "HttpsUpgrades"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "x-unknown"
          },
          "redirectURL": "http://netbird.io/",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 0,
          "_error": null
        },
        "serverIPAddress": "",
        "startedDateTime": "2024-05-11T13:33:59.400Z",
        "time": 3001.9210000000385,
        "timings": {
          "blocked": -1,
          "dns": -1,
          "ssl": -1,
          "connect": -1,
          "send": 0,
          "wait": 3001.9210000000385,
          "receive": 0,
          "_blocked_queueing": -1
        }
      },
      {
        "_initiator": {
          "type": "other"
        },
        "_priority": "VeryHigh",
        "_resourceType": "document",
        "cache": {},
        "connection": "901",
        "request": {
          "method": "GET",
          "url": "http://netbird.io/",
          "httpVersion": "http/1.1",
          "headers": [
            {
              "name": "Upgrade-Insecure-Requests",
              "value": "1"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
            }
          ],
          "queryString": [],
          "cookies": [],
          "headersSize": -1,
          "bodySize": 0
        },
        "response": {
          "status": 408,
          "statusText": "Request Time-out",
          "httpVersion": "http/1.1",
          "headers": [
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [],
          "content": {
            "size": 0,
            "mimeType": "text/plain"
          },
          "redirectURL": "",
          "headersSize": -1,
          "bodySize": -1,
          "_transferSize": 52,
          "_error": "net::ERR_HTTP_RESPONSE_CODE_FAILURE"
        },
        "serverIPAddress": "[2a05:d014:1f8d:7302:ebca:ec15:b24d:d07e]",
        "startedDateTime": "2024-05-11T13:34:02.402Z",
        "time": 75404.58400000003,
        "timings": {
          "blocked": 6.87499999989786,
          "dns": 8.16,
          "ssl": -1,
          "connect": 64.40299999999999,
          "send": 0.49500000000000455,
          "wait": 75303.62100000001,
          "receive": 21.03000000011525,
          "_blocked_queueing": 5.57899999989786
        }
      }
    ]
  }
}

**Comment by euh2** [comment]
@mrpastewart It looks like you try netbird.io with IPv6. That endpoint, `[2a05:d014:1f8d:7302:ebca:ec15:b24d:d07e]`, isn't responding for me as well. You could try to force to reach netbird.io through IPv4. Eg. by adding the following line to your `/etc/hosts` file:
```bash
18.158.22.172 netbird.io
```

**Comment by mrpastewart** [comment]
@euh2 That did it for me thanks I can access site now

**Comment by euh2** [comment]
@mrpastewart That's good! Just so you know, this should only be a temporary solution. You should check out your network setup. Especially DNS. You are likely having a configuration where your DNS serves you with IPv6 addresses, although your network may not always work with IPv6 connections.
And netbird.io IP address might change in the future, so then our `/etc/hosts` hack won't work anymore.

To debug issues like this you could use the `curl` application on Linux, like:
```bash
curl --verbose https://netbird.io/
```
This would give you some more detailed information on what's going on behind the scenes.

**Comment by mlsmaycon** [comment]
Thank you guys, we will review this configuration and make sure ipv6 works as expected.

**Comment by mrpastewart** [comment]
I'm going to mark this as closed. If the netbird team has anything further they can reopen this.
