### ISSUE TITLE
Netbird is causing my laptop to kernel panic

### ISSUE THREAD

**Issue by ItIsGhastly** [netbirdio/netbird#1980]
**Describe the problem**

Netbird is causing my Intel 2020 macbook air to kernel panic after a few minutes of being connected. I will attach the log that comes up after the laptop restarts. When i try to reconnect after the laptop restarts i get the error Dial service: context deadline exceeded.

**To Reproduce**

1. Open netbird
2. Connect with an active exit node (i also had 2 other routes active)
3. After some time your laptop should restart 

**Expected behavior**

My laptop connects, and i can use the application fine to access my home network.

**Are you using NetBird Cloud?**

Self hosted quick start version.

**NetBird version**

`netbird version gui 0.27.6`

**NetBird status -d output:**

`Error: failed to connect to daemon error: context deadline exceeded
If the daemon is not running please run: 
netbird service install 
netbird service start

ghastly@MacBook ~ % netbird service start
"launchctl" failed with stderr: Warning: Expecting a LaunchAgents path since the command was ran as user. Got LaunchDaemons instead.
`launchctl bootstrap` is a recommended alternative.

Error: "launchctl" failed with stderr: Warning: Expecting a LaunchAgents path since the command was ran as user. Got LaunchDaemons instead.
`launchctl bootstrap` is a recommended alternative.`

**Screenshots**

**Additional context**
[panic(cpu 2 caller 0xffffff801e8ab89b): userspace watchdog timeout….pdf](https://github.com/netbirdio/netbird/files/15306472/panic.cpu.2.caller.0xffffff801e8ab89b.userspace.watchdog.timeout.pdf)

**Comment by xcstatus** [comment]
I had this problem too.
The gui shows that the configuration file path is empty


![image](https://github.com/netbirdio/netbird/assets/40375067/9684f9bd-9aa9-4606-b5a3-8a94ee6ff8a6)

**Comment by mlsmaycon** [comment]
@xcstatus, this seems duplicated from #1896, can you confirm if the issue happens only when there is a exit node route configured? 

Can you share the logs from the daemon service too? https://docs.netbird.io/how-to/troubleshooting-client#getting-client-logs

**Comment by xcstatus** [comment]
[client.log](https://github.com/netbirdio/netbird/files/15315525/client.log)
It was used, but has now been removed.

**Comment by ItIsGhastly** [comment]
I am relatively certain, either way its not great when im in class and my laptops restarting randomly lol.  

[client.log](https://github.com/netbirdio/netbird/files/15319417/client.log)
Here you go.

**Comment by asvataa** [comment]
@mlsmaycon 
By the way yes, we had the same error with saving the configuration, as soon as you remove the “Exit node” and reinstall the application, the error goes away

**Comment by mlsmaycon** [comment]
Hey folks, the PR #2025 seems to fix the issue. If anyone wants to try this build, you can use the binary from: https://github.com/netbirdio/netbird/actions/runs/9187529519/artifacts/1526014624

**Comment by mlsmaycon** [comment]
Hello Folks, the v0.27.9 has the fix for the crash. Thanks for your help testing the builds.

**Comment by ItIsGhastly** [comment]
context deadline exceeded is still popping up
