### ISSUE TITLE
Hiding register button from UI

### ISSUE THREAD

**Issue by MxD-js** [netbirdio/netbird#1988]
**Is your feature request related to a problem? Please describe.**
Is there a way to hide the register button from the UI?

**Describe the solution you'd like**
hide/disable register button from front end ui 
and additionally hide the footer, the less information I am revealing the better we are in staying secure

![image](https://github.com/netbirdio/netbird/assets/60336163/5cf2737d-3f51-4a69-99d9-61e2a95c1faa)

**Comment by lixmal** [comment]
Please address your request to zitadel: https://github.com/zitadel/zitadel

**Comment by MxD-js** [comment]
thanks, will do.

**Comment by EDIflyer** [comment]
> thanks, will do.
> 
> Update: For anyone looking on how to do it. access the zitadel interface at [https://netbird.[yourdomain.com]/ui/console](https://netbird.%5Byourdomain.com%5D/ui/console) and in the instance settings there is a disable registration and a bunch more customization. Refer to https://zitadel.com/docs/guides/solution-scenarios/configurations

Really helpful, thanks - just to flag that the `netbird` bit at the start may vary too depending on the subdomain you've picked for your setup :)
