### ISSUE TITLE
error: failed while getting Management Service public key

### ISSUE THREAD

**Issue by LuizFelipeAlvesMaia** [netbirdio/netbird#2043]
**Describe the problem**

The error message you are encountering, "rpc error: code = Unknown desc = getting device authorization flow info failed with error: failed while getting Management Service public key," indicates that the Netbird agent is unable to retrieve the public key from the Management Service. This public key is essential for establishing a secure communication channel between the agent and the management service. The failure could be due to several reasons, such as network connectivity issues, misconfiguration of the management service, or problems with the service's key management or distribution.

To Reproduce

Follow all the steps in the Self-Hosted guide, using Google Workspace IDP.
Attempt to connect a Windows agent to https://netbird.mydomain.com:443.

Expected behavior:

The agent should successfully connect to the Netbird self-hosted instance, retrieving the Management Service public key and completing the authorization process without errors.

Are you using NetBird Cloud?

No, I am self-hosting NetBird's control plane.

NetBird version: 0.27.9

![image](https://github.com/netbirdio/netbird/assets/71887325/034c4047-e7fe-45ce-af53-1ef5e8e044b1)

**Comment by LuizFelipeAlvesMaia** [comment]
UPDATE: Now I have an error when trying to connect my Netbird agent. My management container has the following log:
`management-1 | 2024-05-24T21:17:55Z WARN management/server/grpcserver.go:371: failed logging in peer`

**Comment by Amplificator** [comment]
I have the same error as you initially did - how did you fix it?

**Comment by LuizFelipeAlvesMaia** [comment]
> I have the same error as you initially did - how did you fix it?

I'm still encountering the same error. I had to take a break from trying to fix it, but now I'm attempting to resolve it again. My peers still can't connect to the server.

**Comment by biggreywave** [comment]
sane error here

**Comment by maslyankov** [comment]
Anyone who solved this?

**Comment by BrianGrug** [comment]
I'm having the same issue as well

**Comment by juniormarangao** [comment]
Hi!

I am facing this issue, I can't connect any client.
I've installed using Advanced guide, with Authentik and Nginx Proxy Manager.
I can login, shows peers page, I can create management Keys, but I cannot connect.

When I debbug with `sudo netbird up -F -l debug -m https://myvpn.example.com:443` shows this below

```
2024-09-16T12:33:03-03:00 ERRO client/internal/login.go:105: failed while getting Management Service public key: failed while getting Management Service public key
2024-09-16T12:33:03-03:00 WARN client/cmd/root.go:234: retrying Login to the Management service in 1.259689188s due to error failed while getting Management Service public key
2024-09-16T12:33:05-03:00 DEBG client/internal/login.go:93: connecting to the Management service https://myvpn.example.com:443
2024-09-16T12:33:05-03:00 DEBG client/internal/login.go:63: connected to the Management service https://myvpn.example.com:443
2024-09-16T12:33:05-03:00 ERRO management/client/grpc.go:287: failed while getting Management Service public key: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/html"
```

The setup is 3 VMs:

1. Nginx Proxy Manager
2. Authentik
3. Netbird

All behind one Public IP, but same internal network, all reachable between each.
In NPM with host pointing to netbird vm, is the ports `80`, `443`, and `33073` in configuration, with gRPC, etc...

The other ports required, is forwarding directly to the netbird VM.

There are something that I missed?

**Comment by Christophe-Foyer** [comment]
Any updates on this issue? I'm also having the same problem. Here's the exact error I'm seeing when setting up the peer:
```
2024-09-24T10:20:41Z ERRO client/internal/login.go:105: failed while getting Management Service public key: failed while getting Management Service public key
2024-09-24T10:20:41Z WARN client/cmd/root.go:244: retrying Login to the Management service in 5.18639944s due to error failed while getting Management Service public key
2024-09-24T10:20:47Z ERRO management/client/grpc.go:278: failed while getting Management Service public key: rpc error: code = PermissionDenied desc = unexpected HTTP status code received from server: 403 (Forbidden); transport: received unexpected content-type "text/plain; charset=UTF-8"
2024-09-24T10:20:47Z ERRO client/internal/login.go:105: failed while getting Management Service public key: failed while getting Management Service public key

Error: foreground login failed: backoff cycle failed: failed while getting Management Service public key
```

Regarding my setup, I can access the ui at `https://subdomain.domain.example/`, keycloak is at `https://othersubdomain.domain.example/` with the admin url set to a local `http://192.168.X.X:port/` reflecting the VM ip and keycloak port. Logging in seems to work fine.

I also only have ports 80 and 443 forwarded to NPM which then forwards it to the VM that hosts netbird (where SSL is off etc).

My Nginx Proxy Manager is setup as described in [this reddit comment](https://www.reddit.com/r/nginxproxymanager/comments/1arxp04/netbird_config/kyhanum/). Custom locations:


 - /api
Scheme: http Forward Hostname / IP : netbird-management-1 Forward Port: 443

- /management.ManagementService/
Advanced:

    grpc_pass grpc://192.168.X.X:33073;  # matches exposed management port in docker compose
    #grpc_ssl_verify off;
    grpc_read_timeout 1d;
    grpc_send_timeout 1d;
    grpc_socket_keepalive on;

- /signalexchange.SignalExchange/
Advanced:

    grpc_pass grpc://192.168.X.X:10000;  # matches exposed signal port in docker compose
    #grpc_ssl_verify off;
    grpc_read_timeout 1d;
    grpc_send_timeout 1d;
    grpc_socket_keepalive on;

**Comment by juniormarangao** [comment]
I had a little progress I think.
Instead `/api` set to IP:443, I changed to IP:33073

With this I could partially add peers.
On the client side (linux) I used the command `netbird up -m https://domain.name` and generated the URL for authenticate, I can authenticate, but the page goes blank, e in terminal stays forever without end to establish the connection... 
Checking management logs, shows `Peer need to login`
When I cancel the command in client side and type `netbird status` it shows connected, but Signal disconnected.
In Dashboard page the peer shows there, but offline.

Now I am trying hard to figure out how to fix that too, and until now nothing.

**Comment by 185504a9** [comment]
This is pretty specific so I dunno if this can help you guys but I "solved" this problem after remembering that I'm using Cloudflare as DNS so I had to disable the proxying of requests to my netbird's subdomain

**Comment by Christophe-Foyer** [comment]
Not sure if this gives any more info but I can't even get it to a point where it complains that the peer needs to log in.
I had a typo above and it was already redirecting the API calls to 

This is a slightly more verbose version of the error above when running `GRPC_GO_LOG_VERBOSITY_LEVEL=99 GRPC_GO_LOG_SEVERITY_LEVEL=info netbird up -F -l debug`:

```
2024-09-24T16:49:44Z DEBG client/internal/login.go:93: connecting to the Management service https://domain.subdomain.example:443
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel created
2024/09/24 16:49:44 INFO: [core] [Channel #16]original dial target is: "domain.subdomain.example:443"
2024/09/24 16:49:44 INFO: [core] [Channel #16]parsed dial target is: resolver.Target{URL:url.URL{Scheme:"domain.subdomain.example", Opaque:"443", User:(*url.Userinfo)(nil), Host:"", Path:"", RawPath:"", OmitHost:false, ForceQuery:false, RawQuery:"", Fragment:"", RawFragment:""}}
2024/09/24 16:49:44 INFO: [core] [Channel #16]fallback to scheme "passthrough"
2024/09/24 16:49:44 INFO: [core] [Channel #16]parsed dial target is: passthrough:///domain.subdomain.example:443
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel authority set to "domain.subdomain.example:443"
2024/09/24 16:49:44 INFO: [core] [Channel #16]Resolver state updated: {
  "Addresses": [
    {
      "Addr": "domain.subdomain.example:443",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "Endpoints": [
    {
      "Addresses": [
        {
          "Addr": "domain.subdomain.example:443",
          "ServerName": "",
          "Attributes": null,
          "BalancerAttributes": null,
          "Metadata": null
        }
      ],
      "Attributes": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
} (resolver returned new addresses)
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel switches to new LB policy "pick_first"
2024/09/24 16:49:44 INFO: [core] [pick-first-lb 0xc0008ae8a0] Received new config {
  "shuffleAddressList": false
}, resolver state {
  "Addresses": [
    {
      "Addr": "domain.subdomain.example:443",
      "ServerName": "",
      "Attributes": null,
      "BalancerAttributes": null,
      "Metadata": null
    }
  ],
  "Endpoints": [
    {
      "Addresses": [
        {
          "Addr": "domain.subdomain.example:443",
          "ServerName": "",
          "Attributes": null,
          "BalancerAttributes": null,
          "Metadata": null
        }
      ],
      "Attributes": null
    }
  ],
  "ServiceConfig": null,
  "Attributes": null
}
2024/09/24 16:49:44 INFO: [core] [Channel #16 SubChannel #17]Subchannel created
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel Connectivity change to CONNECTING
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel exiting idle mode
2024/09/24 16:49:44 INFO: [core] [Channel #16 SubChannel #17]Subchannel Connectivity change to CONNECTING
2024/09/24 16:49:44 INFO: [core] [Channel #16 SubChannel #17]Subchannel picks a new address "domain.subdomain.example:443" to connect
2024-09-24T16:49:44Z DEBG util/net/dialer_nonios.go:52: Dialing tcp domain.subdomain.example:443
2024/09/24 16:49:44 INFO: [core] [pick-first-lb 0xc0008ae8a0] Received SubConn state update: 0xc0008ae900, {ConnectivityState:CONNECTING ConnectionError:<nil>}
2024/09/24 16:49:44 INFO: [core] [Channel #16 SubChannel #17]Subchannel Connectivity change to READY
2024/09/24 16:49:44 INFO: [core] [pick-first-lb 0xc0008ae8a0] Received SubConn state update: 0xc0008ae900, {ConnectivityState:READY ConnectionError:<nil>}
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel Connectivity change to READY
2024-09-24T16:49:44Z DEBG client/internal/login.go:63: connected to the Management service https://domain.subdomain.example:443
2024-09-24T16:49:44Z ERRO management/client/grpc.go:278: failed while getting Management Service public key: rpc error: code = PermissionDenied desc = unexpected HTTP status code received from server: 403 (Forbidden); transport: received unexpected content-type "text/plain; charset=UTF-8"
2024-09-24T16:49:44Z ERRO client/internal/login.go:105: failed while getting Management Service public key: failed while getting Management Service public key
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel Connectivity change to SHUTDOWN
2024/09/24 16:49:44 INFO: [core] [Channel #16]Closing the name resolver
2024/09/24 16:49:44 INFO: [core] [Channel #16]ccBalancerWrapper: closing
2024/09/24 16:49:44 INFO: [core] [Channel #16 SubChannel #17]Subchannel Connectivity change to SHUTDOWN
2024/09/24 16:49:44 INFO: [core] [Channel #16 SubChannel #17]Subchannel deleted
2024/09/24 16:49:44 INFO: [transport] [client-transport 0xc0007fd688] Closing: rpc error: code = Canceled desc = grpc: the client connection is closing
2024/09/24 16:49:44 INFO: [transport] [client-transport 0xc0007fd688] loopyWriter exiting with error: rpc error: code = Canceled desc = grpc: the client connection is closing
2024/09/24 16:49:44 INFO: [core] [Channel #16]Channel deleted
2024-09-24T16:49:44Z WARN client/cmd/root.go:244: retrying Login to the Management service in 10.261420214s due to error failed while getting Management Service public key
```

**Comment by Christophe-Foyer** [comment]
Figured out my issue. Just had to move the grpc directives to the advanced tab in nginx proxy manager.

Not sure it's the same as the rest of you though but going to post my config just in case.

```
underscores_in_headers on; 

location /management.ManagementService/ {
  grpc_pass grpc://192.168.X.X:33073;
  #grpc_ssl_verify off;
  grpc_read_timeout 1d;
  grpc_send_timeout 1d;
  grpc_socket_keepalive on;
  grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /signalexchange.SignalExchange/ {
  grpc_pass grpc://192.168.X.X:10000;
  #grpc_ssl_verify off;
  grpc_read_timeout 1d;
  grpc_send_timeout 1d;
  grpc_socket_keepalive on;
  grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
}
```

**Comment by BrianGrug** [comment]
> Figured out my issue. Just had to move the grpc directives to the advanced tab in nginx proxy manager.
> 
> Not sure it's the same as the rest of you though but going to post my config just in case.
> 
> ```
> underscores_in_headers on; 
> 
> location /management.ManagementService/ {
>   grpc_pass grpc://192.168.X.X:33073;
>   #grpc_ssl_verify off;
>   grpc_read_timeout 1d;
>   grpc_send_timeout 1d;
>   grpc_socket_keepalive on;
>   grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
> }
> 
> location /signalexchange.SignalExchange/ {
>   grpc_pass grpc://192.168.X.X:10000;
>   #grpc_ssl_verify off;
>   grpc_read_timeout 1d;
>   grpc_send_timeout 1d;
>   grpc_socket_keepalive on;
>   grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
> }
> ```
> 
> Edit: though now I'm having issues with peers not seeing relay servers so... fun new isues to solve!

I ended up getting a cheap VPS and hosting it on there. No issues after that. Even tried using the same reverse proxy instance, that it worked. Have no idea what was causing the issue, guessing a firewall misconfiguration, or maybe a port missing from documentation?

**Comment by juniormarangao** [comment]
> > Figured out my issue. Just had to move the grpc directives to the advanced tab in nginx proxy manager.
> > 
> > Not sure it's the same as the rest of you though but going to post my config just in case.
> > 
> > ```
> > underscores_in_headers on; 
> > 
> > location /management.ManagementService/ {
> >   grpc_pass grpc://192.168.X.X:33073;
> >   #grpc_ssl_verify off;
> >   grpc_read_timeout 1d;
> >   grpc_send_timeout 1d;
> >   grpc_socket_keepalive on;
> >   grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
> > }
> > 
> > location /signalexchange.SignalExchange/ {
> >   grpc_pass grpc://192.168.X.X:10000;
> >   #grpc_ssl_verify off;
> >   grpc_read_timeout 1d;
> >   grpc_send_timeout 1d;
> >   grpc_socket_keepalive on;
> >   grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
> > }
> > ```
> > 
> > Edit: though now I'm having issues with peers not seeing relay servers so... fun new isues to solve!
> 
> I ended up getting a cheap VPS and hosting it on there. No issues after that. Even tried using the same reverse proxy instance, that it worked. Have no idea what was causing the issue, guessing a firewall misconfiguration, or maybe a port missing from documentation?


I have it installed in other location, in a residential place with a common residential internet with dynamic public IP, but with quick install, all Default, and it is working great.
But this way I lost my port 80 and 443 to work only netbird.
I am almost to take a cheap VPS too, and use quick install... This is really annoying me... The documentation is missing a lot of things.

**Comment by collse** [comment]
damn this was a tricky one  but I finally got it to work.

**My setup is as follows:**
<img width="1285" alt="image" src="https://github.com/user-attachments/assets/1406b83b-4fe7-4c1a-bd3d-6ed159d189c4">

**my docker compose differs as below:**
```
dashboard:
    ports:
      - ip.address.of.docker.host:80:80
      - ip.address.of.docker.host:443:443
    environment:
      # Endpoints
      - NETBIRD_MGMT_API_ENDPOINT=https://your.dom.com:443
      - NETBIRD_MGMT_GRPC_API_ENDPOINT=https://your.dom.com:443
```
   
```
signal:
   ports:
      - ip.address.of.docker.host:10000:10000
```

```
relay:
    ports:
      - ip.address.of.docker.host:33080:33080
```

```
management:
    ports:
      -  ip.address.of.docker.host:33073:443 #API port
    command: [
      "--port", "443",
      "--log-file", "console",
      "--log-level", "info",
      "--disable-anonymous-metrics=false",
```

**my nginx proxy manager configuration:**

main domain eg:  
nb.your.dom.com

scheme: http          forward: ip.address.of.docker.host   forward_port:80

advanced:
```
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Scheme $scheme;
proxy_set_header        X-Forwarded-Proto https;
proxy_set_header        X-Forwarded-Host $host;
grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
underscores_in_headers on;
```

**custom locations:**
/api


scheme: http          forward: ip.address.of.docker.host   forward_port:33073
advanced
```
proxy_set_header        X-Real-IP $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header        X-Scheme $scheme;
proxy_set_header        X-Forwarded-Proto https;
proxy_set_header        X-Forwarded-Host $host;
grpc_set_header         X-Forwarded-For $proxy_add_x_forwarded_for;
```


/management.ManagementService/


scheme: http          forward: ip.address.of.docker.host   forward_port:33073

advanced:
```
    if ($http_content_type = "application/grpc") { 
        grpc_pass grpc://ip.address.of.docker.host:33073; 
    } 
grpc_read_timeout 300s;
grpc_send_timeout 300s;
grpc_socket_keepalive on;
grpc_set_header         X-Forwarded-For     $proxy_add_x_forwarded_for; #helps getting the correct IP through npm to the server
```


/signalexchange.SignalExchange/


scheme: http          forward: ip.address.of.docker.host   forward_port:10000

advanced:
```
    if ($http_content_type = "application/grpc") { 
        grpc_pass grpc://ip.address.of.docker.host:10000; 
    } 
grpc_read_timeout 300s;
grpc_send_timeout 300s;
grpc_socket_keepalive on;
grpc_set_header         X-Forwarded-For     $proxy_add_x_forwarded_for; #helps getting the correct IP through npm to the server
```

/relay/


scheme: http          forward: ip.address.of.docker.host   forward_port:33080

NPM version: v2.11.3 © 2024 [jc21.com](https://jc21.com/?utm_source=nginx-proxy-manager).

**Comment by juniormarangao** [comment]
Maybe it not be considering close yet.
I've checked my configuration, most was like yours @collse, so I did the changes following your guide, and I am still facing issues... 

Well, let's say I got some progress even before this adjustments... 
My case now is: I am able to access dashboard page, I can navigate to other pages, like Setup Keys and create keys, Access Control,, Network Routes, etc.
But when I try to add some peer, in the client the things stay forever without finish the command (netbird up -m https://domain)
It generates a url, that ask me to login, after the login the page is blank and nothing happens, when I use a Key (netbird up -m https://domain -k <key-value>) its just stays forever without finish the command, the peer shows in dashboard but as offline, in management logs keeps showing "Peer needs login".

Honestly, I don't know nothing more I can do, I already have started it again from scratch a couple of times, and always I got stuck in this situation

**Comment by collse** [comment]
seems like your signalling is trying to reach port: 10000 instead of using 443 and then being handled ...

try the following: `netbird up -m https://domain:443 -k key-value `

**Comment by juniormarangao** [comment]
Same thing!

Could it be some misconfiguration on signal in Nginx Proxy Manager?
I did the configuration like in your previous post


/signalexchange.SignalExchange/

scheme: http forward: ip.address.of.docker.host forward_port:10000

advanced:
```
    if ($http_content_type = "application/grpc") { 
        grpc_pass grpc://ip.address.of.docker.host:10000; 
    } 
grpc_read_timeout 300s;
grpc_send_timeout 300s;
grpc_socket_keepalive on;
grpc_set_header         X-Forwarded-For     $proxy_add_x_forwarded_for; #helps getting the correct IP through npm to the server
```

**Comment by collse** [comment]
based on your previous message it is attempting to make the call to port 10000 instead of 443 not sure what prompts it to do that, check your configuration again, against mine - I know it works as it has been working like that since - unfortunately no other advice that I can give apart from also checking your npm logs but the attempt to :10000 is explicit enough what happens there

**Comment by mhartmann-jaconi** [comment]
Even though this issue is closed, I wanted to share my findings regarding this issue. I ran netbird in a GKE cluster with a managed nginx ingress in front. When capturing traffic, I noticed that the requests, which should be grpc calls, were sent as HTTP/1.1 requests.
So adding an annotation `nginx.ingress.kubernetes.io/backend-protocol: GRPC` to the ingress resource solved the issue for me, as now the requests reach the server as real grpc calls.

**Comment by liuyishengaaa** [comment]
> Hi!
> 
> I am facing this issue, I can't connect any client. I've installed using Advanced guide, with Authentik and Nginx Proxy Manager. I can login, shows peers page, I can create management Keys, but I cannot connect.
> 
> When I debbug with `sudo netbird up -F -l debug -m https://myvpn.example.com:443` shows this below
> 
> ```
> 2024-09-16T12:33:03-03:00 ERRO client/internal/login.go:105: failed while getting Management Service public key: failed while getting Management Service public key
> 2024-09-16T12:33:03-03:00 WARN client/cmd/root.go:234: retrying Login to the Management service in 1.259689188s due to error failed while getting Management Service public key
> 2024-09-16T12:33:05-03:00 DEBG client/internal/login.go:93: connecting to the Management service https://myvpn.example.com:443
> 2024-09-16T12:33:05-03:00 DEBG client/internal/login.go:63: connected to the Management service https://myvpn.example.com:443
> 2024-09-16T12:33:05-03:00 ERRO management/client/grpc.go:287: failed while getting Management Service public key: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/html"
> ```
> 
> The setup is 3 VMs:
> 
> 1. Nginx Proxy Manager
> 2. Authentik
> 3. Netbird
> 
> All behind one Public IP, but same internal network, all reachable between each. In NPM with host pointing to netbird vm, is the ports `80`, `443`, and `33073` in configuration, with gRPC, etc...
> 
> The other ports required, is forwarding directly to the netbird VM.
> 
> There are something that I missed?

My issue was about joining a Netbird private network using a Debian 11 server without a graphical interface. When I ran the command "netbird up --management-url https://xxxxxx.net  --admin-url https://xxxxxx.net  --setup-key xxxxx-xxx-xxxx", I got an error saying "error: failed while getting Management Service public key". Fortunately, by referring to your question and using the command "sudo netbird up -F -l debug -m https://myvpn.example.com:443", I found a solution. This command will print a login link at the end, which can be copied and executed in another browser for authorization and login.

**Comment by Ahmed-Hodhod** [comment]
For me, I got this error after I turned on the proxy mode in cloudflare. Before that it was running smoothly. So pretty much it is about the ports.

**Comment by JoaGamo** [comment]
finally I solved it.
I don't know exactly what solved it, sharing my findings:

I added the websockets locations in my nginx proxy manager custom locations like this
format is `scheme (HTTP / HTTPS), IP, PORT`

### /ws-proxy/signal
http ip-host-docker 10000
### /ws-proxy/management
http ip-host-docker 33073

The other settings are almost the same as @collse setup https://github.com/netbirdio/netbird/issues/2043#issuecomment-2384470230 , except that my Signal container has the ports like `10000:80` instead of `10000:10000` .
After using Collse's configuration, I fixed the original problem of this issue ("Management service public key"), but I was facing a context deadline exceeded, then a context  canceled problem.

The thing that automatically enabled connection was editing the management.json

In these lines

```json
    },
    "Signal": {
        "Proto": "http",
        "URI": "vpn.test.com:443",
        "Username": "",
        "Password": ""
    },
```
if you are seeing "Proto": "http", change it to "https", then reload the configuration by `docker compose down && docker compose up -d`.

This fixed the `context canceled` issue, allowing connection instantly.

**Comment by Lxmune** [comment]
Managed to resolve the issue by enabling gRPC on CF (through NGINX reverse proxy)
