### ISSUE TITLE
[Video] How to make Nextcloud hosted at home available from anywhere

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#21]

**Comment by ashutoshpw** [comment]
@braginini I can make a video on this in one of the following two ways
1. Using Docker and Docker-compose (For Nextcloud Instant Setup)
2. Using normal installation on a debian based system. 

Which approach would you like me to follow while creating a video for this? ( I will suggest the docker way)

**Comment by braginini** [comment]
hey @ashutoshpw 
It is very nice of you to offer help with making videos! Thank you.

I think we could add a 3rd option to your list - "Using [https://beta.wiretrustee.com/](https://beta.wiretrustee.com/)"
This is the easiest set up just to try the system (under 5 minutes). 
It is not a self-hosted option but is the fastest to show case the capabilities. 
Here is the video that explains what I mean [https://www.youtube.com/watch?v=j0EPaK5Rapw](https://www.youtube.com/watch?v=j0EPaK5Rapw). Of course, it is just an example and was the 1st try, I didn't do any editing, etc - you can do it better :)

Then you could prepare another one with a self-hosted setup. 
There is one caveat - you will need an [Auth0](http://auth0.com/) account to make it work. We are preparing documentation on this part.

**Comment by ashutoshpw** [comment]
Sure @braginini , I will come up with a video soon and will post the link here so you could review!

**Comment by braginini** [comment]
@ashutoshpw Excellent!
Thank you for your support!

**Comment by ashutoshpw** [comment]
Hi @braginini 

Please check this video and let me know if that looks good
https://www.youtube.com/watch?v=uaXXUypq0jk

**Comment by braginini** [comment]
thank you @ashutoshpw 
Looks great!

**Comment by mlsmaycon** [comment]
leaving this internally
