### ISSUE TITLE
update 0.28.0 all down

### ISSUE THREAD

**Issue by 07ke** [netbirdio/netbird#2160]
Docker v0.27.10 update to 0.28.0

![image](https://github.com/netbirdio/netbird/assets/17754548/b54835e7-09ec-4bdd-a376-15ba8c90e243)
![image](https://github.com/netbirdio/netbird/assets/17754548/14063864-7c1f-40cd-b1ff-cd5e01da75ca)
![image](https://github.com/netbirdio/netbird/assets/17754548/19e496ae-40cf-4c82-b5e8-8d30c86f4a7b)
![image](https://github.com/netbirdio/netbird/assets/17754548/5f514038-2951-4e66-a075-810a8218bd0b)

The domain name is wrong and cannot be connected。

Windows 11(0.28.0) & Centos 8 (0.28.0) Test

**Comment by nikolicjakov** [comment]
Could this be related to https://github.com/netbirdio/netbird/issues/2157 ...?

**Comment by mlsmaycon** [comment]
Hello @07ke the -A flag anonymizes the output. Can you check without it?

**Comment by 07ke** [comment]
> Hello @07ke the -A flag anonymizes the output. Can you check without it?

Yes. It's solved. Maybe I didn't notice it before because it didn't work.
