### ISSUE TITLE
macos Internal Netbird DNS resolver uses IPv6

### ISSUE THREAD

**Issue by ez1976** [netbirdio/netbird#2201]
Hi.
when not connected to netbird, the MacOS is using the regular laptop DNS and all is well.
but once connected to netbird (and IPv6 is enabled on the MAC), any requests to external resources are automatically delayed by 30 seconds.
it seems that if i do nslookup i always get the correct IP but using netbird i can see also an additional line for  rdata_46).
if i run:
sudo networksetup -setv6off Ethernet
sudo networksetup -setv6off Wi-Fi

it disables the IPv6 and works right away
so it seems that the internal netbird DNS resolver is trying to query via IPv6

**Comment by mlsmaycon** [comment]
Thanks for reporting the issue @ez1976 . I was not able to replicate the issue. Can you share more information about your routing setup that might influence the DNS resolution? For instance, do you have exit node routes or DNS routes enabled? 

Also, is this delay observed only in the agent startup? And having a  match domain for the DNS queries you are performing helps with the issue?
