### ISSUE TITLE
Self-hosted Ubuntu logs filling up the disk

### ISSUE THREAD

**Issue by jluisoma** [netbirdio/netbird#2202]
**Describe the problem**

I've been running Netbird on my Ubuntu 22.04.4 for about two months.
Last week two peers failed to connect and I discovered that the Ubuntu VM was out of disk space.  I couldn't do much other than logging in so I had to restore the VM from backup to a week old image and I was then able to resize the volumes.

I have been trying to figure out the culprit (I'm a Linux beginner) and found the following issues:
1. There is a root_caddy_1 docker image that seems to be saving logs in "debug" mode, which caused the volume to fill up.  So far is about 17Gb in size and growing about 1Gb every 36 hrs.
2. I couldn't find a /etc/docker/daemon.json file to change the log level to "info" or to set logging rotation -- according to some research I did.
3. If there is not an automated way to clear the logs, what is the recommended way to do this?

**Expected behavior**

The logs should automatically truncate so the server doesn't run out of disk space.

**Are you using NetBird Cloud?**

Self hosted

**NetBird version**

`netbird version`

**NetBird status -d output:**

N/A

**Screenshots**
![Screenshot 2024-06-26 095053](https://github.com/netbirdio/netbird/assets/171960879/49ea23bb-3bb6-42bf-ba69-4e45f3d32a86)
![Screenshot 2024-06-26 100053](https://github.com/netbirdio/netbird/assets/171960879/93d2a4da-4fcc-42de-be5c-00f8aeabe76b)

**Additional context**

This is an example of the logs:

__{"level":"debug","ts":1719411987.5158257,"logger":"http.handlers.reverse_proxy","msg":"selected upstream","dial":"signal:10000","total_upstreams":1}
{"level":"debug","ts":1719411987.5170805,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"signal:10000","duration":0.00113983,"request":{"remote_ip":"65.155.56.98","remote_port":"53576","client_ip":"65.155.56.98","proto":"HTTP/2.0","method":"POST","host":"my.domaingoeshere.com:443","uri":"/signalexchange.SignalExchange/Send","headers":{"Te":["trailers"],"Grpc-Timeout":["9999979u"],"X-Forwarded-For":["65.155.56.98"],"X-Forwarded-Proto":["https"],"X-Forwarded-Host":["my.domaingoeshere.com:443"],"Content-Type":["application/grpc"],"User-Agent":["grpc-go/1.64.0"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"my.domaingoeshere.com"}},"headers":{"Content-Type":["application/grpc"]},"status":200}__

**Comment by mlsmaycon** [comment]
@jluisoma you can update your docker-compose.yml file with the log configuration as the new template recently pushed:

https://github.com/netbirdio/netbird/blob/main/infrastructure_files/docker-compose.yml.tmpl#L47

After adding this to all services, you can run `docker compose up -d` to apply.

**Comment by jluisoma** [comment]
Great.  Made the changes and volume size went down to 13Gb.
Appreciate the help!
