### ISSUE TITLE
Setup Keys EXPIRES

### ISSUE THREAD

**Issue by chmis8000** [netbirdio/netbird#221]
The expiration time of the Setup Keys is 30 days. Can you specify the time?

**Comment by braginini** [comment]
Hey @chmis8000 
Not possible in the current version but it is a good idea and I think it is worth having this feature.

Will add to our plan

**Comment by rhinot** [comment]
To extend this request, I'd to request that time can be X Days or "Non-expiring".

Alternatively to "non-expiring", a single click way to re-extend the keys which is proactively sent to the owner account.


Use case: Want to set up a permanent distributed network, without having to remote into each machine and type in new set up key (and pre-shared key)

**Comment by braginini** [comment]
@rhinot thank you for the feedback.

You don't need to extend the setup key for peers to be in the network. 
The setup key expiration means that after a certain time it can't be used anymore to add new peers. 
But all peers that were registered with this key are still connected.

peers are identifying themselves with a Wireguard public key (used internally).

See more on setup keys here:
https://docs.wiretrustee.com/overview/setup-keys#expiration

**Comment by timwsuqld** [comment]
@chmis8000 can you please reopen this? We want the setup key to be used for automated deployments, and having to update the automated deployment system every 30 days makes netbird a non-starter for us. Ideally we want a 1-2 year expiry, or never expiring (so we can rotate it as we want).

**Comment by braginini** [comment]
@timwsuqld 
Sounds very reasonable. I think that I could add custom expiration this week. Will ping you

**Comment by mlsmaycon** [comment]
done in https://github.com/netbirdio/dashboard/pull/90
