### ISSUE TITLE
Netbird resets network adapter at every reboot on Windows

### ISSUE THREAD

**Issue by graphixillusion** [netbirdio/netbird#2217]
**Describe the problem**
At every reboot the netbird's network adapter is reset: 
- the name of the interface will increase by one number at every reboot: (Name wt0 1, wt0 2, wt0 3, ...) 
- the alias of the interface is always the same (wt0)

A clear and concise description of what the problem is.

The problem is that if i set the connection to private, it resets to public at every os reboot.

**To Reproduce**
1. set-netConnectionProfile -InterfaceAlias wt0 -NetworkCategory "Private" 
2. reboot the system
3. network profile is reverted back to public becouse the name of the interface changes the name with a +1 while still keeping the same alias as described before.

**Expected behavior**

Netbird should keep the same interface name and keep the settings applied.

**NetBird version**

0.28.3 on Windows 11 23H2

**Comment by Marcus1Pierce** [comment]
Same here on every windows connect to netbird

**Comment by graphixillusion** [comment]
Any news about this?

**Comment by maikl88** [comment]
v0.25.6 the same thing

**Comment by Svetloslav** [comment]
Wow, we are at version 0.28.9 yet absolutely no one from development cares about such a huge bug. In another thread a guy proposed a solution of a few simple lines. What a sad shame.

**Comment by graphixillusion** [comment]
Indeed

**Comment by graphixillusion** [comment]
It seems that since version 0.29.0 this issue is not happening anymore. I will report it back if something wrong will happen again...

**Comment by maikl88** [comment]
> It seems that since version 0.29.0 this issue is not happening anymore. I will report it back if something wrong will happen again...

hm, windows 11 home 23H2 netbird 29.0.1 after reinstalling from a lower version, it seems to work fine. the wt interfaces do not change

**Comment by Marcus1Pierce** [comment]
> It seems that since version 0.29.0 this issue is not happening anymore. I will report it back if something wrong will happen again...

I can confirm after reset the networklist profiles in registry, my wt0 interface still wt0 without any number now. Looks like the update include this fix (maybe). And after update to 0.29.1 and now 0.29.2 the problem looks like really gone.

**Comment by Marcus1Pierce** [comment]
@graphixillusion Now it's version 0.34.1 and the issue no longer exists. Maybe this issue should be closed.
