### ISSUE TITLE
Netbird isn't available for MacOS 12?

### ISSUE THREAD

**Issue by myevit** [netbirdio/netbird#2218]
I have old Macbook that can run only MacOS 12.7.5. Current installer require MacOS 14 min. 
<img width="264" alt="Screen Shot 2024-06-30 at 7 41 25 PM" src="https://github.com/netbirdio/netbird/assets/13375246/2166c490-ebcf-4dff-bd99-27dec57fac50">

Is there an instructions to build netbird for  MacOs 12?

**Comment by chris-si** [comment]
I just experienced the same behavior on macOS 13 with the latest client. I'd be great if that could be fixed again.

**Comment by mlsmaycon** [comment]
We recently updated our GUI client build machine version, which probably broke something with Xcode. 

We will double-check it and see how we can continue to support older OS versions. We will get back to you soon. In the meantime, you can download the 0.28.2 version: https://github.com/netbirdio/netbird/releases/download/v0.28.2/netbird_0.28.2_darwin_arm64.pkg

**Comment by mlsmaycon** [comment]
@myevit @chris-si the fix will come in the next release.

**Comment by myevit** [comment]
> @myevit @chris-si the fix will come in the next release.

Thank you!
