### ISSUE TITLE
Can't set management URL on macOS client (Apple Silicon) 0.28.3 - Error: "Invalid interface port"

### ISSUE THREAD

**Issue by flotpg** [netbirdio/netbird#2231]
**Describe the problem**

When I try to set the management URL, I get an "Invalid interface port" error.

- macOS Sonoma 14.5 (23F79)
- installed via brew (Casks: netbirdio/tap/netbird-ui)

**Expected behavior**

Be able to set the management URL.

**Are you using NetBird Cloud?**
Self-host NetBird's control plane:

- Server is running Netbird management version:  "0.28.3"
- Server is running Netbird dashboard version:  "v2.4.0"

**NetBird version**

`0.28.3`

**Screenshots**
![CleanShot 2024-07-03 at 16 07 47@2x](https://github.com/netbirdio/netbird/assets/20798074/42408def-7d22-48b4-93f5-eae342557c8c)

**Comment by flotpg** [comment]
After stopping the service, uninstalling the service, re-installing and starting again, it works:
```
sudo netbird service stop
Netbird service has been stopped

sudo netbird service uninstall
Netbird service has been uninstalled

sudo netbird service install
Netbird service has been installed

sudo netbird service start
Netbird service has been started
```
![CleanShot 2024-07-03 at 16 21 25@2x](https://github.com/netbirdio/netbird/assets/20798074/a0acc0ba-f798-49bc-bc70-8715970a8477)

**Comment by pappz** [comment]
The error message looks valid. The "interface port" was empty.

**Comment by fmedinaq** [comment]
qa
