### ISSUE TITLE
Seems like UDP hole punching is not working or something else

### ISSUE THREAD

**Issue by shrisha108** [netbirdio/netbird#227]
Hello,
I just registered with official Wiretrustee website to try this service and added two machines, Fedora 35 and Ubuntu 20.04. In a dashboard I can see that both peers are online but when I'm trying to ping them nether of them can reach each other. What could be a problem? Some ports should be open? Setup seems quite straight forward. Log not showing any errors.
Any help would be appreciated.
Regards.

**Comment by mlsmaycon** [comment]
Hello @shrisha108 , sorry to hear that you are facing such issues with Wiretrustee and I would like to help you on this issue. 

To answer your question, in many default cases, they should be able to communicate directly without further configuration required. Also, currently, our connection status in the dashboard reflects only management to peer status and not peer-to-peer connections, with that in mind, can you check a couple of things to help us understand better your case?

1 - Is there any restricted firewall rules in either node?
2 - check for connection status in our client logs:
```shell
sudo grep 'opened a connection to peer' /var/log/wiretrustee/client.log
```
3 - if that doesn't return any logs, you can send us the warn and error logs:
```shell
sudo grep -E 'warn|error'  /var/log/wiretrustee/client.log
``` 
Also, I would be happy to follow up on our community [Slack Workspace](https://join.slack.com/t/wiretrustee/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A)

**Comment by shrisha108** [comment]
Hello @mlsmaycon Thank your for your answer. Should I just send you direct message on Slack Workspace?

**Comment by mlsmaycon** [comment]
Thanks, @shrisha108, for your time in our troubleshooting chat. 

Just documenting our findings. The issue was caused by existing Iptables rules that were dropping packets from the CGNAT used by Wiretrustee. 

```shell
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ts-input   all  --  0.0.0.0/0            0.0.0.0/0 
....
.....
Chain ts-input (1 references)
target     prot opt source               destination         
ACCEPT     all  --  100.125.145.17       0.0.0.0/0           
RETURN     all  --  100.115.92.0/23      0.0.0.0/0           
DROP       all  --  100.64.0.0/10        0.0.0.0/0
```

executing the command below solved the issue:
```shell
sudo iptables -I  ts-input  1 -s 100.64.0.0/24 -j ACCEPT
```

As we discussed, I will follow up on the Oracle cloud investigation on the ticket #228
