### ISSUE TITLE
Window CLI

### ISSUE THREAD

**Issue by ismail0234** [netbirdio/netbird#2293]
Hello, 

Is it possible to install and use this program in windows via command line? In a project I am using, I would like to be able to silently install this program and join the network with the command line.

**Comment by roberthase** [comment]
I use the following powershell script in our gpo for installing and updating netbird from a fileshare/netlogon on windows client-computers:
You might want to use a wmi filter which only applies to battery powered devices like notebooks and tablets.

$currentVersion = "0.28.4.9780101341"   
$installedVersion = Get-ItemPropertyValue HKLM:SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Netbird -Name DisplayVersion

_#this part sets the version you want to be installed and which is installed on the computer._

if ($installedVersion -ne $currentVersion) {
    Copy-Item "\\your\fileshare\netbird0.28.4.exe" "C:\Temp\netbird0.28.4.exe" -Force #this copies the netbird installer to a local directory
    Start-Process "C:\Temp\netbird0.28.4.exe" -ArgumentList "/S" -NoNewWindow -Wait

_#if the installed version is not the version you want be installed, the netbirdinstaller gets copied on to the local computer and is installed (this part is important, if you are updating from outside the network as netbird gets completly reinstalled(netbird is gone and your computer cant access the fileshare anymore)_

    Start-Sleep -Seconds 15
    $Env:Path = [System.Environment]::GetEnvironmentVariable("Path", "Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path", "User")
    Start-Sleep -Seconds 15

_#this renews the variables so you can use the netbird up command_

    netbird up --setup-key "YOURKEY" --management-url https://your.url:33073
    Remove-Item "C:\Temp\netbird0.28.4.exe" -Force

_#this part connects netbird to your controller with a setupkey und removes the installer_
    echo "Netbird installed/updated to version $currentVersion"
} else {
    echo "Netbird is already up to date with version $currentVersion"
}

_#if netbird is installed and the current version the script does nothing_
