### ISSUE TITLE
libappindicator3.so.1 is outdated and doesnt work on some linux distrubutions

### ISSUE THREAD

**Issue by simen64** [netbirdio/netbird#2304]
**Describe the problem**

On void-linux (may also be on other distros) the netbird-ui app wont load because it cant find libappindicator3.so.1 This library is outdated as the latest release was in 2012, and distros like void doesnt package it anymore.
https://launchpad.net/libappindicator

**To Reproduce**

1. Be on void linux or any other distro without libappindicator3.so.1
2. Try launching netbird ui `netbird-ui`
3. Get error: `netbird-ui: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory`

**Expected behavior**

Netbird UI launching

**NetBird version**

`0.28.6`

**Comment by bcmmbaga** [comment]
Hello @simen64 , can you check if `libayatana-appindicator` is available in void-linux?

**Comment by simen64** [comment]
Yes it is in the repos

**Comment by bcmmbaga** [comment]
Could you please install it and test if NetBird-UI works?

**Comment by simen64** [comment]
It gives the same error.
According to this thread it needs to be fixed upstream
https://www.reddit.com/r/voidlinux/comments/lfy5kv/error_while_loading_shared_libraries/

**Comment by bcmmbaga** [comment]
Can you download the NetBird-UI (this version does not contain support for the legacy indicator) https://github.com/netbirdio/netbird/actions/runs/10060312792/artifacts/1730753028 and then test if it works now?

**Comment by xadhoom** [comment]
Same on Fedora 40, wanted to try the above link, but it states "Failed to generate URL to download artifact."

**Comment by bcmmbaga** [comment]
> Same on Fedora 40, wanted to try the above link, but it states "Failed to generate URL to download artifact."

The previous link has expired. Please use this new link
 https://github.com/netbirdio/netbird/actions/runs/10060312792/artifacts/1768310854

**Comment by xadhoom** [comment]
Now the app "starts", but I get the following error:

2024/08/02 12:17:16 systray error: failed to register: The name is not activatable

And I cannot see the tray icon anywhere, but maybe this is a different issue. Using FC40 + Gnome + Wayland (which is the default of Fedora)

**Comment by bcmmbaga** [comment]
> The name is not activatable

Did you install the deb and run it, or are you running the binary directly from the terminal?

**Comment by xadhoom** [comment]
Being Fedora, I installed the rpm and run it (from the terminal)

Now I've tried to run the amd64 binary present in the artifacts directly from the terminal, but got same result.

**Comment by bcmmbaga** [comment]
> Being Fedora, I installed the rpm and run it (from the terminal)
> 
> Now I've tried to run the amd64 binary present in the artifacts directly from the terminal, but got same result.

To determine if this is a GNOME-specific issue, I recommend installing [gnome-shell-extension-appindicator](https://github.com/ubuntu/gnome-shell-extension-appindicator) and test again.

**Comment by acarstoiu** [comment]
This can be closed, I've tested the _0.29.4_ version.

**Comment by mgarces** [comment]
this was tested and documentation was added on https://github.com/netbirdio/docs/pull/257
