### ISSUE TITLE
Locked out of app.netbird.io and vpn clients unable to connect

### ISSUE THREAD

**Issue by MichaelCCBulwark** [netbirdio/netbird#2306]
Out of nowhere this evening some of my clients started having issues connecting. When I went to begin triage by logging into the Netbird cloud web portal it would not load no matter how long I wait (over an hour now.) We are dead in the water at this point and there is nothing I can do to even attempt to remediate because the web portal will not load for me at all. I have a hard time believing this is only affecting us as there was no trigger or any changes made today but when I connect to app.netbird.io with my personal email and create a new network it loads just fine so I'm forced to wonder if it has something to do with the google IDP synchronization. regardless we need support or we need to abandon Netbird as a product.

**To Reproduce**

1. Attempt to log into app.netbird.io with a bulwarkpest email account
or
1. Attempt to connect the netbird client with either a bulwarkpest email account or application key

**Expected behavior**

App.netbird.io loads the admin panel with peers and settings
or
Netbird client connects

**Are you using NetBird Cloud?**

We are using Netbird Cloud

**NetBird version**

0.28.4

**Screenshots**

![image](https://github.com/user-attachments/assets/3cf4a7d8-ff75-47b3-8653-b0df38981dac)

![image](https://github.com/user-attachments/assets/bf9db489-a055-4c76-bfbf-f4660fa0ada9)

**Comment by bcmmbaga** [comment]
The issue has been resolved through our email support, and everything is now functioning correctly. I will go ahead and close the issue.
