### ISSUE TITLE
IPv6 format for DNS (linux)

### ISSUE THREAD

**Issue by WolfgangDpunkt** [netbirdio/netbird#2327]
> this adds the address in the expected format in Go [ipv6]:port

I think this would also have to be adapted for the Linux client.
Every ipv6 DNS address that I enter via the Management Gui results in this error message on a debian server client:

`dial udp: address 2001:4860:4860::8888:53: too many colons in address`

_Originally posted by @WolfgangDpunkt in https://github.com/netbirdio/netbird/issues/1350#issuecomment-2231800597_

**Comment by v1rusnl** [comment]
@WolfgangDpunkt I had same problem. After that I put the shortened IPv6 into the Netbird IP field as the unshortended version and for some weird reason after saving, Netbird shortended the IPs by itself and now the IPv6 adresses are available in the clients without any errors. So give it a try and insert `2001:4860:4860:0000:0000:0000:0000:8888` into Netbird UI. For me it worked.
