### ISSUE TITLE
Proper FreeBSD icon in management UI

### ISSUE THREAD

**Issue by skillcoder** [netbirdio/netbird#2339]
**Describe the problem**

This is what I see in my management UI for FreeBSD server
![Screenshot_20240728_142822-1](https://github.com/user-attachments/assets/952e5deb-b46a-4b21-8386-2223838143ba)

**To Reproduce**

1. Run current client on FreeBSD from master.
Here you can find a full list of required actions: https://github.com/netbirdio/netbird/issues/1505#issuecomment-2254208989
2. Open https://app.netbird.io/peers and take a look on icon for you FreeBSD server, you will the generic linux icon

**Expected behavior**
Instead of generic linux icon you should see in management UI something like this:
![freebsd-icon-512x504-ge1jboyc](https://github.com/user-attachments/assets/5f8beef9-d83c-4be0-983c-02525f46b3c8)

**Are you using NetBird Cloud?**

Does not mater, the icon should be correct in NetBird Cloud and self-host NetBird's control plane.

**NetBird version**

current master, latest current tag [v0.28.6](https://github.com/netbirdio/netbird/releases/tag/v0.28.6)

**NetBird status -d output:**

Not related to the client, after https://github.com/netbirdio/netbird/pull/2078 client should send correct GoOS, OS

**Screenshots**

Screenshot provided in  **Describe the problem**

**Additional context**

-

**Comment by mlsmaycon** [comment]
we have an internal PR fixing that already:

![image](https://github.com/user-attachments/assets/ae9b0512-22f0-4916-85f4-25a8a45875f8)
