### ISSUE TITLE
Add support for Wireguard over TCP using mullvad's method of UDP tunneling over TCP

### ISSUE THREAD

**Issue by shadow2399** [netbirdio/netbird#2367]
**Is your feature request related to a problem? Please describe.**
Wireguard traffic when inspected by an ISP or some other entity monitoring traffic screams itself out with almost no obsfucation. Yes, the traffic is still encrypted, but there's nothing stopping an ISP from simply blocking the traffic in bad-acting countries.

**Describe the solution you'd like**
Integrate TCP based wireguard by tunneling UDP over TCP connections. Look at mullvad vpn's source code for integration reference:
https://github.com/mullvad/mullvadvpn-app

**Describe alternatives you've considered**
Simply not integrating it due to challenges.

**Additional context**
This method is likely going to be very slow, but make it a configurable advanced option that could help a user out if they need it. This will help with issue #1096's ISP blocking of netbird traffic.

**Comment by lixmal** [comment]
We already have wireguard over TURN (if proto tcp is configured) when using relay. It can be forced by using the env var `NB_ICE_FORCE_RELAY_CONN=true` on the client

Is that of any help?

**Comment by shadow2399** [comment]
Yeah I think that covers it then. Thanks for your help!

**Comment by PRNDA** [comment]
> We already have wireguard over tcp when using relay with a tcp enabled turn server. It can be forced by using the env var `NB_ICE_FORCE_RELAY_CONN=true` on the client
> 
> Is that of any help?

Is this supported by iOS/macOS clients? Are there any docs about this?

**Comment by willcipher** [comment]
> Is this supported by iOS/macOS clients? Are there any docs about this?

Not sure if you found your answer elsewhere, but here's the (hack) workaround I'm using:

```
sudo cp /Library/LaunchDaemons/netbird.plist /Library/LaunchDaemons/netbird.plist.orig
sudo nano /Library/LaunchDaemons/netbird.plist

```
I inserted an **EnvironmentVariables** key (context shown above and below):

```
...
	<key>Label</key>
	<string>netbird</string>
	<key>EnvironmentVariables</key>
	<dict>
		<key>NB_FORCE_RELAY</key>
		<string>true</string>
	</dict>
	<key>ProgramArguments</key>
...
```
Then...
```
sudo launchctl unload /Library/LaunchDaemons/netbird.plist
sudo launchctl load /Library/LaunchDaemons/netbird.plist
```
Subsequently, my Mac used only the relay for all connections.

I'm using `NB_FORCE_RELAY` due to this suggestion: [Force relay connection not working](https://github.com/netbirdio/netbird/issues/4063#issuecomment-3013544805)

Not sure how to accomplish this on iOS.
