### ISSUE TITLE
Support for Android 5.1

### ISSUE THREAD

**Issue by michele-grifa** [netbirdio/netbird#2409]
**Is your feature request related to a problem? Please describe.**
It is possible to support Android 5.1, because right now the error in the log are "util/net/dialer_android.go:20 failed to protect socket" and "client/internal/login.go:96 failed connecting to the Management service https://app.netbird.io:443 context deadline exceeded".

**Describe the solution you'd like**
The Android client should connect.

**Describe alternatives you've considered**

**Additional context**

**Comment by yaneony** [comment]
Android Lollipop is like 10 years old. Not even supported by google itself...

**Comment by Marcus1Pierce** [comment]
Android 5 is no longer supported, even by Google itself. And it seems Netbird will have to do the same. 
@mlsmaycon?

**Comment by yaneony** [comment]
Like asking to support Windows XP...

**Comment by mgarces** [comment]
Hi there @michele-grifa can you please test latest Android release?

**Comment by michele-grifa** [comment]
> Hi there @michele-grifa can you please test latest Android release? We need a minimal of `SdkVersion = 26` which corresponds to Android 8.0, so I think you won't have much chance, even with the latest version.

Hi, I ended up replacing the old devices with new ones. Thanks for the help anyway.
