### ISSUE TITLE
Unable to reach /api/peers, receive 404

### ISSUE THREAD

**Issue by velopsiraptor-github** [netbirdio/netbird#2422]
**Describe the problem**

I deployed netbird (self-hosted) via the advanced guide.  I have netbird running successfully and authenticating with Zitadel.  However, when attempting to query `/api/peers` via curl or anything else to use the API, I get a 404.  It seems that the management UI has `/peers`, and when I go to `/api/peers` in the UI, it redirects me back to `/peers`.

I can only assume that I have something misconfigured, but I swear I've looked over everything and I can't seem to find anything that would point me in the right direction.  Has this been seen before? Is there an easy solution or place I can start looking to resolve this?

**Are you using NetBird Cloud?**

Self-hosted

**NetBird version**

0.28.7

**NetBird status -dA output:**

Unable to run this, netbird running in docker, no apparent `netbird` binary in any of the containers.

**Additional context**

Clients seem to connect just fine and are able to ping each other over the tunnel IPs.  Just not sure why `/api/peers` is returning a `404`, along with other `/api/*` routes.

**Comment by pascal-fischer** [comment]
Hi @velopsiraptor-github,
the `/api/*` paths are part of the management backend service while `/peers` is part of the dashboard. So depending on your setup those will most likely have different domains configured. Your dashboard (opening `/peers`) is running fine correct? You can use the developer tools in your browser and check the API calls to find the correct address.

**Comment by velopsiraptor-github** [comment]
Ah, so that makes sense! I appreciate the reply! It looks like the `/api` routes are over `33073` (which is the management port).  Thanks for at least getting me to a place where I can confirm the information I needed.  Much appreciated.
