### ISSUE TITLE
"TypeError: Failed to fetch" upon log in. 

### ISSUE THREAD

**Issue by WGandy** [netbirdio/netbird#246]
I just set this up on ubuntu 20.04.4 with docker compose for self hosting.  
I think everything went according to plan. There isn't anything too weird in the logs, as far as I can tell. But I get this type error line twice just above the dotted box for peers. And, if I click on the link to add a peer, I can't select the key type (default or one shot). 

![image](https://user-images.githubusercontent.com/81717633/156309667-6bc74118-4a69-4c1c-bf8b-3bc1ab834a9b.png)

**Comment by WGandy** [comment]
Yes, I referenced that guide and watched the youtube video. 

The one issue I had while installing was a problem with the dns for my domain. Let's Encrypt failed on the first try and it seems to be because that domain/subdomain was involved with cloudflare proxy. I switched to an entirely different domain (and simple dns provided by the registrar), updated the setup.env file and auth0 and ran the ./configure.sh script again. That time it made the certs correctly. But perhaps running the configure.sh a second time caused a second problem? 

I'm planning to wipe out the entire wiretrustee directory and start over.  Unless you have some other suggestions.

**Comment by mlsmaycon** [comment]
Hello @WGandy, we've updated the templates to use a shared certificate for both, dashboard and management API.

Can you please verify ?

**Comment by WGandy** [comment]
Just to follow up, Maycon did a great job of digging into this and the update seems to solve the issue. 
There is a detail that I'm still concerned might snag someone. Step 3 of the "Add Peer" instructions on the management dashboard needs to be updated to include an additional argument. 
`--management-url [https://](https://$WIRETRUSTEE_DOMAIN:33073/)` 
I disregarded Maycon's instructions (forgot) and just followed the instructions presented on the Add Peer page which got me into trouble.  

I suspect that this argument may be baked into the client code in the future and then won't be necessary??

**Comment by mlsmaycon** [comment]
Thank you @WGandy, I've opened the ticket https://github.com/wiretrustee/wiretrustee-dashboard/issues/18
