### ISSUE TITLE
Build management docker image error

### ISSUE THREAD

**Issue by BJorah** [netbirdio/netbird#2464]
Under this directory "/netbird-0.28.6/management",
 I use this `docker build -t nb-mgmt:test01 .`  to build a management docker image, but it but got an error below:
```
=> ERROR [3/3] COPY netbird-mgmt /go/bin/netbird-mgmt                                                           0.0s
------
 > [3/3] COPY netbird-mgmt /go/bin/netbird-mgmt:
------
Dockerfile:5
--------------------
   3 |     ENTRYPOINT [ "/go/bin/netbird-mgmt","management"]
   4 |     CMD ["--log-file", "console"]
   5 | >>> COPY netbird-mgmt /go/bin/netbird-mgmt
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 30bc39d0-bf08-488b-90ad-f1f08153165b::pg3meq19vofr8fqz9bpwnjkrn: "/netbird-mgmt": not found
```

For the missing '/netbird-mgmt' ,  does it mean you create a go mod named 'netbird-mgmt', and use `go  build` to create  the executable program named  'netbird-mgmt'?

**Comment by bcmmbaga** [comment]
you need to build the netbird-mgmt executable first before running the docker build command.

```sh
CGO_ENABLED=1 GOOS=linux GOARCH=<ARCH> go build -o netbird-mgmt .
```

Replace `<ARCH>` with the appropriate architecture for your target environment. Once the executable is built, you can then run the docker build command

**Comment by BJorah** [comment]
thanks a lot I made it.
