### ISSUE TITLE
How to get management.log when running in docker?

### ISSUE THREAD

**Issue by BJorah** [netbirdio/netbird#2494]
When I run netbird-mgmt locally， I can see the log information  in /var/log/netbird/management.log , but How can I get the log when I run management on the self-host  server running in  docker?

**Comment by saule1508** [comment]
this is more for the slack channel I think
You can see the logs with

`docker compose logs management`

or you can see them in /var/lib/docker/containers/<containerid>, there is a log file there

**Comment by BJorah** [comment]
Cool, I successfully get the log.
Thank you very much!  @saule1508
