### ISSUE TITLE
Fresh macOS install from cli, dashboard not accessible

### ISSUE THREAD

**Issue by gabrielstuff** [netbirdio/netbird#2502]
**Describe the problem**

The dashboard at https://app.netbird.io/peers is not accessible. Netbird says it is connected but the dashboard url always shows: 

<img width="1510" alt="image" src="https://github.com/user-attachments/assets/75e41cc5-b3db-4672-ba7a-0d72b2d4f712">

**To Reproduce**

1. Go to net bird webiste, read the doc
2. Install from command line

**Expected behavior**

Access to the dashboard

**Are you using NetBird Cloud?**

yes

**NetBird version**

`netbird version`

```
➜ netbird version
0.28.9
```

**NetBird status -dA output:**

If applicable, add the `netbird status -dA' command output.

```
Peers detail:
 g***-laptop.netbird.cloud:
  NetBird IP: 100.70.135.79
  Public key: +Y5Ww4/yTJTMH3BmGe8skY4ElykVmJvrgmlrxQv1aHA=
  Status: Disconnected
  -- detail --
  Connection type:
  Direct: false
  ICE candidate (Local/Remote): -/-
  ICE candidate endpoints (Local/Remote): -/-
  Last connection update: -
  Last WireGuard handshake: -
  Transfer status (received/sent) 0 B/0 B
  Quantum resistance: false
  Routes: -
  Latency: 0s

 y***-x1.netbird.cloud:
  NetBird IP: 100.70.148.26
  Public key: TILLsoBvDU13rVDzFvcyQZqoNqAmHvZ1DxMpaaP06lQ=
  Status: Disconnected
  -- detail --
  Connection type:
  Direct: false
  ICE candidate (Local/Remote): -/-
  ICE candidate endpoints (Local/Remote): -/-
  Last connection update: -
  Last WireGuard handshake: -
  Transfer status (received/sent) 0 B/0 B
  Quantum resistance: false
  Routes: -
  Latency: 0s

 netbird-exit.netbird.cloud:
  NetBird IP: 100.70.XXX.XXX
  Public key: 9GYoFraE0UwSeipOduT6N8i7Itdr7JdWG5FKS3Z6XHA=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): srflx/srflx
  ICE candidate endpoints (Local/Remote): 198.51.XXX.X:51820/198.51.XXX.X:51820
  Last connection update: 4 minutes ago
  Last WireGuard handshake: Now
  Transfer status (received/sent) 7.2 MiB/2.0 MiB
  Quantum resistance: false
  Routes: 0.0.0.0/0
  Latency: 12.646208ms

OS: darwin/arm64
Daemon version: 0.28.9
CLI version: 0.28.9
Management: Connected to https://api.netbird.io:443
Signal: Connected to https://signal.netbird.io:443
Relays:
  [stun:stun.netbird.io:5555] is Available
  [turns:turn.netbird.io:443?transport=tcp] is Available
Nameservers:
FQDN: gabriels-laptop-1.netbird.cloud
NetBird IP: 100.70.1.253/16
Interface type: Userspace
Quantum resistance: false
Routes: -
Peers count: 1/3 Connected
```

**Do you face any (non-mobile) client issues?**

Please provide the file created by `netbird debug for 1m -AS`.
We advise reviewing the anonymized files for any remaining PII.

**Screenshots**

**Additional context**

**Comment by heisbrot** [comment]
Hey @gabrielstuff ,

you are currently logged in as a regular user and not admin.
There could be another E-Mail domain already registered which is the owner of the domain / account.

Please reach out to [support@netbird.io](mailto:support@netbird.io) with the E-Mail address you are currently logged in.
We can help you identify the current owner E-Mail address.
