### ISSUE TITLE
Dashboard not showing peers that have been added, stuck on “Add new device to your network”

### ISSUE THREAD

**Issue by Heavensong89** [netbirdio/netbird#2506]
**Describe the problem**

I’ve just set-up a self-hosted NetBird, logged in to the dashboard and download the NetBird app on my iPad and iPhone. Both are connected to my netbird server and show as peers connected in the app, but when I go to the Dashboard, I am just presented with the “Add new device to your network” page, with no options to navigate anywhere else. 

**Expected behavior**

Be able to view the NetBird Dashboard

**Are you using NetBird Cloud?**

Self-Hosted

**Comment by Heavensong89** [comment]
Found a similar issue elsewhere, needed to delete my docker mgmt volume and bring the stack back up

**Comment by laravieira** [comment]
Same issue, added 3 peers, all connected, they can ping each other. Panel stuck at "Install Netbird" or "Add new device to your network" screens.

The `/api/users/current` endpoint says I'm a restricted user and I don't have any permissions, even though I just created the account:
```
{
    "auto_groups": [],
    "email": "...",
    "id": "...",
    "is_blocked": false,
    "is_current": true,
    "is_service_user": false,
    "issued": "api",
    "last_login": "2025-10-01T13:56:09.894Z",
    "name": "...",
    "pending_approval": false,
    "permissions": {
        "is_restricted": true,
        "modules": {
            // All false
        }
    },
    "role": "user",
    "status": "active"
}
```

**Comment by laravieira** [comment]
I discovered the account I created was magically assigned to another account with the same email domain.
Thanks to this, it gave me a hint: https://www.answeroverflow.com/m/1366167902906089542
