### ISSUE TITLE
OpenWRT not able to login

### ISSUE THREAD

**Issue by Gauss23** [netbirdio/netbird#2512]
**Describe the problem**

Clean installation of gl-inet AR300M with OpenWrt 22.03.4 with their firmware 4.3.17. Installed Netbird `https://downloads.openwrt.org/snapshots/packages/mips_24kc/packages/netbird_0.28.9-r1_mips_24kc.ipk
`
Netbird up with setup key says:
`Error: login backoff cycle failed: rpc error: code = DeadlineExceeded desc = context deadline exceeded
`
In the logfile I see:
```
2024-09-01T20:36:00Z ERRO client/server/server.go:262: failed login: context deadline exceeded
2024-09-01T20:36:00Z ERRO util/grpc/dialer.go:38: Failed to dial: dial: dial tcp ####:443: connect: invalid argument

```
Seems like a Go problem. Version 0.17 works for OpenWrt but is missing important features. Would be great to get the current version running. Looks like something changed between 0.17 and 0.28.9 with the go implementation to connect to the management server.

**To Reproduce**

1. Fresh firmware on gl-inet AR300M
2. Download netbird package from the snapshot tree
3. install netbird
4. run netbird up with setup-key
5. wait until it times out and read the above error msg

**Expected behavior**

It should just connect, like it does with 0.17

**Are you using NetBird Cloud?**

self-hosted, but it doesn't matter, I tried it also with the the cloud version, same error

**NetBird version**

0.28.9

**NetBird status -dA output:**

Daemon status: LoginFailed
Run UP command to log in with SSO (interactive login):
 netbird up 
If you are running a self-hosted version and no SSO provider has been configured in your Management Server,
you can use a setup-key:
 netbird up --management-url <YOUR_MANAGEMENT_URL> --setup-key <YOUR_SETUP_KEY>
More info: https://docs.netbird.io/how-to/register-machines-using-setup-keys

**Do you face any (non-mobile) client issues?**

Please provide the file created by `netbird debug for 1m -AS`.
We advise reviewing the anonymized files for any remaining PII.
Output:
Error: failed to up: up already in progress: current status LoginFailed

**Screenshots**

none

**Additional context**

none

**Comment by Gauss23** [comment]
Update: I exchanged the original gl-inet firmware with a vanilla OpenWRT installation. The newest Netbird package (atm 0.28.9) works perfectly.

**Comment by nazarewk** [comment]
FYI: this might be caused by using legacy `iptables` instead of new `nftables` on the system running Netbird.

**Comment by Gauss23** [comment]
Thanks for your hint. Looks like it’s the same problem indeed. I don’t want to go back to the stock firmware as the underlying  OpenWrt firmware is older and the vanilla one feels better. Maybe I‘ll get another one to test it.
Interestingly enough I had a look at the function, which is creating the connection and there is a differentiation between running as root or as a different user. as root it uses the new custom connect and as normal user the legacy way.
But I was not able to trigger this if statement. Seems like netbird up was just telling the daemon to connect, which was running as root.
Maybe those exports could have helped.
