### ISSUE TITLE
Unlimited setup key

### ISSUE THREAD

**Issue by tropnikovvl** [netbirdio/netbird#2523]
**Is your feature request related to a problem? Please describe.**
At the moment, the setup key can have a maximum duration of [1 year](https://docs.netbird.io/api/resources/setup-keys#create-a-setup-key).
This is not convenient if I have many peers that need to be updated later.
It would be great to be able to create an unlimited setup key for trusted peers.

**Describe the solution you'd like**
Provide the ability to make setup keys unlimited

**Additional context**
It was already discussed in this [issue](https://github.com/netbirdio/dashboard/issues/384) that the setup key duration can be changed manually in the database.

**Comment by mlsmaycon** [comment]
We've added support in the 0.31.0 version. Let us know if this resolves the problem.
