### ISSUE TITLE
Netbird website seems to be down

### ISSUE THREAD

**Issue by infocillasas** [netbirdio/netbird#2526]
The website seems to be down.
Am I the only one experiencing this ?
I'm using Brave Browser on Android

![Screenshot_20240903-210356_1](https://github.com/user-attachments/assets/29e6a207-6c75-4911-97e6-4ce664167ccb)

**Comment by mgarces** [comment]
Hi, thank you for opening this issue; from our side we are not observing downtime on the website.
Can you please test https://docs.netbird.io/ and validate that it's down for you also?

**Comment by infocillasas** [comment]
Hi
Looks like the website is back. It works now, but wasn't for a couple of days
