### ISSUE TITLE
Windows Client is missing file version string

### ISSUE THREAD

**Issue by florian-obradovic** [netbirdio/netbird#2557]
**Describe the problem**

This Windows client executables are missing the "file version" string
**To Reproduce**
Check file properties
![CleanShot 2024-09-08 at 14 43 23@2x](https://github.com/user-attachments/assets/2565d7e9-61a3-4da7-a7b7-986f06a8d0ab)

**Expected behavior**

**Are you using NetBird Cloud?**

Please specify whether you use NetBird Cloud or self-host NetBird's control plane.

**NetBird version**
v0.28.2

**NetBird status -dA output:**

**Additional context**
Windows MDM admins often use these file properties for install detection / presence of the app.

**Comment by florian-obradovic** [comment]
Please close, this is fixed at least in v0.28.9:
![CleanShot 2024-09-08 at 15 07 57@2x](https://github.com/user-attachments/assets/650aeb98-bc75-4c1b-a9d0-7a9f0dbed63f)

**Comment by mlsmaycon** [comment]
thanks for the feedback @florian-obradovic
