### ISSUE TITLE
Can't delete empty group due to revoked setup key ?

### ISSUE THREAD

**Issue by R-Nabil** [netbirdio/netbird#2561]
**Describe the problem**

Fairly simple : you create a setup-key assigned to a group. Then you revoke that setup key, and actually want to get rid of this group as well. However, you can't get rid of the group as the setup-key, even revoked, is considered part of the group. 

**To Reproduce**

See above

**Expected behavior**

Be able to delete group with unused setup keys.

**Are you using NetBird Cloud?**

Yes but similar in selfhosted.

**NetBird version**

Not sure if relevant here but : 0.28.9

**Screenshots**

<img width="1046" alt="image" src="https://github.com/user-attachments/assets/6b8deb97-cd50-490d-b647-9af2c4706223">

**Comment by R-Nabil** [comment]
I’ve tried to use the API to reassign the keys to a different group (temporary workaround).

Would this group eventually be deleted when those keys expired ? Can I expire them through the API ?

**Comment by pascal-fischer** [comment]
You don't need to reassign them, if you just clear the groups a key can belong to no group. Groups will not be deleted if the keys are revoked. You can expire keys over the API, yes.
