### ISSUE TITLE
cannot find any tags of netbirdio/relay in dockerhub

### ISSUE THREAD

**Issue by TheresaQWQ** [netbirdio/netbird#2562]
**Describe the problem**

as title, https://hub.docker.com/r/netbirdio/relay is an empty repository

**To Reproduce**

1. Go to https://hub.docker.com/r/netbirdio/relay
2. See error

**Expected behavior**

You can see the “latest” in tags

**Are you using NetBird Cloud?**

No, just self-hosted.

**NetBird version**

0.28.9

**NetBird status -dA output:**

not applicable

**Do you face any (non-mobile) client issues?**

not applicable

**Screenshots**

![image](https://github.com/user-attachments/assets/71a5c203-d07d-41e3-ba91-ebf0b66ec09e)

**Additional context**

not applicable

**Comment by pascal-fischer** [comment]
Hi @TheresaQWQ,
well, the reason for that is simple, there are no images published yet. We are currently developing a new relay service. This should be released within the next days and you should see some images there.

**Comment by Marcus1Pierce** [comment]
@TheresaQWQ It seems that when you posted, the image hadn't been published yet. Now, you can check that the tags are available, and you should be able to pull the image.

![Untitled](https://github.com/user-attachments/assets/132bd94b-0d7a-4444-a4a5-2f5958f96a60)
