### ISSUE TITLE
systemd is not correctly detected on rpm-ostree distros

### ISSUE THREAD

**Issue by M0Rf30** [netbirdio/netbird#2572]
**Describe the problem**

Installing netbird (0.29.0) on Fedora Atomic distros will continue to fail cause of undetected systemd session
This is caused by the first check of `isSystemd()` function that looks for `/run/systemd/` path, not detected in postinstall isolated environment and causing a `return false`.

Incorrect detection is also suggested by `/etc/init.d` error log reference, that doesn't exist on rpm-ostree distros.

See:
https://github.com/netbirdio/netbird/issues/1634

I opened https://github.com/netbirdio/service/pull/3

And will open a PR toward this repo to update the module

Tested on Fedora CoreOS 40.20240808.3.0

**Comment by jkrogers9862** [comment]
I can happily confirm I can install libvirt and network-scripts alongside netbird on Fedora Kinoite! Thank you for all your hard work!
