### ISSUE TITLE
Version 0.29.1 doesn't work on Windows

### ISSUE THREAD

**Issue by graphixillusion** [netbirdio/netbird#2585]
The just released 0.29.1 version has some issue on Windows: after installation it doesn't make the adapter and it  doesn't connect, so it doesn't work at all. Previous version 0.29.0 works good.

**Comment by mlsmaycon** [comment]
@graphixillusion can you please run it in a PowerShell window:

```shell
netbird debug log level trace
```

Then try the connection again after a while, copy the log file from `C:\ProgramData\netbird\client.log`, and share it with us?

**Comment by graphixillusion** [comment]
Well i reinstalled the 0.29.0 in meantime. Becouse of this problem https://github.com/netbirdio/netbird/issues/2217 i stopped netbird service, i did a cleanup of all the adapters made by previous installation in this location (Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\NetworkList\Profiles), then i restarted the netbird services and update again to 0.29.1 and now it works. I don't know what's happened before...

**Comment by mlsmaycon** [comment]
Got it. Ok, let us know if it happens again.
