### ISSUE TITLE
Issues with NGINX Proxy Manager and Authentik

### ISSUE THREAD

**Issue by jacksondarman** [netbirdio/netbird#2610]
**Describe the problem**

I have followed the advanced install guide to the best of my ability on my self-hosted VM using Authentik as my IDP and NGINX Proxy Manager as a reverse proxy. I had to change the dashboard port to 8080, but I imagine that shouldn't have broken much.

Upon going to the dashboard, I see a blank black screen with an orange loading symbol. The Firefox console is giving me a Cross-Origin Request Blocked error when trying to access the API at port 33073. This has been stumping me for the past day or so and would like some insight on where I should be looking. Thank you! :)

![image](https://github.com/user-attachments/assets/d8c624f5-8216-4401-ad5f-9d68f0436d23)

Here is what my advanced configuration for the proxy host in NGINX proxy manager looks like.

```
location / {
        proxy_pass http://10.0.0.141:8080;
    }
   location /signalexchange.SignalExchange/ {
        grpc_pass grpc://10.0.0.141:10000;
        #grpc_ssl_verify off;
        grpc_read_timeout 1d;
        grpc_send_timeout 1d;
        grpc_socket_keepalive on;
    }

    location /api {
        proxy_pass http://10.0.0.141:33073;
    }

    location /management.ManagementService/ {
        grpc_pass grpc://10.0.0.141:33073;
        #grpc_ssl_verify off;
        grpc_read_timeout 1d;
        grpc_send_timeout 1d;
        grpc_socket_keepalive on;
    }
```

**To Reproduce**

1. Follow the [advanced self-hosting guide](https://docs.netbird.io/selfhosted/selfhosted-guide), using Authentik as my IDP.
2. Configure NGINX proxy manager with the advanced config settings explained above.

**Expected behavior**

A new, ready to use instance of Netbird.

**Are you using NetBird Cloud?**

No

**Screenshots**

![image](https://github.com/user-attachments/assets/5f97866c-ee66-4fae-96bf-39417aef4c8f)
![image](https://github.com/user-attachments/assets/bc661a36-7dd5-4cb9-bf36-76f0e0c4bce9)
![image](https://github.com/user-attachments/assets/792b52ec-e010-4dbc-bac1-9030e19997a3)
![image](https://github.com/user-attachments/assets/de9a3b22-ad7e-4bbd-b697-6c4c93ad9522)

**Comment by jacksondarman** [comment]
Ended up figuring it out and am on the dashboard! The issue was that the API's traffic wasn't being routed to the correct place. (The API was accessing port 33073 on the path /users/api).

I managed to fix this problem by manually editing the docker compose file to remove the port number from the API endpoint.

**Comment by pedroponte** [comment]
Would you be able to add your final docker config and nginx config please? TY
@hackisonjd
