### ISSUE TITLE
Unable to login to Netbird after initial setup - with Authentik

### ISSUE THREAD

**Issue by bajijasti** [netbirdio/netbird#2622]
**Describe the problem**

I have the below setup:

- Domain Registered with Cloudflare
- Authentik is self-hosted at my home lab and accessible via Nginx Proxy Manager, which also in my home lab.
- For Netbird, created a new Ubuntu VM in VPS (Oracle Cloud) and a CNAME created in Cloudflare with VMs public ip (No NPM involved)

Every is set up according to the documented instructions in [Advanced Guide](https://docs.netbird.io/selfhosted/selfhosted-guide). But login to Netbird is stuck at loading page (after Authentication using Authentik is completed successfully). 

It does feel similar to this [issue](https://github.com/netbirdio/netbird/issues/2510) but cannot say as i am not sure if the setup also exactly the same.

Page is stuck while trying to access URL https://nb.domain.com:33073/api/users and gets connection refused. But i am not sure where is that connection is getting refused from and how to fix it. I did enable all ports as mentioned in document (both TCP and UDP) in Oracle Cloud.

![40551](https://github.com/user-attachments/assets/b2dcf19c-e4e1-43cf-8bbc-1c31a25f92e6)

Below is my setup.env
```
NETBIRD_DASHBOARD_TAG=""
NETBIRD_SIGNAL_TAG=""
NETBIRD_MANAGEMENT_TAG=""
COTURN_TAG=""
NETBIRD_RELAY_TAG=""

NETBIRD_DOMAIN="nb.domain.com"

NETBIRD_TURN_DOMAIN=""

NETBIRD_TURN_EXTERNAL_IP="VMs Public IP"

NETBIRD_AUTH_OIDC_CONFIGURATION_ENDPOINT="https://login.domain.com/application/o/netbird-oidc/.well-known/openid-configuration"
NETBIRD_AUTH_AUDIENCE="Client ID from Provider in Authentik"
NETBIRD_AUTH_CLIENT_ID="Client ID from Provider in Authentik"
NETBIRD_AUTH_SUPPORTED_SCOPES="openid profile email offline_access api"
NETBIRD_USE_AUTH0="false"
NETBIRD_AUTH_DEVICE_AUTH_PROVIDER="none"
NETBIRD_AUTH_DEVICE_AUTH_CLIENT_ID="Client ID from Provider in Authentik"
NETBIRD_AUTH_DEVICE_AUTH_AUDIENCE=$NETBIRD_AUTH_AUDIENCE
NETBIRD_AUTH_DEVICE_AUTH_SCOPE="openid"
NETBIRD_AUTH_DEVICE_AUTH_USE_ID_TOKEN=false
NETBIRD_IDP_MGMT_EXTRA_USERNAME="Netbird"
NETBIRD_IDP_MGMT_EXTRA_PASSWORD="service account password from Authentik"
NETBIRD_AUTH_PKCE_REDIRECT_URL_PORTS="53000"
NETBIRD_MGMT_IDP="authentik"
NETBIRD_IDP_MGMT_CLIENT_ID=$NETBIRD_AUTH_CLIENT_ID
NETBIRD_IDP_MGMT_CLIENT_SECRET=""
NETBIRD_DISABLE_LETSENCRYPT=false
NETBIRD_LETSENCRYPT_EMAIL="hello@domain.com"
NETBIRD_DISABLE_ANONYMOUS_METRICS=false
NETBIRD_MGMT_DNS_DOMAIN=netbird.selfhosted

NETBIRD_RELAY_DOMAIN=""

NETBIRD_RELAY_PORT=""
```

I just installed Netbird so everything is latest.

Did any one see this issue? Is it something to do with Netbird or Oracle Cloud restricting something or something between my homelab (Authentik) and Netbird (VPS)? 

Please help me to fix and move forward.

**Comment by mgarces** [comment]
this was solved on Netbird's Slack channel. 
It was related to the setting `NETBIRD_LETSENCRYPT_EMAIL` not being correctly configured.
Improvements in the documentation is needed, to insure users properly configure Let's Encrypt.

**Comment by mgarces** [comment]
closing this issue

**Comment by VignRaph** [comment]
For anyone searching the info here is a link to the conversation on slack: https://netbirdio.slack.com/archives/C02KHAE8VLZ/p1726744544049569

**Comment by cm0002** [comment]
> For anyone searching the info here is a link to the conversation on slack: https://netbirdio.slack.com/archives/C02KHAE8VLZ/p1726744544049569

Hi @VignRaph I'm running into this issue, but the Slack messages from this are behind the Slack "messages older than 90 days" paywall
