### ISSUE TITLE
Initial tray icon shown for netbird-ui

### ISSUE THREAD

**Issue by acarstoiu** [netbirdio/netbird#2649]
With the _netbird_ service being already **started**, when the _netbird-ui_ app is started, the shown tray icon is grayed-out (actually, desaturated). If I disconnect and then reconnect from the icon's menu, the icon becomes coloured as it should have been initially.

**Are you using NetBird Cloud?**

Yes.

**NetBird version**

0.29.4

**Screenshots**

![20240925_174544](https://github.com/user-attachments/assets/f0edad04-48dc-4bbd-baf3-d54d6b041c27)

**Additional context**

Note that I'm **not** using _libayatana-appindicator_.

Operating System: Gentoo Linux 2.15
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.4.0
Graphics Platform: Wayland

**Comment by mgarces** [comment]
hello @acarstoiu 


There are two different things, one is the `service` the other is the `connection`; Having Netbird's service running, does not grant connection. When you press "Connect" on the UI or do a `netbird up` on the CLI, that's when you get connected. Icon will remain grayed out as long as you are not connected. 

When you see the icon grayed out, what is the output of 
```
netbird status -d
```

**Comment by acarstoiu** [comment]
Oh, but I am connected all right. I have upgraded KDE Plasma to _6.1.5_ and it works as expected.
