### ISSUE TITLE
Not using defined DNS

### ISSUE THREAD

**Issue by choldi** [netbirdio/netbird#2651]
**Describe the problem**

Peers in group not using defined dns

**To Reproduce**

1. Create a group of peers. In my case "Convidats"
2. Define a peer (vm1) as exit node
3. Install dockerized pihole (dns server) in exit node. Expose port 53 tcp/udp 
4. Create a dns and assign to group "convidats" pointing to exit node, default port, no domains
5. Using a peer in group convidats with nslookup, server vm1 resolves address
6. requests from  peers in group convidats don't use dns server from vm1

**Expected behavior**

DNS request from peers of group convidads should go to defined DNS for group

**Are you using NetBird Cloud?**

Yes, using netbird cloud

**NetBird version**
0.28 android client
0.29.4 vm1 (server, dockerized)

**NetBird status -dA output:**

Server:

/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:45 /usr/local/bin/netbird up
   82 root      0:00 sh
  110 root      0:00 ps aux
/ # netbird status -dA
Error: failed to connect to daemon error: context deadline exceeded
If the daemon is not running please run: 
netbird service install 
netbird service start

**Do you face any (non-mobile) client issues?**
Not resolving dns correctly

**Screenshots**

**Additional context**

**Comment by mgarces** [comment]
Hi @choldi , 
just a quick check, is `pihole` ports 53 bounded to which IP? Can you please show the output for
```
netstat -tunelp | grep 53
```

Also, how are you assigning your Nameserver in the dashboard, and do you have a Policy that allows `Convidats` peers to access that TCP/UDP port for the `vm1` host?

**Comment by choldi** [comment]
Hello, thanks @mgarces 
pihole:
```
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      11438/docker-proxy
tcp        0      0 :::53                   :::*                    LISTEN      11444/docker-proxy
udp        0      0 0.0.0.0:53              0.0.0.0:*                           11458/docker-proxy
udp        0      0 :::53                   :::*                                11464/docker-proxy

```
The nameserver is in the dashboard but no policy defined. But from the client, I can connect the DNS (telnet to port 53)
