### ISSUE TITLE
MariaDB/MySQL Support

### ISSUE THREAD

**Issue by ismail0234** [netbirdio/netbird#2655]
**Is your feature request related to a problem? Please describe.**
- I would be very grateful if MySQL and MariaDB support is added.

**Additional context**
- MariaDB is a MySQL fork. So when one is added the other will work the same way. It would be very nice if adding both will not cause problems. If it is possible to add only 1 of them, I prefer MySQL. Most web servers use mysql.

**Comment by mgarces** [comment]
Thank you for your interest and feedback!

Support for MySQL/MariaDB/Percona is definitely something we have on our radar, and we understand how valuable it would be for many users. Currently, we need to conduct some internal testing and evaluate the integration thoroughly before we can commit to implementing this feature.

That being said, there isn’t a specific timeline or priority for this at the moment. We appreciate your patience and encourage you to keep an eye on future updates. [Contributions](https://github.com/netbirdio/netbird/blob/main/CONTRIBUTING.md) or suggestions from the community are always welcome as well!

**Comment by ismail0234** [comment]
I added this feature myself and it works very well. https://github.com/netbirdio/netbird/pull/2837
