### ISSUE TITLE
Missing instructions to provide existing SSL certificate

### ISSUE THREAD

**Issue by Fly7113** [netbirdio/netbird#270]
The guide to setup a self hosted instance of wiretrustee ([self-hosting.md](https://github.com/wiretrustee/wiretrustee/blob/main/docs/self-hosting.md)) is missing instructions to provide an already existing SSL certificate, which is possible since the merge of #122.

**Comment by mlsmaycon** [comment]
Hello, @Fly7113 , Sorry, this is not documented and for not getting back sooner. To configure the SSL on management, you can edit the management.json file and replace the CertFile and CertKey. 

We will document integration with a reverse proxy in future releases to make this setup easier.
