### ISSUE TITLE
GeoLite2 City Database Out of Date

### ISSUE THREAD

**Issue by RZRCDR** [netbirdio/netbird#2719]
The GeoLite2 City Database available for self-hosting is out of date.

Following the link: 
https://pkgs.netbird.io/geolocation-dbs/GeoLite2-City/download?suffix=tar.gz

provides GeoLite2-City_20240305

I confirmed that the MaxMind Database has an up-to-date geo entry for a specific IP, but the database provided by the link above is out of date and references the wrong geolocation.

Is this a limitation/delayed service for self-hosting?

Thank you for the great product.

**Comment by RZRCDR** [comment]
> I thought the self hosted version downloads from the maxmind hosted data on startup?

The data hosted by netbird has changed since I posted this issue. Earlier today the link gave me data for 2024-03-05, not I am receiving data for 2024-10-08.

Thank you for fixing the issue in the background.

**Comment by RZRCDR** [comment]
Closing the issue as resolved.

**Comment by mlsmaycon** [comment]
Thanks @RZRCDR we will see what is going on with the cache
