### ISSUE TITLE
Wrong checksum on yum packages from netbird repo

### ISSUE THREAD

**Issue by Foosec** [netbirdio/netbird#2724]
**Describe the problem**

Warning: Digest verification failed for file 'netbird_0.30.1_linux_amd64.rpm'
[/var/tmp/AP_0xXG0rRL/amd64/netbird_0.30.1_linux_amd64.rpm]

  expected 10e9e7e27300393388ec4ce606d5d0225f4f76c5
  but got  e7a0cb9f6be6855921d46d0e8a9178ae2bb6d6ee

**To Reproduce**

Update netbird from https://pkgs.netbird.io/yum/

**Expected behavior**

Not to have checksum verification issues

**NetBird version**

`0.30.1_linux_amd64`

**Comment by mlsmaycon** [comment]
Hi @Foosec @mihaTrajbaric we had an issue with the release workflow just now. We will review the packages upload and update you soon.

**Comment by Foosec** [comment]
Thank you for the quick update! i noticed jfrog throwing some internal errors, glad to hear its nothing serious :)
@mihaTrajbaric Hello fellow FRIjevec :)

**Comment by mihaTrajbaric** [comment]
Works, thanks :)

**Comment by Foosec** [comment]
Confirmed, works!
