### ISSUE TITLE
Dashboard doesn't load after logging in, API call to api.netbird.io/api/users pending forever

### ISSUE THREAD

**Issue by YuukiDE** [netbirdio/netbird#2759]
**Describe the problem**

Dashboard is stuck at loading animation after logging in. Doesn't work on Safari or Chromium on my Mac and doesn't work on Chrome Android. In the Chrome dev console I can see that an API call to https://api.netbird.io/api/users is pending forever.

**To Reproduce**
1. Open netbird.io
2. Click on login
3. log in with your account
4. after redirect see dashboard with infinite loading screen
6. Open Dev Console
7. Open Network tab
8. See API call pending forever

**Expected behavior**

Dashboard loading

**Are you using NetBird Cloud?**

Yes, I am using NetBird Cloud

**Additional context**

Tried with already existing and new account

**Comment by mgarces** [comment]
Hi there, 
Can you show us the output on the command line of:
```
dig api.netbird.io +short
ping api.netbird.io -c2
```
Also, what region/country are you trying to login from?

**Comment by YuukiDE** [comment]
I don't now if this helps but the preflight call to https://api.netbird.io/api/users (just before the fetch api call which I mentioned above) with Request Method: OPTIONS returns 204 No Content. Remote dress is also 35.186.199.111

**Comment by scrivoy** [comment]
Hi, just came across this Issue.
I have the same stuff going on at the moment.
The interesting thing I find is that with an older existing account I can log in without issues.

With a new account I cant login:
![grafik](https://github.com/user-attachments/assets/682b1119-4182-434d-895e-95fd4806f3f6)

Private session a bit different, but also stuck:
![grafik](https://github.com/user-attachments/assets/03e706fb-0549-49c7-ae17-4db4f73477f0)

Hope this helps.
Cheers!

**Comment by YuukiDE** [comment]
I get the same results as I stated before with a private window. My HAR file doesn't show the pending request (is this expected?) and I also sanitized it (removed cookies and authorization headers). Hope this helps. 
[infinite_dashboard_loading_sanatized_YuukiDE.har.zip](https://github.com/user-attachments/files/17441862/infinite_dashboard_loading_sanatized_YuukiDE.har.zip)

**Comment by mlsmaycon** [comment]
Hello folks,

Can you test again? We found an issue and fixed it. Thanks for reporting it.

**Comment by scrivoy** [comment]
Hi!
Yes, I can confirm, it works again, at least for me.
Nice, thanks!

**Comment by YuukiDE** [comment]
It works for me too. Thanks for fixing.
