### ISSUE TITLE
setup.env URL limit

### ISSUE THREAD

**Issue by chmis8000** [netbirdio/netbird#276]
the URL written by WIRETRUSTEE_AUTH0_AUDIENCE did not add / at the end.
The management side will not start.
I suggest you strengthen the documentation or improve the automatic judgment of the program.

**Comment by mlsmaycon** [comment]
Unfortunately, we can't enforce that, as the Auth0 audience value can be any string.

**Comment by mlsmaycon** [comment]
updated doc on #291
