### ISSUE TITLE
After upgrade (pull) to netbird on docker

### ISSUE THREAD

**Issue by freebs65** [netbirdio/netbird#2769]
After my upgrade... and a backup of course..
I can no longer log in using authentic... all my clients connect without issue.. I just can't log in to the dashboard any longer.
It will say "unauthorized"

I see no errors regarding logins in management log.

my "PKCEAuthorizationFlow": shows local url .. same as my older backed up json file.
I did a compare on old versus new.. they are the same... I also have the backup of db files.. I have not tried to restore them as I didn't want to break it further.

Only thing i noticed was an extra file after the upgrade... openid-confiugration.json.. my backup does NOT contain this file..

Latest version is showing.30.2

Any insights would be appreciated.

**Comment by mradermaxlol** [comment]
Same here. Were you able to get the dashboard to log users in again?
It seems like Authentik 2024.10 might have caused some issues, though rolling it back to 2024.8 didn't help in my case.

**Comment by freebs65** [comment]
my issue ended up being Firefox... i did a reset on it and authentik was fine...
i'm running 2024.10.0 without issue
