### ISSUE TITLE
Replacement server fails to connect

### ISSUE THREAD

**Issue by chmis8000** [netbirdio/netbird#277]
os:win10
ever connected to app.wiretrustee.com
and then connect to self-hosted instead:
wiretrustee up --setup-key xxx2EE52-xxA3-xx5F-xx8D-xxF17818CEF0 --management-url https://xxx.xxxx.xxx:33073
can't connect.
I found out that the reason is that config.json is not modified.
I deleted this file and re-executed the above command.
C:\ProgramData\Wiretrustee\config.json

**Comment by braginini** [comment]
Hi @chmis8000 
Good catch!

We have fixed this one in this PR https://github.com/wiretrustee/wiretrustee/pull/262

The fix will be included in the next release!
