### ISSUE TITLE
Windows, Linux and MacOS client open source code

### ISSUE THREAD

**Issue by Gifff69** [netbirdio/netbird#2774]
Hi, 

We can find open source code for ios-client and android-client from netbirdio repositories.
https://github.com/netbirdio/ios-client
https://github.com/netbirdio/android-client

However, we cannot find source code for Windows, Linux and MacOS client. Kindly advise the location. Thanks.

**Comment by mgarces** [comment]
hey @Gifff69 , all the source code used to build both Windows, Linux and macOS is found in this repo you just opened the issue. Take a look at our github-actions; the builds are signed externally for security purposes.

**Comment by Gifff69** [comment]
hi @mgarces, Thanks for reply.
However, I still cannot find it. Can share the link for reference? Thanks.
