### ISSUE TITLE
linux client : show better name

### ISSUE THREAD

**Issue by alfieV** [netbirdio/netbird#2796]
**Is your feature request related to a problem? Please describe.**
When using the Netbird client on linux, the system shows that you are connected to the vpn "wt0".

**Describe the solution you'd like**
it would be better if the name was the name of the network or at least Netbird

**Additional context**
![image](https://github.com/user-attachments/assets/f36e1fca-3568-4e13-ba44-5ba61b68a63c)
example from ubuntu 24.10 system overview

**Comment by mgarces** [comment]
Hey @alfieV , good news! 
On linux this is really easy to achieve. 
Either run: 
```
netbird up --interface-name netbird0
```
OR

edit interface name via "Advanced Settings" in the UI
<img width="592" alt="image" src="https://github.com/user-attachments/assets/c6403e59-a917-4128-b515-7819d6b1a721">

OR

```
netbird down
sudo systemctl stop netbird
sudo vim /etc/netbird/config.json #edit line with wt0 interface name
sudo systemctl start netbird 
```
I believe all these options will allow you to change interface name.

**Comment by alfieV** [comment]
i wasn't aware of these options, thank you very much
