### ISSUE TITLE
Severe performance impact when using Win11 RDP to another Win11 session on v0.30.3

### ISSUE THREAD

**Issue by rihards-simanovics** [netbirdio/netbird#2797]
# Describe the problem

I have two Windows 11 devices, one is OTG (On the Go) Device that can connect to the remote office PC that is part of the same VPN network. However, I've noticed that after upgrading the OTG, and office Device from `v0.30.2` to `v0.30.3`, the RDP performance suffered significantly; the office PC peer is running the same version of the client software.

## To Reproduce

Steps to reproduce the behaviour:
1. install and connect the Laptop and Desktop PC to the VPN client running v0.30.2.
2. Attempt to RDP from laptop to PC from the Internet and move the window around - the refresh speed and window movement should be relatively fast (assuming Laptop is connected to a strong and fast WiFi) ~ 30 - 35 fps when running [this video](https://www.youtube.com/watch?v=0RvIbVmCOxg) in full screen mode.
3. Upgrade __only laptop__ client to v0.30.3.
4. attempt to connect via RDP and do the same actions i.e. move window around - you should be able to notice a significant drop in performance compared to before ~ 0 - 2 fps at most

## Expected behaviour

No performance hit when using RDP after upgrading the client from v0.30.2 to v0.30.3.

## Are you using NetBird Cloud?

Self-Hosted however using a direct peer-to-peer connection

## NetBird version

`netbird v0.30.3`

## NetBird status -dA output:

`gws-rs-thinkpad (Laptop)`
```log
Peers detail:
 gws-rs-main-pc.node.anon-RGEjv.domain:
  NetBird IP: 100.90.54.18
  Public key: [redacted]
  Status: Connected
  -- detail --
  Connection type: Relayed
  ICE candidate (Local/Remote): relay/srflx
  ICE candidate endpoints (Local/Remote): 198.51.100.0:61996/198.51.100.1:17584
  Relay server address:
  Last connection update: 21 minutes, 19 seconds ago
  Last WireGuard handshake: 1 minute, 17 seconds ago
  Transfer status (received/sent) 22.7 MiB/5.6 MiB
  Quantum resistance: true
  Routes: -
  Latency: 15.3344ms

OS: windows/amd64
Daemon version: 0.30.2
CLI version: 0.30.2
Management: Connected to https://[redacted].domain:443
Signal: Connected to https://[redacted].domain:443
Relays:
  [stun:[redacted].anon-DfCsq.domain:3478] is Available
  [turn:[redacted].anon-DfCsq.domain:3478?transport=udp] is Available
Nameservers:
FQDN: gws-rs-thinkpad.node.anon-RGEjv.domain
NetBird IP: 100.90.29.243/16
Interface type: Userspace
Quantum resistance: true (permissive)
Routes: -
Peers count: 1/1 Connected
```

`gws-rs-main-pc (Office PC)`
```log
Peers detail:
 gws-de-1.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-7.node.anon-bVhjL.domain:
  [reduced]

 gws-rs-thinkpad.node.anon-bVhjL.domain:
  NetBird IP: 100.90.29.243
  Public key: [redacted]
  Status: Connected
  -- detail --
  Connection type: Relayed
  ICE candidate (Local/Remote): srflx/relay
  ICE candidate endpoints (Local/Remote): 198.51.100.0:17584/198.51.100.3:61996
  Relay server address:
  Last connection update: 24 minutes, 1 seconds ago
  Last WireGuard handshake: 1 minute, 59 seconds ago
  Transfer status (received/sent) 20.3 MiB/74.8 MiB
  Quantum resistance: true
  Routes: -
  Latency: 23.0477ms

 gws-uk-1.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-2.node.anon-bVhjL.domain:
  [reduced]

 gws-de-3.node.anon-bVhjL.domain:
  [reduced]

 gws-de-2.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-3.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-6.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-4.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-8.node.anon-bVhjL.domain:
  [reduced]

 gws-uk-5.node.anon-bVhjL.domain:
  [reduced]

OS: windows/amd64
Daemon version: 0.30.3
CLI version: 0.30.3
Management: Connected to https://[redacted].anon-Agryo.domain:443
Signal: Connected to https://[redacted].anon-Agryo.domain:443
Relays:
  [stun[redacted].anon-Agryo.domain:3478] is Available
  [turn:[redacted].anon-Agryo.domain:3478?transport=udp] is Available
Nameservers:
FQDN: gws-rs-main-pc.node.anon-bVhjL.domain
NetBird IP: 100.90.54.18/16
Interface type: Userspace
Quantum resistance: true (permissive)
Routes: -
Peers count: 12/12 Connected
```

## Do you face any (non-mobile) client issues?

please see comment below with a `debug.zip` file.

**Comment by rihards-simanovics** [comment]
here are the 0.30.3 debug logs for 5min as the RDP was extremely slow:
[debug.zip](https://github.com/user-attachments/files/17544872/debug.zip)

**Comment by Codixer** [comment]
While I don't have the debug logs with me. I can confirm the issue here, my **remote** server is currently on v0.30.2, I used .3 on my client device (Laptop) and my connection dropped so low that I coudn't even watch a video from Jellyfin. I was running with like, less then 1MB. 

I downgraded the laptop to .2 and this fixed it, something might have broken in between versions or some version incompatibility.

**Comment by rihards-simanovics** [comment]
> I was running with like, less then 1MB.

Yes, seems to be specific to 0.30.3, after downgrading back to 0.30.2 RDP on both laptop and PC, the framerate is back to normal 30~35 fps.

**Comment by briemann** [comment]
Seeing the same. Multiple reports of 0.30.3 users using RDP on windows 10/11 instances having issues. Downgrades to 0.30.2 confirmed as the fix.

**Comment by mlsmaycon** [comment]
@briemann @Codixer can you please share your output from the command below when facing the issue?

```
netbird status -dA
```

It can be from the client. Please share the node where the connection is affected so we check its connection type.

**Comment by rihards-simanovics** [comment]
@mlsmaycon I think at this point we can confidently say that 0.30.3 is the issue so perhaps a `netbird debug for 5m -AS` would be more relevant here so there is a more complete technical log?

**Comment by mlsmaycon** [comment]
@rihards-simanovics, The debug command will help a lot as it contains logs and the status output, but we still need confirmation on which peer you are testing to confirm the connection type and versions.

Could you also share the operating system between the peers and the test you've done? Or was it an RDP connection among Windows nodes with no routing peer in between?

**Comment by Codixer** [comment]
> @briemann @Codixer can you please share your output from the command below when facing the issue?
> 
> ```
> netbird status -dA
> ```
> 
> It can be from the client. Please share the node where the connection is affected so we check its connection type.

I'll be out of the house tomorrow, I'll be able to test it by then.

**Comment by roberthase** [comment]
I would also like to confirm that after updating to 0.30.3 the RDP performance is very bad.

netbird controller selfhosted: version 0.30.3
Ubuntu routing-peers in ha: Version 0.30.3
Windows Clients: version 0.30.3

RDS-Server with Windows Server 2016

**Comment by rihards-simanovics** [comment]
> The debug command will help a lot as it contains logs and the status output, but we still need confirmation on which peer you are testing to confirm the connection type and versions.

Hi @mlsmaycon, sure, sorry just thought you'd get the same from the bundled zip with debug.

> Could you also share the operating system between the peers and the test you've done? Or was it an RDP connection among Windows nodes with no routing peer in between?

Sure, both Office PC and Laptop in my case are running a Business Win. 11.
```Edition	Windows 11 Pro
Version 	23H2
Installed on	‎17/‎04/‎2023
OS build	22631.4391
Experience	Windows Feature Experience Pack 1000.22700.1047.0
```

The testing is the same as per my initial comment when opening the issue. Please See the steps under the `To Reproduce`. This testing was done on both local network and over internet.
With regards to connections: I've been doing remote work behind either NATed network i.e. cellular, or home network. There is no proxy of any sorts and the connection was not routed through any exit nodes. It was/is a direct connection from peer `gws-rs-thinkpad.node.anon-RGEjv.domain` to peer `gws-rs-main-pc.node.anon-RGEjv.domain`, again see the `NetBird status -dA output` for that one, I will update the comment with clearer labels for peers.

**Comment by Codixer** [comment]
After reinstalling .3, it did not seem to replicate anymore. I am unable to reproduce the issue at this time. I will report back if it does happen again.

**Comment by mlsmaycon** [comment]
Hello folks, we found the issue that was causing slow speeds. Can you please test the 0.31.0 version?

**Comment by rihards-simanovics** [comment]
> Hello folks, we found the issue that was causing slow speeds. Can you please test the 0.31.0 version?

Thanks! Will test on Monday as I don't travel over the weekends.

**Comment by rihards-simanovics** [comment]
can confirm, when using RDP along with version 0.31.0 does indeed fixes the issue with slow connection! 

# Thank you Netbrid Team!

**Comment by roberthase** [comment]
Seems to be fixed, thanks for the quick update.

**Comment by rihards-simanovics** [comment]
@roberthase, @Codixer, @briemann, do any of you use web login (i.e. Microsoft Login) to authenticate? I have a wired issue where the "Securing Remote Session" takes for ever though after connecting the speed is fine. I never really measured but it usually is stuck on "Securing remote session" for a solid minute or two. I would open a new issue about this here, but I don't know if it's related to Netbird or just my setup, That said, on version 0.27.x it used to be fast, around a few seconds.

**Comment by roberthase** [comment]
this is something i experienced on my windows pc at home (self-registered with entra online idd), but never on our work-laptops (setup-key), so i thought this related to some update/security setting on my device.

i can test this with another vpn client and report back.

**Comment by Codixer** [comment]
> @roberthase, @Codixer, @briemann, do any of you use web login (i.e. Microsoft Login) to authenticate? I have a wired issue where the "Securing Remote Session" takes for ever though after connecting the speed is fine. I never really measured but it usually is stuck on "Securing remote session" for a solid minute or two. I would open a new issue about this here, but I don't know if it's related to Netbird or just my setup, That said, on version 0.27.x it used to be fast, around a few seconds.

I experience this on my phones, it takes a solid minute for other devices to popup (Might be related to #2158) but not sure. Apart from that, most of my devices connect instantly. At most 10 seconds.

**Comment by roberthase** [comment]
@rihards-simanovics 

hi there, connecting to a remote session with forticlient was indeed quicker.
i ended up connecting to range of different systems and only one was taking longer on "securing remote session".

i cleared the rdp-cache, like mentioned on this website : https://tachytelic.net/2019/01/clear-rdp-cache/ , then rebooted a few times to test and "securing remote sessions" took only 3-5 seconds each time.

**Comment by rihards-simanovics** [comment]
Hey @roberthase thanks. Though I don't think this is the case here. I've been using node's hostname to RDP into it, in this case `gws-rs-main-pc.node.anon-RGEjv.domain`, but after I went back to its IP, "securing the connection" step in Windows RDP client got fast as expected. My assumption is the address resolution is somehow messing with the speed.

**Comment by rihards-simanovics** [comment]
> I've been using node's hostname to RDP into it, in this case gws-rs-main-pc.node.anon-RGEjv.domain, but after I went back to its IP, the "securing the connection" step in the Windows RDP client got faster as expected. My assumption is the address resolution is somehow messing with the speed.

@mlsmaycon, do you have any idea what this could be?

If this has the potential to be a Netbird issue, I'd like to open an issue so it can be tracked.

Just to note that on my DNS server side, `node.anon-RGEjv.domain` has `A` and `AAAA` records pointing to the Netbird Management server IPs, and `*.node.anon-RGEjv.domain` wildecard are canonically linked to `node.anon-RGEjv.domain` via a CNAME record.

**Comment by b00nish** [comment]
> I have a wired issue where the "Securing Remote Session" takes for ever though after connecting the speed is fine. I never really measured but it usually is stuck on "Securing remote session" for a solid minute or two. 

@rihards-simanovics 

Did you ever get to the bottom of this issue?

We see the same behaviour when computers/laptops with Netbird connect to our RDS server. The step "securing remote session" takes about 30 to 90 seconds but after this the connection works well.

It doesn't matter if we connect using the Netbird IP, the Netbird FQDN or the Hostname.

On the local network or using a VPN client that the firewall vendor provides, the same RDP connections happen instantly.

**Comment by rihards-simanovics** [comment]
> > I have a wired issue where the "Securing Remote Session" takes for ever though after connecting the speed is fine. I never really measured but it usually is stuck on "Securing remote session" for a solid minute or two.
> 
> [@rihards-simanovics](https://github.com/rihards-simanovics)
> 
> Did you ever get to the bottom of this issue?
> 
> We see the same behaviour when computers/laptops with Netbird connect to our RDS server. The step "securing remote session" takes about 30 to 90 seconds but after this the connection works well.
> 
> It doesn't matter if we connect using the Netbird IP, the Netbird FQDN or the Hostname.
> 
> On the local network or using a VPN client that the firewall vendor provides, the same RDP connections happen instantly.

Basically, upgrade the client on both machines, or turn off the Rosenpass if you have it on. My entire organisation has now migrated to Linux, so RDP is no longer an issue. However, if you are still experiencing sluggish performance, I recommend upgrading everything related to Netbird, Clients, and the management server. Sometimes there are network-related issues, so try using your mobile phone hotspot.
