### ISSUE TITLE
netbird install client http url error 

### ISSUE THREAD

**Issue by JamesBonddu** [netbirdio/netbird#2803]
**Describe the problem**

netbird install client http url bug

**To Reproduce**

Linux install script http url error 

**Expected behavior**

correct linux http url

**Are you using NetBird Cloud?**

self-host NetBird's control plane.

**NetBird version**

server
0.30.2

client
0.30.3

**Screenshots**

<img width="759" alt="cba05e9eb9eef77f76aafce38c670b8" src="https://github.com/user-attachments/assets/134c2f94-e53f-4c81-a3e4-3adfcaf5d51e">

```sh
root@node1:~/dashboard# netbird up --management-url https://xxx.com --admin-url https:://xxx.com



Error: login backoff cycle failed: rpc error: code = Unknown desc = getting device authorization flow info failed with error: context deadline exceeded
```

**Comment by heisbrot** [comment]
Hey @JamesBonddu,

thanks for the information!
The typo has been fixed in this [PR](https://github.com/netbirdio/dashboard/pull/418).

You can update the dashboard to [v2.6.2](https://github.com/netbirdio/dashboard/tree/refs/tags/v2.6.2)
