### ISSUE TITLE
Exit node not working

### ISSUE THREAD

**Issue by netandreus** [netbirdio/netbird#2824]
**Describe the problem**

After adding exit peer route Internet access disappears.

**To Reproduce**

I have two peers:
- first one (peer-1) Windows VM I use for testing (whatismyipaddress.com)
- second (peer-2) Ubuntu 18.04 VM I use as an Exit Peer. I made distribution group (Exit-TR) for it.

Before adding "Exit-TR" Distribution Group to peer-2 I have an Internet access.

<img width="877" alt="Screenshot 2024-11-01 at 09 49 08" src="https://github.com/user-attachments/assets/59e645ce-ae78-4d82-916c-ce7c8f32f578">

When I added Distribution Group to the first peer the route arrives, but the Internet stops working.

<img width="877" alt="Screenshot 2024-11-01 at 09 53 03" src="https://github.com/user-attachments/assets/48b32c19-619f-4715-8e19-7ce6d5ed4da9">

**Expected behavior**

Routing through the exit peer.

**Are you using NetBird Cloud?**

I use self-hosted version of NetCloud.

**NetBird version**

netbird 0.30.3

**Do you face any (non-mobile) client issues?**

Please provide the file created by `netbird debug for 1m -AS`.
We advise reviewing the anonymized files for any remaining PII.

Here are the logs:

[netbird.debug.881320298.zip](https://github.com/user-attachments/files/17596595/netbird.debug.881320298.zip)

**Comment by mlsmaycon** [comment]
@netandreus can you please test with 0.31.0 and if the problem persists, run the `netbird debug for 1m -AS` again?

**Comment by netandreus** [comment]
@mlsmaycon should I update server only (amangement etc), client or all of them?

**Comment by mlsmaycon** [comment]
you can update the routing peer and the routing client.

**Comment by deemkeen** [comment]
i've experienced exactly the same problem a few times - after upgrading netbird on my exit nodes, all non-netbird internet requests don't work anymore, till i disable the exit nodes

**Comment by serhansevim** [comment]
Having the same issue even with the Netbird Enterprise account. There is a definitive bug around windows clients. We made numerous tests and for some reason exit node bombs the clients with UDP packets and choke them until they get disconnected. During this time **[kworker/1:3+wg-crypt-wt0]** process at the exit node hits %100 CPU.

**Comment by mlsmaycon** [comment]
@serhansevim can you share the output from the command below? 

```shell
netbird debug for 1m -S
```

**Comment by mlsmaycon** [comment]
@netandreus we will check your logs and give you a feedback soon. It seems like we have a constant route update in the logs that needs more time to investigate. In the mean time, can you test both, routing peer and windows client running on NetBird v0.28.9? 

On ubuntu you can run:
```shell
apt-get install netbird=0.28.9
``` 
the windows installer is: https://github.com/netbirdio/netbird/releases/download/v0.28.9/netbird_installer_0.28.9_windows_amd64.exe

**Comment by netandreus** [comment]
@mlsmaycon yes, I confirmed that it works fine when version ```0.28.9``` are on both routing peer and client peer.

<img width="1850" alt="Screenshot 2024-11-06 at 09 56 16" src="https://github.com/user-attachments/assets/7a0dd88d-c73d-4168-80ff-401ba36be57a">

**Comment by eoksum** [comment]
I can also confirm when version 0.28.9 is used on Windows clients and 0.31.0 on exit node, everything works fine.
It seems latest Netbird client is messing with something on Windows but I'm not sure.

**Comment by netandreus** [comment]
@eoksum In my case it only works when version ```0.28.9``` installed on both peers (exit node and client node). When I'm updated netbird from ```0.28.9``` to ```0.31.0``` on the exit node Internet access disappears.

**Comment by mgarces** [comment]
hi @netandreus, would it be possible to test with release [0.31.1](https://github.com/netbirdio/netbird/releases/tag/v0.31.1)?

**Comment by netandreus** [comment]
Good morning, @mgarces !

Windows (client peer):
```
https://github.com/netbirdio/netbird/releases/download/v0.31.1/netbird_installer_0.31.1_windows_amd64.exe
```

Ubuntu (routiong peer):
```
sudo apt-get update
sudo apt-get install netbird=0.31.1
```

Yes, it's working well now! 🎉🎉🎉
Thank you very much!
