### ISSUE TITLE
Error: context deadline exceeded on macOS

### ISSUE THREAD

**Issue by ykhedar** [netbirdio/netbird#290]
HI there, while adding a macos peer to the network, i get the following error all the time. 

```bash
Error: context deadline exceeded
Usage:
  wiretrustee up [flags]

Flags:
  -h, --help   help for up
......
```

Tries with the 0.5.1 binaries and brew install on two different systems with same error.

It works fine on an Ubuntu20.04 Machine though.

Thanks,
khedar

**Comment by braginini** [comment]
Hi @ykhedar 
Could you please send us your log file?
/var/log/wiretrustee/client.log

And how did you exactly run the up command?

**Comment by ykhedar** [comment]
I simply use the command specified in the Add Peer instruction on the Dashboard:
`sudo wiretrustee up --setup-key SETUPKEY`

The log contains the following:

```bash
time="2022-04-03T23:25:56+02:00" level=error msg="failed to connect to service CLI interface context deadline exceeded"
time="2022-04-03T23:26:31+02:00" level=error msg="failed to connect to service CLI interface context deadline exceeded"
time="2022-04-03T23:30:07+02:00" level=error msg="failed to connect to service CLI interface context deadline exceeded"
time="2022-04-04T12:29:17+02:00" level=error msg="failed to connect to service CLI interface context deadline exceeded"
time="2022-04-04T12:53:10+02:00" level=error msg="failed to connect to service CLI interface context deadline exceeded"
```

**Comment by braginini** [comment]
I think that local wiretrustee service isn't running.

Could you please check the step number 4 from here?
https://github.com/netbirdio/netbird#macos

You will basically need to run:
`sudo wiretrustee service install` followed by `sudo wiretrustee service start`

**Comment by ykhedar** [comment]
That was it! I was following the instructions from the UI which did not have this step :(.

Thanks a lot.

**Comment by braginini** [comment]
> That was it! I was following the instructions from the UI which did not have this step :(.
> 
> Thanks a lot.

Our bad. Sorry!
I will add these steps there
