### ISSUE TITLE
Custom DNS support.

### ISSUE THREAD

**Issue by Cikaros** [netbirdio/netbird#2943]
Administrators can publish custom DNS resolution rules based on groups, and clients will accept DNS resolution according to the group rules and write them into the hosts file.

**Comment by Codixer** [comment]
It could be me, but isn't this somewhat already a feature?

**Comment by Cikaros** [comment]
I'm sorry I didn't make it clear, but at the moment you can only have one domain name by setting the client name, but only one

**Comment by Cikaros** [comment]
I would like to have multiple domain names.

**Comment by Codixer** [comment]
And I think that's possible to?

**Comment by Cikaros** [comment]
How should I proceed, please?

**Comment by Cikaros** [comment]
I understand, are you referring to using a custom DNS server to achieve support for more domain name mappings? I am hesitant to open another DNS server.

**Comment by Codixer** [comment]
As far as I know, you can create a server/endpoint in your env and assign it an internal ip only. THen make that your dns server for the domains you wanna use. So yeah.

**Comment by Codixer** [comment]
It's what I do for my infra.

**Comment by mgarces** [comment]
@Cikaros  can you clarify what are you trying to achieve? What is the issue?

**Comment by hurricanehrndz** [comment]
This can easily be done with coredns and again like @Codixer it is something I do in my own environment and outside the scope of this project
