### ISSUE TITLE
Unable to connect 2 devices

### ISSUE THREAD

**Issue by pippo73** [netbirdio/netbird#2974]
**Describe the problem**

I'm trying to use netbird for the first time.
I've tried to install it on a linux machine and a windows and on the 2 devices everything seems ok
the problem is that I cannot interact on device with the other

**To Reproduce**

install netbird on both device.
try to ping or to ssh and nothing happens

**Expected behavior**

the 2 devices should see each other 

**Are you using NetBird Cloud?**

Yes, I'm using NetBird Cloud

**NetBird version**
```

`netbird version`
windows > netbird version
0.32.0
linux # netbird version
0.33.0

**NetBird status -dA output:**

linux
# netbird status -d 
Peers detail:
 miportatile.netbird.cloud:
  NetBird IP: 100.x.x.x
  Public key: xxxxxxx
  Status: Connected
  -- detail --
  Connection type: P2P
  ICE candidate (Local/Remote): host/srflx
  ICE candidate endpoints (Local/Remote): 192.168.x.x:51820/x.x.x.x:39598
  Relay server address: rels://streamline-es-mad1-1.relay.netbird.io:443
  Last connection update: 55 minutes, 3 seconds ago
  Last WireGuard handshake: -
  Transfer status (received/sent) 78.6 KiB/50.3 KiB
  Quantum resistance: false (connection might not work without a remote permissive mode)
  Routes: -
  Latency: 17.950642ms

OS: linux/amd64
Daemon version: 0.33.0
CLI version: 0.33.0
Management: Connected to https://api.netbird.io:443
Signal: Connected to https://signal.netbird.io:443
Relays: 
  [stun:stun.netbird.io:5555] is Available
  [turns:turn.netbird.io:443?transport=tcp] is Available
  [rels://streamline-es-mad1-1.relay.netbird.io:443] is Available
Nameservers: 
  [1.1.1.1:53, 8.8.8.8:53] for [.] is Available
FQDN: myname.netbird.cloud
NetBird IP: 100.x.x.x/16
Interface type: Kernel
Quantum resistance: false
Routes: -
Peers count: 1/1 Connected
==========================================
windows
> netbird status -d
Peers detail:
 mc-wuwuwu.netbird.cloud:
  NetBird IP: 100.x.x.x+1
  Public key: xxxx
  Status: Connected
  -- detail --
  Connection type: P2P
  ICE candidate (Local/Remote): srflx/srflx
  ICE candidate endpoints (Local/Remote): x.x.x.x:39598/x.x.x.x:51820
  Relay server address: rels://streamline-es-mad1-1.relay.netbird.io:443
  Last connection update: 19 minutes, 57 seconds ago
  Last WireGuard handshake: -
  Transfer status (received/sent) 1.3 KiB/30.0 KiB
  Quantum resistance: false (connection won't work without a permissive mode)
  Routes: -
  Latency: 34.1591ms

OS: windows/amd64
Daemon version: 0.32.0
CLI version: 0.32.0
Management: Connected to https://api.netbird.io:443
Signal: Connected to https://signal.netbird.io:443
Relays:
  [stun:stun.netbird.io:5555] is Available
  [turns:turn.netbird.io:443?transport=tcp] is Available
  [rels://streamline-de-fra1-0.relay.netbird.io:443] is Available
Nameservers:
  [1.1.1.1:53, 8.8.8.8:53] for [.] is Available
FQDN: miportatile.netbird.cloud
NetBird IP: 100.x.x.x/16
Interface type: Userspace
Quantum resistance: true
Routes: -
Peers count: 1/1 Connected
```

Only one policy rule that allows all to connect with all

**Additional context**

> ping linux.netbird.cloud

Esecuzione di Ping mc-wuwuwu.netbird.cloud [100.109.x.x] con 32 byte di dati:
Richiesta scaduta.
Richiesta scaduta.
Richiesta scaduta.
Richiesta scaduta.

Statistiche Ping per 100.109.40.159:
    Pacchetti: Trasmessi = 4, Ricevuti = 0,
    Persi = 4 (100% persi),

The IP is correct but ping or ssh does not work at all in both directions :-(

what else could I give you? Did I miss something?

**Comment by mgarces** [comment]
Hello @pippo73 , can you run `netbird debug for 5m -AS` on both peers and attach the generated zip files for our team to take a look? Before, could you update your Windows peer to `0.33.0` please? Also, no need to delete NetBird's IP address from the post, since these IP are part of a private subnet and there is no risk in sharing them.

**Comment by pippo73** [comment]
Windows updated (would be nice a notification/auto-update function) 
Attached you can find both files
[linux.netbird.debug.1496978571.zip](https://github.com/user-attachments/files/17978522/linux.netbird.debug.1496978571.zip)
[windows.netbird.debug.2904953747.zip](https://github.com/user-attachments/files/17978524/windows.netbird.debug.2904953747.zip)

**Comment by pippo73** [comment]
Did I?
Don't know even how I did it. How can I disable it?
For me the only difference is that the linux server is set up with the key, the windows with the login process.

**Comment by mgarces** [comment]
hey @pippo73 sorry I missed you had enabled Rosenpass on Windows. Please disconnect your peer and then disable it in the menu. 
<img width="595" alt="image" src="https://github.com/user-attachments/assets/5357fb8b-21f1-4c83-ad3d-2f21692a3b3f">
After you untick that option, click connect  and test it again please

**Comment by pippo73** [comment]
Thank you. Now it works :-)
