### ISSUE TITLE
How config a windows peer as a Routing Peer? and is that possible?

### ISSUE THREAD

**Issue by lazyfatcat** [netbirdio/netbird#3020]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mohamed-essam** [comment]
According to the [docs](https://docs.netbird.io/how-to/routing-traffic-to-private-networks#routing-group):

> Only Linux OS machines can be assigned as routing peers.

It should be _technically_ possible to have Windows machines as routing peers, there is already an issue for this here: https://github.com/netbirdio/netbird/issues/1248
