### ISSUE TITLE
how to configure coturn with --use-auth-secret in management.json

### ISSUE THREAD

**Issue by chefboyrdave21** [netbirdio/netbird#3090]
I saw in one of your issues - you stated you could configure netbird with --use-auth-secret in replace of the user/pass in the turnconfig :

    "TURNConfig": {
        "TimeBasedCredentials": false,
        "CredentialsTTL": "12h0m0s",
        "Secret": "secret",
        "Turns": [
            {
                "Proto": "udp",
                "URI": "turn:turn.some.thing.it:3478",
                "Username": "self",
                "Password": "xxxxxxx"
            }
        ]
    },

You stated to look at the .tmpl file - I can't seem to figure out what it should look like. I have an existing coturn server on the host - as you know its a pain to try to run multiple instances. I'd like to reuse what i have in place but it uses:

--use-auth-secret
--static-auth-secret=xxxxx

in the turnserver.conf file 

I'd be so grateful if you could give me the entry - i suppose i could try to plugin in some stuff but seems like a wast of time to not just ask! thank you friend!

**Comment by mlsmaycon** [comment]
Hello, @chefboyrdave21, you can do that by enabling time-based credentials and setting a secret. The CredentialsTTL will rotate the secrets. The Username and Password won't matter in this setup, but they can't be empty. See example below:

```
"TURNConfig": {
    "TimeBasedCredentials": true,
    "CredentialsTTL": "12h0m0s",
    "Secret": "<SECRET>",
    "Turns": [
        {
            "Proto": "udp",
            "URI": "turn:turn.some.thing.it:3478",
            "Username": "self",
            "Password": "xxxxxxx"
        }
    ]
},
```
