### ISSUE TITLE
calling netbird inside the docker container

### ISSUE THREAD

**Issue by itsalljustdata** [netbirdio/netbird#371]
I'm using the "netbirdio/netbird" app on my unRAID servers (because, unRAID - it's just easier)...

This is working splendidly giving me connectivity to my servers running elsewhere, however....

With the new SSH server functionality, I need to be able to execute the netbird executable directly, but it's cracking the whoops..

`root@beast:/mnt/user/appdata/netbird# docker exec -it netbird /go/bin/netbird ssh 123.123.123.123
Error: failed to connect to daemon error: context deadline exceeded
If the daemon is not running please run:
netbird service install
netbird service start
`

This is (presumably) because netbird isn't running as a daemon in the container - just running as a "active" program.

Any thoughts as to getting this to work?

I'd rather get a fully working docker solution up and going if possible. 

Or are you fellas open to the idea of re-working the container to make it run as a daemon? I'm happy to do it, I just need to find the time.

**Comment by braginini** [comment]
Hey @itsalljustdata 
Indeed you observations are correct - netbird runs in foreground when run from docker. Just a few days ago we were discussing internally how we could make it run as a daemon. Would love to get some support on that! Ping me or Maycon on slack - happy to discuss it.

As for the SSH command, it checks whether daemon is running... I wil check if it is actually necessary.

**Comment by braginini** [comment]
@itsalljustdata fix is available in the latest release
https://github.com/netbirdio/netbird/releases
