### ISSUE TITLE
Possible to set nameservers to connecting peers

### ISSUE THREAD

**Issue by fang64** [netbirdio/netbird#373]
I am aware DNS is on the roadmap, but in the mean time would it be possible to privately provide nameservers to the client or configure the client to accept a nameserver? 

I don't know if this would be appropriate since objectively it seems you already have a plan. Although I do think it would be useful to operate a custom DNS server even if it isn't explicitly tied to the clients themselves. Unless the feature is already there and I am not seeing it?

**Comment by mlsmaycon** [comment]
Hi @fang64, this feature is planned as part of our routing support feature coming up. The difference between this and our private DNS plan is that the later will resolve NetBird IPs in your network to domain names without need for manual mapping from the users. 

The routing feature is planned for this month, stay tunned!

**Comment by dehoej** [comment]
Routing support has now been added, but i do not se anything in the documentation regarding this topic?
Is it yet to be implemented?

For now i set specific nameservers for wt0 with resolvectl, but id does not seem like the correct solution.

**Comment by pnowy** [comment]
@mlsmaycon any update regarding the DNS forwarding (not internal DNS). That would be a great feature (and with native WireGuard working almost out-of-the-box with client DNS settings provided).

**Comment by pnowy** [comment]
@dehoej thanks for the script but I mostly looking the solution on the client side and not everyone using the linux, etc.

That's quite easy with WireGuard when you generating DNS entry for config file but haven't seen that kind of option on NetBird (yet!) 😄

**Comment by dehoej** [comment]
@pnowy Yeah i know, and that it why i use this workarround for my Ubuntu Desktop.

**Comment by mlsmaycon** [comment]
Hello @pnowy, we are working on the feature right now, our latest estimation is that it will be available by the end of next week.

**Comment by pnowy** [comment]
Will be happy to test this feature 😄

**Comment by pnowy** [comment]
@fang64 @mlsmaycon I think this ticket could be closed. I've tested this on self-deployment version and works on.

I notice just only small delay when connecting (usually takes 2-3 minutes locally until my MacOS machine in browser takes DNS into account) but except that the DNS works very nice.

**Comment by fang64** [comment]
@pnowy I see they've added support I suspeect this doesn't solve everyone's situation maybe they need to extend the netbird client for windows hosts to run a local resolver with forwarding. So at least Linux/Mac land it's solved.

**Comment by pnowy** [comment]
@fang64 I've check on Windows VM and DNS worked nice. The only issue was missing config added to Windows firewall (the best way is to add the Netbird to trusted apps regarding the outgoing traffic). I've extended Windows docs about this: https://netbird.io/docs/getting-started/installation#windows

**Comment by fang64** [comment]
@mlsmaycon @pnowy I see yes I've confirmed testing in a VM, I see. I'll Close it.
