### ISSUE TITLE
How do I network over MPLS?

### ISSUE THREAD

**Issue by iamshiyan** [netbirdio/netbird#392]
How do I network over MPLS?

**Comment by mlsmaycon** [comment]
Hi @iamshiyan, It should work as regular MPLS traffic, the encrypted packets from one peer would receive the MPLS label and follow its path to the peer on the other side of your MPLS network.

Do you have any specific questions in this regard?

**Comment by isecwaypro** [comment]
Also, do you have a specific time frame for when your routing and trunking will be available?

**Comment by isecwaypro** [comment]
@mlsmaycon
