### ISSUE TITLE
Can local Mesh VPN Node subnet's be included in advertisements to other Mesh VPN Nodes?

### ISSUE THREAD

**Issue by bmullan** [netbirdio/netbird#395]
Some of the other Mesh VPN tools I've used (VPNCloud & Nebula for 2 examples) support the ability for the Config for a Node in the Mesh to specify local Subnets to include in Peer advertisements.

With Containers (Docker, LXD etc) this is very useful in that the Mesh VPN has its Endpoint on the Host but each Container(s) on that Host (which are on their own 10.x.x.x non-routable subnet) can be reachable over the Mesh VPN also.

I hope I'm explaining the above functionality well enough.

Does Netbird support something like this?

thanks for any info

Brian

**Comment by braginini** [comment]
@bmullan 
Hey Brian. 
Thank you for trying out NetBird :) I think that what you are talking about is a "router node" feature that @mlsmaycon started working on already. Not yet supported. 
@mlsmaycon other thoughts?

**Comment by bmullan** [comment]
The term "Router Node" makes me think we are both talking about the same
capability!

Thanks.

Brian

**Comment by braginini** [comment]
We will let you know @bmullan once delivered!

**Comment by bmullan** [comment]
@mlsmaycon 
@braginini 

I was following the work you were doing in this "router node" feature that might enable advertisement of Container ... LXD (or Docker) subnets across the Mesh.

It seemed like you were completing work on it so I was wondering if its been released and if there was documentation about how to utilize it yet?

Thanks
Brian

**Comment by mlsmaycon** [comment]
Hello @bmullan we've completed the first step for the feature, it includes:

- Route private networks via one or multiple peers
- Masquerade traffic from NetBird network to those networks

With these features, you are able to route traffic with linux peers, including containers (requires --privileged flag to enable ip forwarding)

The documentation is: https://netbird.io/docs/how-to-guides/network-routes

We are now working on DNS and after that will return to this feature to add:
- Routing group tags, to distribute routes only to a set of peers
- Internet gateway like routing. Basically routing all traffic of peer via another peer (0.0.0.0/0)

**Comment by bmullan** [comment]
@mlsmaycon @braginini 

I been implementing/using Netbird.  

However, _[I still have not found if/how this might be implemented?](https://github.com/netbirdio/netbird/issues/395#issuecomment-1261811121)_

its been a couple years since I asked this question.  The link in the previous comment no longer works.

Is there any Guide or Youtube Video that talks about how to do this?

Thanks 
Brian
