### ISSUE TITLE
Whether to support TCPOnly when udp is restricted by the carrier.

### ISSUE THREAD

**Issue by iamshiyan** [netbirdio/netbird#414]
Whether to support TCPOnly when udp is restricted by the carrier.

**Comment by mlsmaycon** [comment]
it is possible to support TCP only for connections that require Relay (the case you described), we might need to adjust a bit the agent

**Comment by vampywiz17** [comment]
@mlsmaycon 

Please add it. It would be good a method that work similar way with DERP server. It is the only relay server that work every place that i test it! (i think the reason is the TLS/HTTPS working method)

**Comment by braginini** [comment]
@iamshiyan 
It is out there already! We have a single TCP relay running and listening on port 443, but we will deploy more.
Works with our cloud version at https://app.netbird.io/.
Self-hosted is supported as well.

**Comment by fernandoenzo** [comment]
> @iamshiyan It is out there already! We have a single TCP relay running and listening on port 443, but we will deploy more. Works with our cloud version at https://app.netbird.io/. Self-hosted is supported as well.

How can this be self-hosted? I mean, I have a coturn server listening in UDP/TCP and I changed my management.json "Proto" to "TCP" in "Stun" and "Turn" sections, but this doesn't work when I block all UDP traffic with my firewall (it works, however, in unblocked UDP traffic). So, what am I doing wrong?

**Comment by mlsmaycon** [comment]
@fernandoenzo @iamshiyan, Sorry for not getting back sooner. You can configure a TCP relay by adding a setting like the in your management.json Turn config:

```json
        "Proto": "tcp",
        "URI": "turn:turn.example.com:3472?transport=tcp",
```        

I will close this issue for now, please open a new one in case you want further assistance.

**Comment by xiaolei0125** [comment]
@mlsmaycon   Does netbird support  udp relay?
if I set  no-udp and  no-udp-relay in coturn turnserver.conf,  the netbird get error
```
netbird status -d
Relays: 
  [stun:stunserver.stunprotocol.org:3478] is Available
  [stun:stun.freeswitch.org:3478] is Available
  [turn:turn-home.ioth.top:6478?transport=tcp] is Unavailable, reason: allocate: Allocate error response (error 442: UDP Transport is not allowed by the TURN Server configuration)
```

if I set no-udp, but unset no-udp-relay in coturn turnserver.conf,  the netbird status no error, but I seem that netbird client use udp to connect coturn relay :
```
netbird status -d
Relays: 
  [stun:stunserver.stunprotocol.org:3478] is Available
  [stun:stun.freeswitch.org:3478] is Available
  [turn:turn-home.ioth.top:6478?transport=tcp] is Available
```
