### ISSUE TITLE
Netbird client not work on corporate owned windows 10

### ISSUE THREAD

**Issue by vampywiz17** [netbirdio/netbird#419]
Hello there,

My working notebook are controlled Domain Policy, (for example i can not disable Firewall, or change network adapter public to private)

I able to install netbird client (i have local admin right) and netbird say that connect to server but it not able to ping any connected device.

(web interface say that the device online, and `netbird status -d` say that connected with relay mode. I also see the other peer if i run this command)

The interesting part is that i install Vanilla Wireguard windows client with same machine, it working well.

**Comment by braginini** [comment]
hey @vampywiz17 
The connection is established but the traffic is blocked by the Windows firewall.

We will be adding a feature that will integrate with Windows Packet Filter and allow traffic on the NetBird interface. 
I'll keep you posted!
