### ISSUE TITLE
Is there a specific way to set up adding multiple users under the domain.

### ISSUE THREAD

**Issue by iamshiyan** [netbirdio/netbird#420]
Is there a specific way to set up adding multiple users under the domain.

**Comment by braginini** [comment]
Hey @iamshiyan 
Are you using a self-hosted or managed version?
In case of a managed version, accounts with the same org private doing will end up in the same network.

**Comment by braginini** [comment]
Right @iamshiyan 
For the self-hosted version you will need to generate a unique account ID and add it to every user that you want to be in the same account in your IDP (Auth0).

In the hosted version we classify domains and add this ID automatically. 

I think that the best option for the self-hosted version would be to have a user invite feature that would allow to invite users via email. This would require an SMTP server running though.

**Comment by braginini** [comment]
@iamshiyan I probably didn't express myself very well.
We don't have this implemented yet, but will add soon.

**Comment by braginini** [comment]
@iamshiyan we planned it for Q4 this year. 
It might be coming earlier thought :)

**Comment by mlsmaycon** [comment]
This option is the default for the newly deployed self-hosted version. Please open a new issue in case you need support on migrating your users.
