### ISSUE TITLE
Firewall configuration

### ISSUE THREAD

**Issue by misuzu** [netbirdio/netbird#429]
What ports must be open for netbird to function?

**Comment by mlsmaycon** [comment]
Hello @misuzu, for peers to function, usually you won't need any open ports for incoming traffic, but if you are in a more strict network, you can follow the guide here: https://netbird.io/docs/FAQ/firewall-ports

If you are self-hosting, you can view the ports here: https://netbird.io/docs/getting-started/self-hosting#requirements

**Comment by mlsmaycon** [comment]
Probably not. Could you share the output from the command below? 

```shell
netbird status -d --filter-by-ips TARGET_IP
```

Replace TARGET_IP with an address that only worked after you opened the port

**Comment by misuzu** [comment]
I can't reproduce this anymore, everything is working fine without opening any ports ¯\_(ツ)_/¯

**Comment by firestrife23** [comment]
> Hello @misuzu, for peers to function, usually you won't need any open ports for incoming traffic, but if you are in a more strict network, you can follow the guide here: https://netbird.io/docs/FAQ/firewall-ports
> 
> If you are self-hosting, you can view the ports here: https://netbird.io/docs/getting-started/self-hosting#requirements

I tried opening the second link for self-hosting, but i'm getting 404 message. I had to disable my firewall in order for all peers to be reachable... I would like to know what ports i need to open.
