### ISSUE TITLE
Support dynamic OIDC config load in the Management service

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#434]
Instead of providing `AuthIssuer` and `AuthKeysLocation` the `management.json` config [file](https://github.com/netbirdio/netbird/blob/09312b3e6da7c82b15964d26ae3df4d5a38b0533/infrastructure_files/management.json.tmpl), provide an OIDC config endpoint from which this information can be fetched:

```
https://AUTHORITY/.well-known/openid-configuration
```

**Comment by mlsmaycon** [comment]
done in #439
