### ISSUE TITLE
Management code unnecessarily pulled in

### ISSUE THREAD

**Issue by szakharchenko** [netbirdio/netbird#436]
Here mgmtcmd
https://github.com/netbirdio/netbird/blob/09312b3e6da7c82b15964d26ae3df4d5a38b0533/client/internal/connect.go#L8
is only used to read the legacy port number:
https://github.com/netbirdio/netbird/blob/09312b3e6da7c82b15964d26ae3df4d5a38b0533/client/internal/connect.go#L264
Refactoring to avoid this dependency reduces output size.

**Comment by braginini** [comment]
Thanks you @szakharchenko for pointing out!

By how much did it reduce? Would you mind opening a PR?
