### ISSUE TITLE
Add support to define custom STUN/TURN servers per account 

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#440]
Management service configures a list of STUN/TURN servers sent to peers as a part of a configuration update. 

We could extend the Management service to allow users to configure a list of STUN/TURN servers. It will require a new API endpoint and Account store modification.

Relates to https://github.com/netbirdio/dashboard/issues/70

**Comment by VitalyVaryvdin** [comment]
Sorry for bringing up closed issue

Any update on this? Manually editing STUN/TURN addressed on client side would suffice
