### ISSUE TITLE
Routing Traffic to Private Networks - docker?

### ISSUE THREAD

**Issue by itsalljustdata** [netbirdio/netbird#453]
Should the routing to private networks work when the gateway is in a docker container?

```
traceroute 10.1.0.2
traceroute to 10.1.0.2 (10.1.0.2), 30 hops max, 60 byte packets
 1  100.119.x.x (100.119.x.x)  62.201 ms  61.936 ms  61.879 ms
 2  * * *
 3  * * *
 4  * * *
etc
etc
```

`wg show all dump` is showing what i'd expect based on the rules (i.e. 10.1.0.0/22 going to the appropriate netbird peer)

**Comment by itsalljustdata** [comment]
Ignore -

It seems that it's fine with netbird running in a docker container, but apparently *NOT* running inside a container which is running on a Unifi UDM Pro

**Comment by mlsmaycon** [comment]
Ok, I am interested on this setup as if the UniFi OS would have the nftables modules it should work well with masquerading enabled, unless there is extra filtering on the host itself
