### ISSUE TITLE
netbird-ui depends on development package

### ISSUE THREAD

**Issue by danoh** [netbirdio/netbird#456]
The netbird-ui_0.9.0_linux_amd64.rpm depends on libappindicator3-dev

The development package is probably needed only to compile the application, not to run it.

Additionally, on the OpenSUSE distribution the package is called libappindicator3-devel, so the dependency can't be resolved.

**Comment by mlsmaycon** [comment]
Thanks for raising this issue @danoh, we will be testing the dependency, and if not needed, we will remove from future releases

**Comment by mlsmaycon** [comment]
Duplicated: #402
