### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by bohemtucsok** [netbirdio/netbird#488]
Hello

So far it worked perfectly in my self hosted netbird server docker, I just updated the containers and management is not available ERR_TOO_MANY_REDIRECTS. does anyone have an idea what could be the problem?

**Comment by mlsmaycon** [comment]
Hello @bohemtucsok sorry for the late response. Over the last 45 days we had a series of updates for our dashboard that introduced support for other identity providers, like Keycloak and Authentik.

With that in mind, you might need to update the templates by running the configure.sh script again. Just make sure to backup the docker-compose.yml and setup.env files.
