### ISSUE TITLE
Can't ping server on oracle cloud

### ISSUE THREAD

**Issue by h4wwk3ye** [netbirdio/netbird#490]
I have 1 VPS on oracle cloud and 1 server at my home both running Ubuntu 22.04.1. On running `sudo netbird up` and then `netbird status -d` it shows the clients are connected but I am unable to ping. I can't even ping the same host itself using netbird ip which should be working at least on my home server which has no firewall.

```
Peers detail:
 Peer:
  NetBird IP:
  Public key: 
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: false
  ICE candidate (Local/Remote): srflx/srflx
  Last connection update: 2022-10-02 01:41:15

Daemon version: 0.9.7
CLI version: 0.9.7
Daemon status: Connected
Management: Connected to https://api.wiretrustee.com:443
Signal:  Connected to https://signal2.wiretrustee.com:443
NetBird IP: 
Interface type: Kernel
Peers count: 1/1 Connected
```

**Comment by mlsmaycon** [comment]
@h4wwk3ye  sorry for not replying sooner, but Since v0.20.0 we have improved the connectivity layer of the client, and on recent tests, direct connections to Oracle Cloud nodes have been successful.
