### ISSUE TITLE
Journallog shows read/write error

### ISSUE THREAD

**Issue by CommanderRedYT** [netbirdio/netbird#493]
`journalctl -u netbird.service`:
```
Oct 03 07:45:47 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:47 could not write packet: io: read/write on closed pipe
Oct 03 07:45:49 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:49 could not write packet: io: read/write on closed pipe
Oct 03 07:45:49 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:49 could not write packet: io: read/write on closed pipe
Oct 03 07:45:49 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:49 could not write packet: io: read/write on closed pipe
Oct 03 07:45:50 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:50 could not write packet: io: read/write on closed pipe
Oct 03 07:45:50 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:50 could not write packet: io: read/write on closed pipe
Oct 03 07:45:50 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:50 could not write packet: io: read/write on closed pipe
Oct 03 07:45:50 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:50 could not write packet: io: read/write on closed pipe
Oct 03 07:45:51 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:51 could not write packet: io: read/write on closed pipe
Oct 03 07:45:51 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:51 could not write packet: io: read/write on closed pipe
Oct 03 07:45:53 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:53 could not write packet: io: read/write on closed pipe
Oct 03 07:45:53 octopi netbird[605]: ice ERROR: 2022/10/03 07:45:53 could not write packet: io: read/write on closed pipe
Oct 03 07:46:20 octopi netbird[605]: ice ERROR: 2022/10/03 07:46:20 could not write packet: io: read/write on closed pipe
Oct 03 07:46:20 octopi netbird[605]: ice ERROR: 2022/10/03 07:46:20 could not write packet: io: read/write on closed pipe
Oct 03 07:46:20 octopi netbird[605]: ice ERROR: 2022/10/03 07:46:20 could not write packet: io: read/write on closed pipe
Oct 03 07:46:20 octopi netbird[605]: ice ERROR: 2022/10/03 07:46:20 could not write packet: io: read/write on closed pipe
Oct 03 07:46:20 octopi netbird[605]: ice ERROR: 2022/10/03 07:46:20 could not write packet: io: read/write on closed pipe
Oct 03 07:46:20 octopi netbird[605]: ice ERROR: 2022/10/03 07:46:20 could not write packet: io: read/write on closed pipe
```
This is a fresh setup of netbird on a raspberry pi 4b. `netbird status` works and shows the IPs, but pinging the device or from the device to other netbird clients is not working. I already tried apt-purging it, deleting the config files and reinstalling, but that did not help.

Other clients have this output when pinging the raspberry:
```
From laptop (100.xx.xx.xx) icmp_seq=1 Destination Host Unreachable
ping: sendmsg: Required key not available
```

**Comment by mlsmaycon** [comment]
Hello @CommanderRedYT, sorry to hear that you are facing connectivity issues. In order for us to better understand the problem, could you please share the following information:

- Are you using the cloud version or self-hosted?
- when you run `netbird status -d`, do you see the status as connected between the two peers you are trying to connect?

Regarding the `could not write packet` this is a temporal error and the ice client should recover in max 1 minute, if the log persists after 1 minute, can you share a bit firewall configurations, blocking UDP and if you have other VPN clients installed that might be redirecting traffic?

**Comment by CommanderRedYT** [comment]
> Are you using the cloud version or self-hosted?

I am using the one hosted on app.netbird.io.


> when you run `netbird status -d`, do you see the status as connected between the two peers you are trying to connect?

I have in total 4 devices in my network, and I only have connection issues to this pi. Other devices are 2nd pi and a VPS server.


> Regarding the `could not write packet` this is a temporal error and the ice client should recover in max 1 minute, if the log persists after 1 minute, can you share a bit firewall configurations, blocking UDP and if you have other VPN clients installed that might be redirecting traffic?

I'm not entirely sure how to lookup the firewall configs, but this issue persists over every internet connection (home/office/mobile network hotspot,...) and only for this one device. Connecting to other devices works flawless, but I installed it everywhere the same way.

**Comment by mlsmaycon** [comment]
@CommanderRedYT thanks for the fast response. Can you share some logs from your raspberry pi with the issue? You can follow the steps below for that.

On the pi that you can connect, can you run `netbird status -d`, in the block with IP from you laptop, you can copy and save its public key, we will use that for checking logs. 

Next, can you run the following commands to enable debug log and to get logs from connection attempts to your laptop:

enable debug logs
```shell
sudo netbird service stop
sudo netbird service uninstall
sudo netbird service install --log-level debug
sudo netbird service start
```
grep all logs for laptop connection
```shell
sudo grep LAPTOP_PUBLIC_KEY /var/log/netbird/client.log
```

**Comment by CommanderRedYT** [comment]
```
time="2022-10-03T10:26:19+02:00" level=error msg="failed signaling candidate to the remote peer <peer_id> rpc error: code = Unknown desc = peer <peer_id> is not registered" file="conn.go:455"
```

I got this a couple of times in the log, but nothing else other than this message. Weirdly enough, after enabling debug logs, it started to work again. (When I set it up last week, it too worked for ~24hrs and stopped the next day..)

**Comment by mlsmaycon** [comment]
Hello @CommanderRedYT did you face the issue again after 24 hours?

**Comment by CommanderRedYT** [comment]
> Hello @CommanderRedYT did you face the issue again after 24 hours?

No, now everything works as expected

**Comment by mlsmaycon** [comment]
Thanks, I will close this issue as it seems to have been a temporary issue and we can reopen if the issue happens again.

**Comment by CommanderRedYT** [comment]
@mlsmaycon So its happening again...
