### ISSUE TITLE
Allow silent installation on Windows

### ISSUE THREAD

**Issue by timwsuqld** [netbirdio/netbird#494]
We wish to deploy Netbird through tools like Intune, which require either a MSI or an EXE that supports silent installation (no GUIs, all options that need the ability to be set should have CLI flags that can be passed).

**Comment by mlsmaycon** [comment]
Hello @timwsuqld as we discussed in slack, we currently have support for it using the /S flag, for instance, installing the 0.9.7 version would be:

`.\netbird_installer_0.9.7_windows_amd64.exe /S`

After that you can run the up command with a setup key to activate it. 

We do have an issue with the upgrade with existing version, where the steps to remove the previous version is interactive. 

I will leave this ticket open to update you when the upgrade is completely silent.

**Comment by timwsuqld** [comment]
@mlsmaycon thanks for this. Use the `/S` switch worked. It still ends up running in the background (unlike a MSI that you can force to stay in foreground for a silent install) so some workarounds are still needed to detect when the silent install has finished. 

Any chance you can include in the github repo the files used for building the windows installers, and the steps, so others can help improve them? e.g. are you using NSIS, Installshield etc.

It appears we can do a silent install with wait via either `start "" /WAIT netbird_installer_0.9.7_windows_amd64.exe /S` or `ExecWait netbird_installer_0.9.7_windows_amd64.exe /S` depending on how we call it.

**Comment by mlsmaycon** [comment]
Hello @timwsuqld, as we discussed, the main issue with the background installation is that the NISIS installer is a UI application, and the windows terminal sends them to the background. Your solution with start (in CMD) or ExecWait (Powershell) seems to be the best approach for a blocking installation. 

BTW, the PR #505 has the fix for the upgrade process and also one small fix for an installation path bug we had.

**Comment by mlsmaycon** [comment]
@timwsuqld closing this issue since we didn't hear from you.

**Comment by W1BTR** [comment]
After running `netbird_installer_0.28.3_windows_amd64.exe /s` there was no output, and I do not see anything in program files (either the 64 bit or x86 folder). netbird up also replies `'netbird' is not recognized as an internal or external command,
operable program or batch file.`

This is being run with system permissions (full admin).

**Comment by mlsmaycon** [comment]
@W1BTR can you remove the installed version and check the install using MSI? https://docs.netbird.io/how-to/installation#windows

**Comment by ITCMD** [comment]
Tried with the MSI as well, same result. Immediately exits with no output. This is a remote machine with admin cmd access only (no desktop).

If I run this same command in an administrator command prompt on a desktop, it does successfully install with a popup cmd window, but not if I am logged in remotely as system.
