### ISSUE TITLE
Feature: Script parseable status details (JSON maybe?)

### ISSUE THREAD

**Issue by timwsuqld** [netbirdio/netbird#498]
It would be really useful to be able to get netbird client status from other clients (not just netbird-ui).

At the very least, the exit code of 'netbird status' should be useable to see if we are connected, but ideally something like a JSON output mode for the status so we can parse it in scripts. I don't really want to write a grpc client just to get basic things like "connected".

E.g. you can run `tailscale status --json` to get JSON output from the tailscale client, something like that.

**Comment by pascal-fischer** [comment]
Hi @timwsuqld,

Added support for JSON output via `netbird status --json` as well as YAML output via `netbird status --yaml` in PR#704.
The feature will be part of the next release (0.14.1)
