### ISSUE TITLE
Customizable user id claim

### ISSUE THREAD

**Issue by deluxghost** [netbirdio/netbird#507]
while logging in with sso, netbird read user id from hardcoded claim `sub`, but I'm using a custom claim (for example `username`), the `sub` field is just a hash of some details. I want an env var to tell netbird where to read user id from

**Comment by mlsmaycon** [comment]
@deluxghost, thanks for the suggestion, it makes sense, and I can see many deployments benefiting from that. 

FYI, if you are using an IDP like Authentik, you can choose between email or user ID for the sub-claim. 

Maybe you want to check your IDP in the meantime.

**Comment by deluxghost** [comment]
@mlsmaycon thanks for the reply. I know there are 4 modes for subject in authentik, however I am using a "really" customized claim field (if you wonder, it's a unique user attrib from social login, and I insert it into claims via property mapping)

I found some other apps like nextcloud allow me to customize this claim source, so I think netbird could also implement this

**Comment by mlsmaycon** [comment]
@deluxghost got it. Ok, we will check this for the upcoming releases
