### ISSUE TITLE
Peer metadata

### ISSUE THREAD

**Issue by rgl** [netbirdio/netbird#518]
Does it make sense to be able to set/attach metadata (e.g. an ad-hoc json document) to a peer?

That could be used to set description/labels/tags and other ad-hoc data to aid other humans/systems.

**Comment by braginini** [comment]
hey @rgl 

What is the use case you have in mind for that? 
What do you think would be the best way to set the metadata - on startup or via cmd?

**Comment by rgl** [comment]
I do not have a use-case. Just had a feeling that somehow having peer metadata might help the administrator/user/other-system identify the peers. Mainly, because I've created several test VMs, but did not change their hostname, so I ended up with a bunch of peers that appeared to be the same from a glance at the UI, and wondered whether a metadata/description would have helped; but unfortunately, I didn't apply much though into it and I'm now realizing that this is not be a good enough reason to have metadata.

In retrospect, sorry for wasting your time...

**Comment by mlsmaycon** [comment]
Thanks @rgl for the suggestion. 

According to your use case, it seems like you had a common issue, but there is an option to update a peer's name in the UI, see screenshot below:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/7747744/197283500-73b51f88-d199-41f5-80bb-c0d2fa3dfbbf.png">

We also push the system hostname if it is ever changed locally, you can see that expanding the peers system info:
<img width="340" alt="image" src="https://user-images.githubusercontent.com/7747744/197283621-166c35b2-97a1-4b76-9805-3433be8b5337.png">

Let us know if that would help you identify your peers.

**Comment by braginini** [comment]
@rgl 
You might also use setup keys or user tagging system. You could tag a setup key and use it to enroll machines. The tag will automatically apply to these machines.
https://netbird.io/docs/overview/setup-keys#peer-auto-grouping

**Comment by rgl** [comment]
Thank you for the pointers! I think using a unique setup key per peer will allow me to uniquely identity the peer. But maybe what I'm missing is a way to manage the peer IP address(es) (akin to DHCP, where we can configure static IP addresses for specific MACs, and let the system dynamically assign addresses to unknown MACs).
