### ISSUE TITLE
Wrong macOS Version reported in WebUI

### ISSUE THREAD

**Issue by vordenken** [netbirdio/netbird#527]
In the Netbird WebUI (cloud version) my mac gets reported with OS version 21.6.0 instead of 12.6 - the numberes seemed to be mixed up? 

<img width="369" alt="Bildschirmfoto 2022-10-25 um 08 58 08" src="https://user-images.githubusercontent.com/62395860/197704446-d2190900-ccd5-431d-8b20-16ba13079bc2.png">
<img width="424" alt="Bildschirmfoto 2022-10-25 um 08 57 48" src="https://user-images.githubusercontent.com/62395860/197704455-b043de94-a2f6-46cf-a99a-116c5b8471a2.png">

**Comment by pascal-fischer** [comment]
Just double-checked and PR #666 solved the issue.
