### ISSUE TITLE
problem starting netbird daemon on Raspberry Pi OS 11 (Debian 11 bullseye)

### ISSUE THREAD

**Issue by kocour** [netbirdio/netbird#538]
Hello, I have problem with running Netbird on Raspberry Pi OS 11 (Debian 11 bullseye).  I can see this error in `/var/log/netbird/client.log`:

```
time="2022-11-03T12:52:47+01:00" level=info msg="starting Netbird service" file="service_controller.go:23"
time="2022-11-03T12:52:47+01:00" level=info msg="started daemon server: /var/run/netbird.sock" file="service_controller.go:63"
time="2022-11-03T12:52:47+01:00" level=debug msg="conecting to the Management service api.wiretrustee.com:443" file="connect.go:82"
time="2022-11-03T12:52:47+01:00" level=debug msg="connected to the Management service api.wiretrustee.com:443" file="connect.go:87"
time="2022-11-03T12:52:48+01:00" level=debug msg="connected to Signal Service: signal2.wiretrustee.com:443" file="grpc.go:78"
time="2022-11-03T12:52:48+01:00" level=info msg="using userspace WireGuard" file="iface_linux.go:27"
time="2022-11-03T12:52:48+01:00" level=error msg="failed creating tunnel interface wt0: [no such device]" file="engine.go:233"
time="2022-11-03T12:52:48+01:00" level=error msg="error while starting Netbird Connection Engine: no such device" file="connect.go:149"
```

I've tried reinstalling package, reregister client (it is displayed in web console as Status: offline), but nothing helped out... Any idea what to do about it?

**Comment by braginini** [comment]
hey @kocour 
This looks weird. 

What is the output of: 
```
ls -l /dev/net/tun
```

**Comment by kocour** [comment]
```
root@avalon:~# ls -l /dev/net/tun
crw-rw-rw- 1 root root 10, 200 Sep 20 16:36 /dev/net/tun
```

**Comment by braginini** [comment]
would you mind joining slack? The issue seems to be very odd.
[Our Channel](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A)

**Comment by kocour** [comment]
sure, I'm in

**Comment by kocour** [comment]
problem was with tun kernel module (machine not rebooted after kernel and modules update) and has nothing to do with NetBird... solved by rebooting machine with last installed kernel

all credits goes to these fantastic guys @braginini @mlsmaycon for their super fast and accurate response ;-)
