### ISSUE TITLE
ice ERROR

### ISSUE THREAD

**Issue by airfield20** [netbirdio/netbird#540]
```
Nov 04 04:20:59 nuc netbird[941]: ice ERROR: 2022/11/04 04:20:59 could not write packet: io: read/write on closed pipe
```

My connections have been intermittent on several different machines for days at a time. Is there any way to force netbird to renegotiate its connection?

**Comment by braginini** [comment]
hey @airfield20 

could you please provide the full log? 
NetBird should automatically reconnect in case of broken connections.

**Comment by airfield20** [comment]
Seems like the ice error is actually from rebooting the netbird service in an attempt to connect to the server. Are there any more comprehensive logs than journalctl for netbird?

**Comment by mlsmaycon** [comment]
@airfield20 recently, we've refactored our connection layer, can you check if the intermittent connectivity still happening?

**Comment by airfield20** [comment]
I'm sorry, I'm no longer able to do any testing for the moment. This can be closed.
