### ISSUE TITLE
Connection issues with LittleSnitch Firewall on macOS

### ISSUE THREAD

**Issue by vordenken** [netbirdio/netbird#542]
For some reason Netbird started having issues with my application firewall LittleSnitch...
Despite the fact that I allow every connection for the Netbird app in LittleSnitch it still doesn't connect and throws an error (Screenshot for reference). If I disable LittleSnitch temporarily and start Netbird, it works - funny enough it then still works after enabling LittleSnitch again - maybe because it doesn't kill the established connection. 

What I don't get is I'm running LittleSnitch for years and also used Netbird for the last 2 weeks and this issue started to appear today...
<img width="1128" alt="Bildschirmfoto 2022-11-04 um 13 40 42" src="https://user-images.githubusercontent.com/62395860/199974872-01db653b-6ecb-4535-a8aa-aceb567addc5.png">

If you guys need any more informations or logs please lmk :)

**Comment by vordenken** [comment]
After some more troubleshooting I probably found the underlying issue. 
LittleSnitch still thinks the path of the process is "/opt/homebrew/Cellar/netbird/0.10.2/bin/netbird" but I already have a newer version so the real path is /opt/homebrew/Cellar/netbird/0.10.4/bin/netbird - because of that LittleSnitch cannot find the process to allow connections.


I have a lot of programs installed through brew and never had that problem before - so this might be a Netbird issue?

**Comment by mlsmaycon** [comment]
Hello, @vordenken does LittleSnitch works with symlinks? The way homebrew works with formulae applications is that it installs them in a version-specific path like /opt/homebrew/Cellar/netbird/0.10.4 and then it creates a symlink to /opt/homebrew/bin/netbird

**Comment by vordenken** [comment]
Just checked the release notes and apparently this got removed in version Little Snitch 4.3.2...
Weird because I have other stuff install via brew and haven't got any issues.
Is a normal installer / drop-in program for Mac planned?

**Comment by mlsmaycon** [comment]
Yes, it is. Also, we plan to move the daemon bin to the applications folder with the UI client, leaving things a bit more clean for the MacOS install

**Comment by vordenken** [comment]
small update regarding my problem: after stopping netbird, removing the rules in LittleSnitch and restarting my Mac, LittleSnitch (for now) sees the new symlink for 0.10.7.

**Comment by mlsmaycon** [comment]
Closing as the issue seems to be fixed with the upgrade
