### ISSUE TITLE
How to avoid IP conflict with tailscale?

### ISSUE THREAD

**Issue by cg31** [netbirdio/netbird#544]
Both netbird and tailscale are using the IP block 100.xxx.xxx.xxx.

There seems to be IP conflit. I have to stop tailscale to use netbird.

Is there a workaround to use them togather?

**Comment by braginini** [comment]
You can use `--netfilter-mode=off` when running Tailscale. 
This will prevent aggressive packets take over by Tailscale daemon.

It doesn't exclude the possibility of conflict but chances are low.

**Comment by cg31** [comment]
Great, it works.
