### ISSUE TITLE
Hardcoded Google DNS

### ISSUE THREAD

**Issue by vordenken** [netbirdio/netbird#547]
Why is the google dns server hardcoded? Every client has dns servers configured already...
Especially google might be a privacy issue...

**Comment by mlsmaycon** [comment]
Hello, @vordenken I believe you got a management service build from a work-in-progress branch. 

The latest commits in that branch removed that piece of code, and we will be offering some public DNS options from the Dashboard code. So nothing will be created automatically.

**Comment by vordenken** [comment]
Cool, thanks for the quick reply!
