### ISSUE TITLE
netbird-ui debian package have devel librairies depends

### ISSUE THREAD

**Issue by aderumier** [netbirdio/netbird#553]
Hi,
I'm trying to install netbird-ui debian package, 
and it seem than devel packages are presentin dependencies

``
apt install netbird-ui
Les NOUVEAUX paquets suivants seront installés :
  gir1.2-ayatanaappindicator3-0.1 gir1.2-ayatanaido3-0.4 icu-devtools libatk-bridge2.0-dev libatk1.0-dev libatspi2.0-dev libayatana-appindicator3-dev libayatana-ido3-dev libayatana-indicator3-dev libblkid-dev libbrotli-dev
  libcairo2-dev libdatrie-dev libdbus-1-dev libdbus-glib-1-dev libdbus-glib-1-dev-bin libdbusmenu-glib-dev libdeflate-dev libegl-dev libegl1-mesa-dev libepoxy-dev libffi-dev libfontconfig-dev libfontconfig1-dev libfreetype-dev
  libfreetype6-dev libfribidi-dev libgdk-pixbuf-2.0-dev libgl-dev libgles-dev libgles1 libglib2.0-dev libglib2.0-dev-bin libglvnd-core-dev libglvnd-dev libglx-dev libgraphite2-dev libgtk-3-dev libharfbuzz-dev libharfbuzz-gobject0
  libice-dev libicu-dev libjbig-dev libjpeg-dev libjpeg-turbo8-dev libjpeg8-dev liblerc-dev liblzma-dev libmount-dev libopengl-dev libpango1.0-dev libpcre2-dev libpcre2-posix3 libpixman-1-dev libpng-dev libpng-tools
  libpthread-stubs0-dev libselinux1-dev libsepol-dev libsm-dev libthai-dev libtiff-dev libtiffxx5 libwayland-bin libwayland-dev libx11-dev libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxcomposite-dev libxcursor-dev
  libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxft-dev libxi-dev libxinerama-dev libxkbcommon-dev libxrandr-dev libxrender-dev libxtst-dev netbird-ui pango1.0-tools uuid-dev wayland-protocols x11proto-dev
  xorg-sgml-doctools xtrans-dev
```

**Comment by mlsmaycon** [comment]
Duplicated: #402
