### ISSUE TITLE
Authentik 

### ISSUE THREAD

**Issue by bohemtucsok** [netbirdio/netbird#556]
Hello

My question is, does netbird work with authentik? and if so, could someone describe how I can configure it?  :) 

thanks in advance for your answers.

**Comment by braginini** [comment]
Hey @bohemtucsok 
It does :) Thought there are no instructions yet - [WIP by community](https://github.com/nolog-it/netbird-docs/blob/main/docs/integrations/identity-providers/self-hosted/authentik.md)

You could join our [Slack channel](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A) - there are some users who did the installation already.
