### ISSUE TITLE
It is not possible to edit the route

### ISSUE THREAD

**Issue by vitaleg** [netbirdio/netbird#559]
Netbird version  - v0.10.7

Screenshot: https://i.imgur.com/UVOoqhf.png

**Comment by braginini** [comment]
Hey @vitaleg 
You must be running Management version 0.10.5 or below. There was a bug in the route API.

To check the version run:
```
 docker inspect <MANAGEMENT IMAGE> | grep 'org.opencontainers.image.version'
```

Could you please update your self-hosted Management service docker container if it is lower than v0.10.6?

**Comment by vitaleg** [comment]
Yes, you're right. I thought I had updated the version.
