### ISSUE TITLE
Cant edit users

### ISSUE THREAD

**Issue by ykorzikowski** [netbirdio/netbird#561]
Hello there, 

I have a Netbird with SSO Keycloak integration and just updated to the most recent version. 

I can't edit the users in the webinterface, nor assign a group, nor change the role, nor change the name. 

The save button is always grey and the page is continously auto-reloading (if you are not fast enough entering the formula).

Any idea?

![Bildschirm­foto 2022-11-12 um 11 22 28](https://user-images.githubusercontent.com/20556547/201469953-884ec715-2671-4b97-9002-8b04225a0395.png)

**Comment by ykorzikowski** [comment]
I was able to manually edit the `netbird-mgmt/store.json` when the service was shut-down. But this should not be the optimal way :D

**Comment by mlsmaycon** [comment]
Thanks for reporting the issue @ykorzikowski. There is a bug in the dashboard when validating changes to the object. I will issue a fix

**Comment by mlsmaycon** [comment]
@ykorzikowski can you update your local deployment of the dashboard image and try again? it should be fine now

**Comment by ykorzikowski** [comment]
Looks good, I can change group, but the age is still reloading when editing.

**Comment by ykorzikowski** [comment]
Okay thank you. I will check.

**Comment by ykorzikowski** [comment]
@mlsmaycon can you tell me more exactly where to check? I did not find anything which will meet the 30-60 seconds refresh. :)
