### ISSUE TITLE
Simplify signal gRpc client

### ISSUE THREAD

**Issue by braginini** [netbirdio/netbird#57]
Instead of using sync groups to wait until stream is connected or retry mechanisms try using 
with grpc.WaitForReady(true)

See examples:
https://github.com/grpc/grpc-go/blob/master/examples/features/wait_for_ready/main.go

https://github.com/grpc/grpc-go/blob/master/examples/features/retry/client/main.go

**Comment by mlsmaycon** [comment]
leaving this internally
