### ISSUE TITLE
Support sending wireguard traffic over IPv6

### ISSUE THREAD

**Issue by Genteure** [netbirdio/netbird#577]
Currently only IPv4 addresses are used in the peer discovery process and as wireguard endpoints.
IPv6 support would enable clients that can't establish connection via NAT traversal but have IPv6 addresses to connect directly via IPv6.

I'm planning on doing a pull request for this.

This is not the same as #46

**Comment by mlsmaycon** [comment]
Hello, @Genteure that sounds great!
