### ISSUE TITLE
Let peer choose DNS port

### ISSUE THREAD

**Issue by e-renna** [netbirdio/netbird#585]
First of all, thank you for the recent update which brought the DNS feature!
I was wondering if it would be possible to let the user choose if the local resolver on each peer should bind on port 53 or 5053.
This could be a manual setting that would override the automatic check, that select port 5053 if port 53 is already in use.

The aim is to avoid problems with services that start after netbird and need to bind on port 53. In this case, netbird would bind on the port as at the time of check is free, but the later starting service would then fail to start because of it.

**Comment by mlsmaycon** [comment]
Thanks @e-renna I will add this option in the next release

**Comment by e-renna** [comment]
Hi @mlsmaycon, just curious to know if there is any updates regarding this feature.

**Comment by wuchang1123** [comment]
At present, I modify it directly and pack it myself.

**Comment by e-renna** [comment]
Closing this issue as it has been solved by @mlsmaycon with the following PR: #652  
Thank you!
