### ISSUE TITLE
docker setup stuck at login page

### ISSUE THREAD

**Issue by platinum55** [netbirdio/netbird#591]
Hello,

I followed your docker guide with the self-hosted keycloak and everything went without errors.
On the first load in the browser, after all containers were up, there was only a blank page with this error in the browser console:

`Uncaught TypeError: Failed to construct 'URL': Invalid base URL`
`at LoginError.tsx:54:12`
`at index.tsx:54:24`

As there were no errors in the container logs, I think this is a bug in the frontend javascript. Any idea how to resolve this? :-)

**Comment by Tiny-Wei** [comment]
How did you solve it?
