### ISSUE TITLE
Mobile Client status?

### ISSUE THREAD

**Issue by IngwiePhoenix** [netbirdio/netbird#596]
Hello!

I am trying to build a self-hosted network for my servers and as an entrypoint to my home-network when away. However, whilst on the go, I am usually on my phone - Android 12.

So I wanted to ask what the current status is regarding mobile clients? It's listed for Q3 2022 - which is about half-way done.

Thanks and kind regards,
Ingwie

**Comment by mlsmaycon** [comment]
Hello @IngwiePhoenix, mobile clients are in our roadmap for this quarter. 

We are looking into gomobile to port our client core to Ios and android.

**Comment by schlambos** [comment]
Any updates on the status? I'd love to move over to Netbird

**Comment by dillfrescott** [comment]
Soon hopefully

**Comment by mlsmaycon** [comment]
we've started working on the Android client. Our aim is to deliver it in this quarter. 

For the iOS client, we will focus on once the Android client is released.

**Comment by mlsmaycon** [comment]
Hello Folks, as you may already know, we are developing our android app. We will be doing a closed preview release for those that want to help us test the application with their devices. If you are interested in joining the list of testers, please fill the form in the following link: https://forms.gle/AuLwsnWV5Z4Pn3A87
Once the preview is ready, we will add your information to google play testing list and let you know so you can download the app.

**Comment by IngwiePhoenix** [comment]
Oh, I don't think partaking in Betas works when using Aurora Store (I run a de-googled phone - LineageOS for MicroG 20.0). But thank you for the update regardless! Looking forward to it =)

**Comment by yimiaoxiehou** [comment]
@mlsmaycon  Can intive me in testing list？

**Comment by mlsmaycon** [comment]
To update here, the Android client is https://play.google.com/store/apps/details?id=io.netbird.client

We started iOS development, and we are scheduled to deliver it at the beginning of Q3.

**Comment by sandstrom** [comment]
Related issues (possible duplicates?):
- https://github.com/netbirdio/netbird/issues/213
- https://github.com/netbirdio/netbird/issues/115

**Comment by oskarirauta** [comment]
@mlsmaycon 

What's the state with iOS version? Looking forward to it...

**Comment by mlsmaycon** [comment]
Hello @oskarirauta , it is under development, we currently have no specific date, but we will have a better view in couple of weeks. Then we can share a date for the preview release.

**Comment by oskarirauta** [comment]
Thanks @mlsmaycon 

If it's open source... As a developer license holder I can also build it for testing phase.

**Comment by mlsmaycon** [comment]
Hello folks, you can sign up for the iOS preview here: https://forms.gle/HVAdMKt2vSdCiTzY9

We will send you test flight invites when the first version is ready for testing.

**Comment by mlsmaycon** [comment]
Hello folks, we published the iOS app!!!

You can find it here:
https://apps.apple.com/us/app/netbird-p2p-vpn/id6469329339

We are looking into, publishing to China's store but it might be a problem as it requires more paperwork. So it will be great to hear from the community there, if there is an alternative distribution channel.
