### ISSUE TITLE
Keycloak integration - Peer detail does not show Username 

### ISSUE THREAD

**Issue by gcheewah** [netbirdio/netbird#601]
After integrating Keycloak with Netbird, everything works fine but i have an issue of the username does not show on the peer detail (check the screenshot).

![image](https://user-images.githubusercontent.com/25439044/205422248-3463a8c6-b87d-44e0-b225-5cd98a8433eb.png)

I've followed the keycloak integration documentation based from netbird.
I'm using keycloak with Active Directory integration.

Thank you.

**Comment by wuchang1123** [comment]
me too

**Comment by braginini** [comment]
Hey @gcheewah & @wuchang1123 

The user email should be shown there. This information comes from the IDP.  We implemented only the Auth0 IDP integration to fetch user data. Even thought the OIDC integration works with Keycloak, the IDP API integration with Keycloack is yet to be implemented.

Would you like to contribute? Here is a simple interface and Auth0 implementation:
https://github.com/netbirdio/netbird/blob/main/management/server/idp/idp.go#L12

https://github.com/netbirdio/netbird/blob/main/management/server/idp/auth0.go#L23

**Comment by cheewah-cd** [comment]
> Hey @gcheewah & @wuchang1123
> 
> The user email should be shown there. This information comes from the IDP. We implemented only the Auth0 IDP integration to fetch user data. Even thought the OIDC integration works with Keycloak, the IDP API integration with Keycloack is yet to be implemented.
> 
> Would you like to contribute? Here is a simple interface and Auth0 implementation: https://github.com/netbirdio/netbird/blob/main/management/server/idp/idp.go#L12
> 
> https://github.com/netbirdio/netbird/blob/main/management/server/idp/auth0.go#L23
> 
> As a workaround, we could put Keycloak userID there. Would it suffice?

Yes, userID should be sufficient.
Will check out the auth0 as well.
Thanks.

**Comment by mlsmaycon** [comment]
See docs https://docs.netbird.io/selfhosted/identity-providers#step-9-add-manage-users-role-to-netbird-backend for details on how to configure idp management integration, supporting name/email fetch from the IDP.
