### ISSUE TITLE
DNS Fallback

### ISSUE THREAD

**Issue by cfouche3005** [netbirdio/netbird#602]
**Describe the problem**
I use multiple adguard instances as DNS server but when is one instance is down, certain peer doesn't fallback to the second dns unless I disable it in Netbird.

**To Reproduce**
1. Create multiple Nameserver in https://app.netbird.io/dns
2. Down one DNS server
3. See error

**Expected behavior**
All peer should fallbak to the other dns server

**NetBird status -d output:**
```Peers detail:
 serv-lavos.netbird.cloud:
  NetBird IP: 100.105.92.118
  Public key: ntpT+bg9zh1A+iFCnZyux+HBSEY6ktMXvW14FIuz8nQ=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): host/host
  Last connection update: 2022-12-04 00:05:53

 serv-monitor.netbird.cloud:
  NetBird IP: 100.105.153.66
  Public key: oHo+rgUKfop2+u6CUrep4MuBDcnndqpx1nxy3lBaZBw=
  Status: Connected
  -- detail --
  Connection type: P2P
  Direct: true
  ICE candidate (Local/Remote): host/prflx
  Last connection update: 2022-12-04 11:51:13

Daemon version: 0.11.3
CLI version: 0.11.3
Daemon status: Connected
Management: Connected to https://api.wiretrustee.com:443
Signal:  Connected to https://signal2.wiretrustee.com:443
Domain: serv-lotus.netbird.cloud
NetBird IP: 100.105.210.93/16
Interface type: Kernel
Peers count: 2/2 Connected
```
Lavos fallback but the other not.

**Screenshots**
![image](https://user-images.githubusercontent.com/51720655/205488404-f4934d93-cec8-494b-839f-9881ba383ab8.png)
Lotus DNS is down and certain peer doesn't fallback to Monitor DNS
![image](https://user-images.githubusercontent.com/51720655/205488479-660b2919-384e-41e2-a12b-246d7fbf3aec.png)
On Lotus it doesn't work
![image](https://user-images.githubusercontent.com/51720655/205488510-e7e3362f-f39f-4e38-a223-7d2aaf7b9b2c.png)
But on Lavos it works

**Comment by cfouche3005** [comment]
After more test, DNS doesn't change unless I restart all netbird peers

**Comment by mlsmaycon** [comment]
Thanks for opening this issue @cfouche3005, we need to add an event connection between peers and the DNS configuration.

**Comment by mlsmaycon** [comment]
In #901 We've implemented a retry logic that validates the communication with private upstream services.

**Comment by Onur-Cansever** [comment]
There is another similar issue. I’ve configured two nameservers. After restarting one of them, clients reconnect to that server, which is fine, but then always receive responses from the second nameserver, even though it remains online. I verified this using Wireshark.
