### ISSUE TITLE
Homebrew Install Error - Wiretrustee Refference 

### ISSUE THREAD

**Issue by tomtom215** [netbirdio/netbird#613]
**Describe the problem**

Installing the client via Homebrew on MacOS presented an error

**To Reproduce**

`brew install netbirdio/tap/netbird`

**Expected behavior**

No errors

**Screenshots**
Error message:

> ==> Installing netbird from netbirdio/tap
Warning: netbird: No available formula with the name "wiretrustee". Did you mean wiredtiger?
'conflicts_with "wiretrustee"' should be removed from netbird.rb.
Please report this issue to the netbirdio/tap tap (not Homebrew/brew or Homebrew/core)!

**Comment by mlsmaycon** [comment]
Hello, @tomtom215, some homebrew executions fail due to the `HOMEBREW_DEVELOPER` and `HOMEBREW_INSTALL_FROM_API` being set. Can you check if running the following before running the install command will help?

```shell
export HOMEBREW_DEVELOPER=0;
export HOMEBREW_INSTALL_FROM_API=0;
```

I've also removed the conflict flag from the formulae in #615

**Comment by mlsmaycon** [comment]
Thank you, @tomtom215, for opening, it definitely will help others resolve this issue.
