### ISSUE TITLE
How to change `netbird.selfhosted` domain?

### ISSUE THREAD

**Issue by ykorzikowski** [netbirdio/netbird#619]
![grafik](https://user-images.githubusercontent.com/20556547/207015661-fd7c65e0-2388-4ba3-9df6-4763fa27207f.png)

I could not find it anywhere in documentation, and https://netbird.io/docs/overview/dns is empty

**Comment by mlsmaycon** [comment]
Hello @ykorzikowski, sorry for the lack of documentation for that. 

The domain name can be changed by passing the flag `--dns-domain` to the management service. Using our docker-compose.yml file this is done in the management service command definition.

e.g.:
```yml
command: ["--port", "443", "--log-file", "console", "--disable-anonymous-metrics=false", "--single-account-mode-domain=example.com","--dns-domain=example.com"]
```

**Comment by ykorzikowski** [comment]
thx @mlsmaycon :) working
