### ISSUE TITLE
Option to provide device name during registration

### ISSUE THREAD

**Issue by pnowy** [netbirdio/netbird#623]
**Is your feature request related to a problem? Please describe.**

When single user would like to multiple devices would be nice to have option to provide device name by CLI parameter (like `--name`) as could be hard to guess by NetBird operator who registered the device.

**Describe the solution you'd like**

Provide the device name manually to CLI or somehow automatically get the metadata info who registered the device

**Describe alternatives you've considered**

Have an option to configure JWT claim from IDP and add some metadata which user registered the device (but probably this will be solved by activity events showed by @braginini)

**Comment by cclements** [comment]
This would also be useful for me.  An --dev-name argument following --setup-key would be helpful, especially when using the same setup key for multiple endpoints.

**Comment by lfarkas** [comment]
it'd be very useful eg in case of home assistant or any other way when netbirn run inside a container. in this case it's very annoying that the hostname will be a docker container id eg: 049e78cb8a5d
