### ISSUE TITLE
Failed to update user

### ISSUE THREAD

**Issue by 0PandaDEV** [netbirdio/netbird#642]
**Describe the problem**
When I try to invite another user on the admin panel, I get an error message "Failed to update user". I have of course entered real data.

![image](https://user-images.githubusercontent.com/70103896/210377413-66331843-1041-485d-9eb5-9fbca94d6723.png)
![image](https://user-images.githubusercontent.com/70103896/210377423-2e955ca4-fe34-4fb5-a70a-aabf763fca4d.png)

Can it be that it is because the user has already registered with this email? In the docs it says that you can only invite unregistered users. If this is the case, is there a way to invite this user anyway?

![image](https://user-images.githubusercontent.com/70103896/210378071-d4592597-3bdd-44b6-9fff-42b8a171889b.png)

**Comment by braginini** [comment]
Hey @0PandaDEV.
That's not possible because if a user exists, this means that they have an account, and NetBird only supports one account/network per user.

However, we could modify it manually for your case. Please ping us via [Slack](https://join.slack.com/t/netbirdio/shared_invite/zt-vrahf41g-ik1v7fV8du6t0RwxSrJ96A).

**Comment by dillfrescott** [comment]
When I invite a user, it brings them to a sign up page. And when I make an account for the user and try to invite a user, it errors out. Makes no sense

**Comment by dillfrescott** [comment]
It says:

```
The invited users will receive an email invitation that they have to confirm. After logging in to the system, they will join your network automatically.
```

And when I try to "log in" as that user it throws an error...

**Comment by mlsmaycon** [comment]
> It says:
> 
> ```
> The invited users will receive an email invitation that they have to confirm. After logging in to the system, they will join your network automatically.
> ```
> 
> And when I try to "log in" as that user it throws an error...

@dillfrescott could you share the error?

**Comment by dillfrescott** [comment]
![Screenshot 2023-09-12 205922](https://github.com/netbirdio/netbird/assets/56714680/1ec3c81f-a3d8-43b6-a2ef-f0fe11ac9fae)
