### ISSUE TITLE
Consider adding a CHANGELOG or release notes

### ISSUE THREAD

**Issue by marco-m** [netbirdio/netbird#677]
Hello,

please consider adding a CHANGELOG file or a summary of the most important changes in each release.

Currently if one goes to the Releases page (https://github.com/netbirdio/netbird/releases), the only information is the version and the contributors. If would be nice to have a sort of release notes :-) If they are already available elsewhere, then the release page could contain a simple link to the corresponding release notes or similar.

Thanks!

**Comment by mlsmaycon** [comment]
Hello @marco-m we are adding the release notes on each release, the only exception is for follow up releases on the same day where they are usually got fast bug fixes. Can you have a look again on the releases page?

**Comment by marco-m** [comment]
@mlsmaycon thanks for your kindness in not treating me like a stupid :-)
Turned out I had a too strong uBlock configuration 🤦‍♂️ . Never mind :-)
