### ISSUE TITLE
Feature: Reauthentication after disconnect

### ISSUE THREAD

**Issue by giezi** [netbirdio/netbird#715]
**Is your feature request related to a problem? Please describe.**
The feature request is related to improve the security.

**Describe the solution you'd like**
For security reasons, we want that when a user disconnects, he has to re-authenticate. It would be great if we could have a "setting" that could be set per user to control the disconnect behaviour.

**Describe alternatives you've considered**
None.

**Comment by mlsmaycon** [comment]
Hello @giezi we are currently working on a time-based peer expiration, where peers activated by users will require authentication after N hours (from 1 hour to 180 days).

**Comment by e-renna** [comment]
> Hello @giezi we are currently working on a time-based peer expiration, where peers activated by users will require authentication after N hours (from 1 hour to 180 days).

Would there be a setting to disable the expiration? e.g. for a peer that is used for a service (like a DNS server) rather than a user endpoint

**Comment by mlsmaycon** [comment]
@e-renna yes the feature will be enabled for new accounts. For existing accounts you can choose to enable in the account settings and you can also choose to disable expiration for specific peers.

**Comment by mlsmaycon** [comment]
See https://github.com/netbirdio/netbird/releases/tag/v0.14.2
