### ISSUE TITLE
Add support for personal access tokens and service users

### ISSUE THREAD

**Issue by pascal-fischer** [netbirdio/netbird#718]
**Is your feature request related to a problem? Please describe.**
Being able to create personal access tokens to use for authenticating when sending API requests from 3rd-party applications or when using scripts.

**Describe the solution you'd like**
There should be an option to create personal access tokens for my user to use for authenticating agains the API. For better usability it would be good to have service users that are not bound to a specific person but can be created to hold tokens independently.

**Comment by MohammedNoureldin** [comment]
Hi, how far is it from being ready? May I ask that you also add an initial access token (auto-generated or passed in the CLI) that will expire in for example 1 hour? This will help to automate the whole setup of Netbird.
