### ISSUE TITLE
Feature: Exit nodes

### ISSUE THREAD

**Issue by giezi** [netbirdio/netbird#723]
**Describe the solution you'd like**
It would be great if you could implement exit nodes like Tailscale, which can be selected in the client.
https://tailscale.com/kb/1103/exit-nodes/

Many thanks for considering this :)

**Comment by lorenzo95** [comment]
Agree. It's a bit odd that this is missing. The network routes section won't let you add a route smaller than a /7

**Comment by mrbluecoat** [comment]
duplicate of #289

**Comment by mlsmaycon** [comment]
Closing duplicate

**Comment by thehoff** [comment]
you say this is a duplicate of #289 and that brings me to #723 and they are both closed and netbird still wont allow anything larger than a /7. 
the use of a 0.0.0.0/0 route especially with mobile devices might even solve the bug you have in the android client on #858 ?

**Comment by tbleiker** [comment]
Any update on this? I am evaluating a few solutions and I like netbird a lot. However, I need this functionality.

**Comment by tiagogbarbosa** [comment]
Any updates on this?

**Comment by EngEryx** [comment]
Having an Exit node can come in handy..

**Comment by B08Z** [comment]
Is this a planned feature. It's the only thing stopping me using netbird as my primary (and only) VPN solution.

**Comment by svardie** [comment]
Any news on when exit node feature will come to Android/iOS clients? Looks like this is only feature, that keeping us from switching to NetBird.
