### ISSUE TITLE
Usernames are not displayed for peers

### ISSUE THREAD

**Issue by giezi** [netbirdio/netbird#724]
**Describe the problem**
When Keycloak is used in connection with netbird, no usernames are displayed at the peers.

**To Reproduce**
1. Go to 'Peers'
2. Click on one 'Peer'
3. In the sidebar the username empty and the field is grayed out

**Expected behavior**
Username of peer should be displayed

**Screenshots**

<img width="365" alt="Screenshot 2023-03-06 at 08 39 10" src="https://user-images.githubusercontent.com/1326203/223047941-45354266-b195-4968-a95d-f391b2de8e8f.png">

**Comment by braginini** [comment]
Hey @giezi 
The names are not displayed because there is no integration with Keycloack user API. 
We have only one yet - Auth0. See https://github.com/netbirdio/netbird/tree/main/management/server/idp.
NetBird doesn't store any personal info locally.

But the implementation should be simple. What is your experience with Golang? Maybe you could help us out with it? :)

**Comment by giezi** [comment]
Hi @braginini -unfortunately, I don't have any experience in Golang. However, we would like to support the project and see if we can find someone on Upwork who will implement this and provide it back into the project.

**Comment by braginini** [comment]
@giezi 
That's awesome! Thank you.
The implementation should implement this interface https://github.com/netbirdio/netbird/blob/ed4f90b6aa7193e9da99f6d05d89da531bb16e76/management/server/idp/idp.go#L12
Here is the example https://github.com/netbirdio/netbird/blob/ed4f90b6aa7193e9da99f6d05d89da531bb16e76/management/server/idp/auth0.go#L23

I belive that this Keycloack API reference can be used
https://www.keycloak.org/docs-api/15.0/rest-api/index.html#_users_resource

**Comment by giezi** [comment]
@braginini The work is done: https://github.com/netbirdio/netbird/pull/746

**Comment by braginini** [comment]
> @braginini The work is done: #746

Damn awesome! We will have a look

**Comment by giezi** [comment]
@braginini I saw that the pull request was accepted, and the feature is implemented :) Happy weekend!
