### ISSUE TITLE
Relays/Exit nodes/Subnet routers

### ISSUE THREAD

**Issue by alexlyee** [netbirdio/netbird#733]
The only feature that I see [in Netmaker](https://github.com/gravitl/netmaker) that I'm really missing out on here is the ability to advertise routes. I think this is essentially what #289 was getting at, but I'd like to be more specific because I think generalizing this problem hits a lot of birds (oughsorry!) with the same stone:

- If a client/user advertises other addresses within the network (i.e. 100.0.0.0/8) to be routable from them, they have **elected themselves to be a potential fallback path (fallback router?) for the network**. This would be particularly desirable for me because I'm hosting mine on a little VPS and really would rather not have to worry about an unknowing family member or friend hitting my monthly data limit because NAT tunneling was unsuccessful between them and, say, the NAS.
- If a client/user advertises their LAN network addresses, they may be called a **local exit node.**
- If a client/user advertises any other addresses, this would make them an **exit node.** Without this feature, I've got to use a separate Wireguard tunnel on my PC to use netbird to access my things and exit through my home network the way I'd like. And without this feature, I don't think I could use the mobile app for my use case.

Maybe this differentiation would be useful for UI and for buttons for toggling the three on and off.

edit: this was also mentioned, upvoted, but not replied to, in [this discussion](https://github.com/netbirdio/netbird/discussions/587).

**Comment by bmullan** [comment]
@alexlyee lexlyee

Isn't this what you are asking for?
**[Routing traffic to private networks](https://netbird.io/docs/how-to-guides/network-routes)**

**Comment by alexlyee** [comment]
@bmullan you're right 🤦 I assumed this wasn't implemented because #289 wasn't.

thanks for the heads-up

**Comment by mrbluecoat** [comment]
> @alexlyee lexlyee
> 
> Isn't this what you are asking for? **[Routing traffic to private networks](https://netbird.io/docs/how-to-guides/network-routes)**

_broken link_

**Comment by alexlyee** [comment]
> > @alexlyee lexlyee
> 
> > 
> 
> > Isn't this what you are asking for? **[Routing traffic to private networks](https://netbird.io/docs/how-to-guides/network-routes)**
> 
> 
> 
> [_updated link_](https://docs.netbird.io/how-to/routing-traffic-to-private-networks)

I'm asking for relay nodes like netmaker has. That's all.

**Comment by PavelNiedoba** [comment]
I cannot get netbird network (the one starting with 100.) to work with nodes without public IP.  I have multiple private networks. Each one have router with public IP where I can configure port forward. Inside those networks I have clients which I want to be available within netbird network.  I cannot find documentation how to do that.

**Comment by PatrickHuetter** [comment]
> I cannot get netbird network (the one starting with 100.) to work with nodes without public IP. I have multiple private networks. Each one have router with public IP where I can configure port forward. Inside those networks I have clients which I want to be available within netbird network. I cannot find documentation how to do that.

Similar setup for me. Because netbird is missing exit node feature i can't use it and have to rely on headscale. Already compared all overlay network solutions out there and netbird has the possibilty to outline all of them **IF** they implement exit node feature. 

In my case i have IPv6 only machines that need access to IPv4 internet. Having one dual stack machine in my network and marking this machine as exit node all other ipv6-only machines are able to connect to the internet (public network) using this dual stack machine as gateway.

**Comment by PavelNiedoba** [comment]
I fixed my port forwarding and netbird can now go behind NAT. Documentation should be improved, it's very high level.
