### ISSUE TITLE
Domain Name Increment

### ISSUE THREAD

**Issue by cfouche3005** [netbirdio/netbird#772]
**Describe the problem**
Netbird still increment domain name despite deleting it.

**To Reproduce**
1. Delete a peer 
2. Create a peer with the same domain as the previous deleted one

**Expected behavior**
Netbird shouldn't increment the domain name if the previous peer with the same name is delete or we sould have an option to change the domain name

**Screenshots**
![image](https://user-images.githubusercontent.com/51720655/228315372-ff51eda5-5404-4595-92a0-66e5b343dd62.png)
![image](https://user-images.githubusercontent.com/51720655/228354432-2734b3a3-7e73-48e8-94a4-57b40bb67d9c.png)

**Comment by pascal-fischer** [comment]
Hi,

I am trying to reproduce the issue but for me it seems to work fine so far.

Can you give me some more information about the environment? are you running in docker with auto restart?

**Comment by cfouche3005** [comment]
I am on the cloud version.
I have redo the same steps as before :
Delete the serv-monitor peer (hostname : serv-monitor-1.netbird.cloud)
Recreated the peer with the same name (serv-monitor) and this time the hostname didn't incremented so the peer hostname is back to serv-monitor.netbird.cloud

**Comment by mlsmaycon** [comment]
@cfouche3005 thanks for the feedback. Regarding the option to change the name, when you click on a peer it will open the screen with peer information. You can update the name at the very top of the screen, where the name is visible with the edit icon next to it:
![image](https://user-images.githubusercontent.com/7747744/229226201-e10b1024-83dc-42b8-baef-7f28bcf9a802.png)
