### ISSUE TITLE
missing domain for SSL in managment.json cant sign in

### ISSUE THREAD

**Issue by tjsims1** [netbirdio/netbird#793]
**Describe the problem**
Cant login as managment.json are missing domain for for the directory for the SSL Cert

**To Reproduce**
1.  new install
2.  setup your env
3.  run configure
4. check managment.json
        "CertFile":"/etc/letsencrypt/live//fullchain.pem",
        "CertKey":"/etc/letsencrypt/live//privkey.pem",
both certfile and certkey are missing domain

**Comment by braginini** [comment]
Hi @tjsims1 
What version are you using?

**Comment by mlsmaycon** [comment]
@tjsims1 there is a bug for the variable in the last 2 releases. The fix will come in the PR https://github.com/netbirdio/netbird/pull/794

For the time being, please edit the generated `management.json` file and update the following lines:
```json
        "CertFile":"/etc/letsencrypt/live//fullchain.pem",
        "CertKey":"/etc/letsencrypt/live//privkey.pem",
```

With your the correct paths:
```json   
        "CertFile":"/etc/letsencrypt/live/your.domain.com/fullchain.pem",
        "CertKey":"/etc/letsencrypt/live/your.domain.com/privkey.pem",
```

After that a simple `docker-compose restart management`  will restore the service
