### ISSUE TITLE
dns support only routing domain but not search domain

### ISSUE THREAD

**Issue by lfarkas** [netbirdio/netbird#828]
if add a domain with nameserver  in the DNS tab it's add only routing only domain (at least on linux).  eg if i add foo.com to 1.2.3.4 then i see something like this on the resolvectl output:
```
Link 5 (wt0)
    Current Scopes: DNS
         Protocols: +DefaultRoute LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 100.76.24.179
       DNS Servers: 100.76.24.179
        DNS Domain: netbird.cloud ~foo.com
```
this result that if i try to resolve a name with:
`resolvectl query bar.foo.com`
than it's working, BUT if i try with short name only eg:
`resolvectl query bar` or `ping bar`
than it's not working. and currently I'm not able to solve it.

it'd be nice if i can add search domains too. The best would be if i can configure whether add routing or search domain in the DNS tab.

**Comment by gigovich** [comment]
Hello, @lfarkas. When Netbird DNS name resolving is enabled, a short domain name search works only for `netbird.cloud` zone. So you can resolve as short names only peers in the Netbird network. For all other queries, you need to use FQDN domain names.

**Comment by lfarkas** [comment]
it seems the situation was not clear enough.
if we got a domain and a dns for it than the given zone probably contains many fqdn hostname in the dns (otherwise we do't use a dns).
we probably have a netbird client in the given network but not all of the host has a netbird client (otherwise the .netbird.cloud zone resolution would be enough).
so when we'd like to manage dns in netbird, then we've a routed network with a gateway netbird clinet inside this  network. 
if i'd like to use dns in netbird then i'd like to be able to resolve all host in that domain.
of course as a the routing only domain it's better then nothing since if i use fqdn then it resolve it but if i'd like to resolve short names than it's not working what's more there is no way to resolve short names for these domains.

that's  why i'd propose that by default these domains should have to be search domain or at least it should have to be configurable to be routing only dns  or search dns.

**Comment by lfarkas** [comment]
fixed in the latest release
