### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [netbirdio/netbird#852]
Is there a way for a peer to disable the ssh ability?

**Comment by oskardotglobal** [comment]
You mean the ability for a peer to connect via SSH? AFAIK not, but you could restrict access entirely using ACL or try to block the connection from that IP on the port via iptables

**Comment by dillfrescott** [comment]
Is there a way to do this officially yet?

**Comment by braginini** [comment]
Hey @dillfrescott 

I think that this won't be hard to add as a client parameter. I will check this next week.

**Comment by tjarbo** [comment]
Would suggest to close this as duplicate of #509, and to continue discussion there.

**Comment by mlsmaycon** [comment]
duplicate of #509
