### ISSUE TITLE
Home Assistant Add-ons for NetBird

### ISSUE THREAD

**Issue by lfarkas** [netbirdio/netbird#884]
I created a netbird  addon for home assistant:
https://github.com/lfarkas/addon-netbird
unfortunately it can't be added to to community addons until android and ios clients will be released.
IMHO it'd be the better to move this repo under 
https://github.com/netbirdio/homeassistant-netbird-addon
until it can't be added to the community addons.

**Comment by mlsmaycon** [comment]
Thank you @lfarkas for the amazing work and contribution.

We have transferred the repository to the NetBird organization.

We need to adjust the links and docs, but it should be fine. 


The old repository url will redirect to the new one, but will be good to document the url change too.
