### ISSUE TITLE
DNS doest'n work on MacOS

### ISSUE THREAD

**Issue by rgonzlz** [netbirdio/netbird#894]
**Describe the problem**

The DNS Match domain doest'n work never.

If I change to Match all the DNS resolver is not working for ANY website.

On my server DNS doesn't have any error log, so never reach to my server.

I'm using MacOS M2, 13.3.1

**Expected behavior**
Netbird should resolve to forward to the private DNS server the requests of the selected domains.

**NetBird status -d output:**
Daemon version: 0.20.3
CLI version: 0.20.3
Management: Connected to https://api.wiretrustee.com:443
Signal: Connected to https://signal2.wiretrustee.com:443
Interface type: Userspace

**Screenshots**

Match domain
![Pasted Graphic 1](https://github.com/netbirdio/netbird/assets/7152452/4a40002e-4bb7-4e89-bce6-f864d2c86647)
![image](https://github.com/netbirdio/netbird/assets/7152452/247c4f2a-b9e7-468c-a2c1-4f6ee47fb21b)
![image](https://github.com/netbirdio/netbird/assets/7152452/4eb3dfed-6e34-4ae1-9b72-e39f30816935)

Match all
![Pasted Graphic 3](https://github.com/netbirdio/netbird/assets/7152452/10b74ed7-3391-4031-a272-6147569e00e7)

**Comment by mlsmaycon** [comment]
Hello @rgonzlz, the NetBird's dns management system uses the macOS dns routing system to configure match domains. Unfortunately this mode is not supported by tools like `nslookup` or `dig`. To validate your DNS configuration, please use a tool like `dscacheutil `:
```
dscacheutil -q host -a name peer-a.netbird.cloud
```

**Comment by rgonzlz** [comment]
Hi!

Without Netbird
![Pasted Graphic 4](https://github.com/netbirdio/netbird/assets/7152452/d5973d58-4caf-4b8e-9906-9b82d71253ff)

With NetBird
![Pasted Graphic 5](https://github.com/netbirdio/netbird/assets/7152452/46a0daea-7d75-4bd1-9252-2b9273918eb2)

**Comment by mlsmaycon** [comment]
Hi @rgonzlz from your screenshots in the first message, the resolve all domains seem to work for the `int.xxx.com` domain, and in the second message's screenshot, there was a resolution for the whoami name with the 198.18.2.1 address again.

But the answer for the netbird.cloud domain is wrong as it returned the wrong address. Can you enable the trace log in the agent? 


```shell
sudo netbird service stop
sudo netbird service uninstalll
sudo netbird service install --log-level trace
sudo netbird service start
```

**Comment by rgonzlz** [comment]
Hi!

But I cannot resolve private domains (xxx.com) :/

Here is the log:

[netbird.client.log](https://github.com/netbirdio/netbird/files/11553924/netbird.client.log)

**Comment by mlsmaycon** [comment]
@rgonzlz can you confirm your macOS version and if you had any other VPN app previously running?

And please share the output from `scutil --dns`

**Comment by rgonzlz** [comment]
Hi!

Yep! I have WireGuard (but disconnected) and FortiClient (disconnected)

```DNS configuration

resolver #1
  search domain[0] : netbird.cloud
  search domain[1] : technicolor.net
  nameserver[0] : 192.168.0.1
  if_index : 11 (en0)
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : netbird.cloud
  nameserver[0] : 127.0.0.1
  port     : 53
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00030002 (Reachable,Local Address,Directly Reachable Address)
  order    : 103000

resolver #3
  domain   : int.xxx.com
  nameserver[0] : 127.0.0.1
  port     : 53
  flags    : Supplemental, Request A records, Request AAAA records
  reach    : 0x00030002 (Reachable,Local Address,Directly Reachable Address)
  order    : 102600

resolver #4
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #5
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #6
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #7
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #8
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #9
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  search domain[0] : technicolor.net
  nameserver[0] : 192.168.0.1
  if_index : 11 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)```

**Comment by mlsmaycon** [comment]
Thanks for confirming. @rgonzlz we got another user with a similar issue that also got the FortiClient installed and disconnected. 

Can you check if there is any of these [processes](https://docs.fortinet.com/document/forticlient/7.2.0/administration-guide/234949/forticlient-macos-processes) running on the system? 

You can use `ps aux | grep -i FortiClient`

**Comment by rgonzlz** [comment]
Hi!

Only this one appears

> root               926   0.0  0.0 409645264  10640   ??  Ss    8:47AM   0:00.33 /Library/Application Support/Fortinet/FortiClient/bin/fctservctl2


Here is the complete list

> root              4899   0.0  0.0 409642560   8976   ??  Ss    8:47AM   0:00.46 /Library/PrivilegedHelperTools/com.fortinet.forticlient.macos.PrivilegedHelper
root              4882   0.0  0.1 409647296  18000   ??  Ss    8:47AM   0:05.79 /Library/Application Support/Fortinet/FortiClient/bin/fcconfig
root               409   0.0  0.0 409238688   6624   ??  Ss    8:00AM   0:05.80 /Library/Application Support/Fortinet/FortiClient/bin/ztnafw
rgonzlz             6850   0.0  0.0 409219552   7296   ??  S     8:47AM   0:03.25 /Library/Application Support/Fortinet/FortiClient/bin/ztagent
rgonzlz             4893   0.0  0.1 409812672  25200   ??  S     8:47AM   0:00.25 /Applications/FortiClient.app/Contents/Resources/runtime.helper/FortiTray.app/Contents/MacOS/FortiTray
rgonzlz             4892   0.0  0.1 409661184  20384   ??  S     8:47AM   0:00.44 /Applications/FortiClient.app/Contents/Resources/runtime.helper/FortiClientAgent.app/Contents/Resources/runtime.helper/FctMiscAgent.app/Contents/MacOS/FctMiscAgent
rgonzlz             4880   0.0  0.0 408508032   3072   ??  S     8:47AM   0:00.02 /Library/Application Support/Fortinet/FortiClient/bin/CredentialStore
rgonzlz             4876   0.0  0.1 409799632  25776   ??  S     8:47AM   0:00.25 /Applications/FortiClient.app/Contents/Resources/runtime.helper/FortiClientAgent.app/Contents/MacOS/FortiClientAgent
rgonzlz             4875   0.0  0.4 414216192 105936   ??  S     8:47AM   0:02.47 /Applications/FortiClient.app/Contents/Frameworks/FortiClient Helper (Renderer).app/Contents/MacOS/FortiClient Helper (Renderer) --type=renderer --field-trial-handle=1718379636,9799536100589025288,1538587340392228958,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --disable-gpu-compositing --lang=es --app-path=/Applications/FortiClient.app/Contents/Resources/app.asar --node-integration --node-integration-in-worker --no-sandbox --no-zygote --enable-remote-module --background-color=#fff --enable-spellcheck --enable-websql --disable-electron-site-instance-overrides --num-raster-threads=4 --enable-zero-copy --enable-gpu-memory-buffer-compositor-resources --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files
rgonzlz             4874   0.0  0.1 408908400  22736   ??  S     8:47AM   0:00.06 /Applications/FortiClient.app/Contents/Frameworks/FortiClient Helper.app/Contents/MacOS/FortiClient Helper --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=1718379636,9799536100589025288,1538587340392228958,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --lang=es --service-sandbox-type=network --shared-files --seatbelt-client=41
rgonzlz             4862   0.0  0.2 409898256  46416   ??  S     8:47AM   0:00.36 /Applications/FortiClient.app/Contents/Frameworks/FortiClient Helper (GPU).app/Contents/MacOS/FortiClient Helper (GPU) --type=gpu-process --field-trial-handle=1718379636,9799536100589025288,1538587340392228958,131072 --enable-features=WebComponentsV0Enabled --disable-features=CookiesWithoutSameSiteMustBeSecure,SameSiteByDefaultCookies,SpareRendererForSitePerProcess --gpu-preferences=MAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAQAAAAAAAAAAAAAAAAAAAA6AAAABwAAADgAAAAAAAAAOgAAAAAAAAA8AAAAAAAAAD4AAAAAAAAAAABAAAAAAAACAEAAAAAAAAQAQAAAAAAABgBAAAAAAAAIAEAAAAAAAAoAQAAAAAAADABAAAAAAAAOAEAAAAAAABAAQAAAAAAAEgBAAAAAAAAUAEAAAAAAABYAQAAAAAAAGABAAAAAAAAaAEAAAAAAABwAQAAAAAAAHgBAAAAAAAAgAEAAAAAAACIAQAAAAAAAJABAAAAAAAAmAEAAAAAAACgAQAAAAAAAKgBAAAAAAAAsAEAAAAAAAC4AQAAAAAAABAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAGAAAAEAAAAAAAAAAAAAAABwAAABAAAAAAAAAAAAAAAAgAAAAQAAAAAAAAAAAAAAAKAAAAEAAAAAAAAAAAAAAACwAAABAAAAAAAAAAAAAAAA0AAAAQAAAAAAAAAAEAAAAAAAAAEAAAAAAAAAABAAAABgAAABAAAAAAAAAAAQAAAAcAAAAQAAAAAAAAAAEAAAAIAAAAEAAAAAAAAAABAAAACgAAABAAAAAAAAAAAQAAAAsAAAAQAAAAAAAAAAEAAAANAAAAEAAAAAAAAAAEAAAAAAAAABAAAAAAAAAABAAAAAYAAAAQAAAAAAAAAAQAAAAHAAAAEAAAAAAAAAAEAAAACAAAABAAAAAAAAAABAAAAAoAAAAQAAAAAAAAAAQAAAALAAAAEAAAAAAAAAAEAAAADQAAABAAAAAAAAAABgAAAAAAAAAQAAAAAAAAAAYAAAAGAAAAEAAAAAAAAAAGAAAABwAAABAAAAAAAAAABgAAAAgAAAAQAAAAAAAAAAYAAAAKAAAAEAAAAAAAAAAGAAAACwAAABAAAAAAAAAABgAAAA0AAAA= --use-gl=swiftshader-webgl --shared-files
rgonzlz              782   0.0  0.3 414412048  67696   ??  S     8:47AM   0:00.68 /Applications/FortiClient.app/Contents/MacOS/FortiClient
rgonzlz            16676   0.0  0.0 408626896   1344 s007  S+    9:38AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i FortiClient

**Comment by rgonzlz** [comment]
Hi!

Same results.

Process list:

> rgonzlz             6850   0.0  0.0 409219552   8640   ??  S     8:47AM   0:05.85 /Library/Application Support/Fortinet/FortiClient/bin/ztagent
rgonzlz             4880   0.0  0.0 408508032   2192   ??  S     8:47AM   0:00.03 /Library/Application Support/Fortinet/FortiClient/bin/CredentialStore
root               926   0.0  0.0 409645264   9248   ??  Ss    8:47AM   0:00.44 /Library/Application Support/Fortinet/FortiClient/bin/fctservctl2
root               409   0.0  0.0 409240096   8304   ??  Ss    8:00AM   0:08.09 /Library/Application Support/Fortinet/FortiClient/bin/ztnafw
rgonzlz            24587   0.0  0.0 408626896   1216 s007  R+   10:17AM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox -i FortiClient

**Comment by mlsmaycon** [comment]
Did you test Netbird's DNS resolution?

**Comment by mlsmaycon** [comment]
After checking the issue with @rgonzlz via Slack, we discovered that the issue was caused by a version of FortiClient running in the background. @rgonzlz further investigated and discovered that the issue didn't happen with the apple store version of the client.
