### ISSUE TITLE
Android App doesn't show error if other app has "always-on VPN"

### ISSUE THREAD

**Issue by ymarkus** [netbirdio/netbird#900]
**Describe the problem**
If another app has always-on VPN activated on Android, Netbird doesn't show an error and just ignores any input.

**To Reproduce**
1. Install app on android
2. Set other app to "always-on"
3. Try to activate Netbird.
4. See nothing

**Expected behavior**
A helpful error message

**Comment by mlsmaycon** [comment]
Fixed on v0.0.14
