### ISSUE TITLE
 Problems encountered during testing

### ISSUE THREAD

**Issue by chonglee123456** [netbirdio/netbird#903]
Hello, I have two Windows 10 hosts in the VPN that use the Netbird Windows client and are pinging normally. However, when I installed Chfsgui to simulate an FTP server on one of them and downloaded it through the VPN network on the other, I found that the host with Chfsgui would automatically go offline. I don't know the reason? Have you encountered this situation. thank you

**Comment by mlsmaycon** [comment]
Hello @chonglee123456 , thanks for reporting the issue.

In order to troubleshoot the problem. Can you share the netbird version of both clients?

You can do that on PowerShell with:
```
netbird version
```

**Comment by chonglee123456** [comment]
Hello, I am using the client version of Netbird version 0.20.3 and have also tried using PowerShell, but the results are the same. One end of the server will go offline.

**Comment by mlsmaycon** [comment]
Ok, we released the v0.20.4 yesterday with some fixes for windows clients related to MTU configuration. Can you please update both clients and run the test again?

**Comment by chonglee123456** [comment]
Do you want to upgrade the server

**Comment by mlsmaycon** [comment]
Initially the clients only. But you can upgrade the management layer too.

**Comment by chonglee123456** [comment]
Hello, the client has been updated to 0.20.4 and the issue has been resolved. Thank you.

**Comment by mlsmaycon** [comment]
That's great @chonglee123456 , thanks for reporting it again. Feel free to close the issue.
