### ISSUE TITLE
Features for network routes

### ISSUE THREAD

**Issue by emferrandi** [netbirdio/netbird#982]
**Is your feature request related to a problem? Please describe.**
It's impossible to delete network routes after some test with it. 
I also want to enable / disable network route faster like ACL with a simple switch.

**Describe the solution you'd like**
Is it possible to reproduce the same ACL functionality (enable/disable and delete) for network routes ?

My actual version for dashboard : "v1.15.2"

**Comment by braginini** [comment]
Hey @emferrandi 
Thank you for reporting the issue. We are almost ready with the new routes layout. 

What do you think about this?

![image](https://github.com/netbirdio/netbird/assets/700848/eaecf8ba-f59b-4a6a-8d00-4f5a46a1143c)

**Comment by emferrandi** [comment]
Hi @braginini 
That's exactly what I was thinkin'!
Thanks for your job !

**Comment by braginini** [comment]
Soon to be released :)

**Comment by mlsmaycon** [comment]
@emferrandi it was released a few weeks ago, can you have a look? 

Also, check your routing peer details from the peer's tab, now you can see the routes it is responsible for.
