### ISSUE TITLE
Settings window doesn't open on Windows 11

### ISSUE THREAD

**Issue by emferrandi** [netbirdio/netbird#986]
**Describe the problem**
When I try to display the settings pop-up to configure private address for Netbird client, nothing appears.

**To Reproduce**
1. Go to task bar when netbird-ui is launched
2. Right-click and then click on 'Settings'
3. Nothing is opened

**Expected behavior**
A settings window should open to configure the VPN client.

**Screenshots**
N/A

**Additional context**
My session on Windows 11 **is not admin.**

**Comment by mlsmaycon** [comment]
Hello @emferrandi is windows 11 being accessed via RDP? if so there is some issues with RDP sessions that doesn't enable openGL.

**Comment by emferrandi** [comment]
Hello @mlsmaycon,
In fact, I'm running Windows 11 on VMWare Workstation 16 Pro. 
Can the problem comes from virtualization ?

**Comment by joachimtingvold** [comment]
The problem seems to happen via HTML5 KVMs and console on virtual servers, in addition to via RDP.

**Comment by mitnicki** [comment]
can confirm the issue. happens via RDP on Win Server 2022. Is there a workaround?

**Comment by mitnicki** [comment]
> can confirm the issue. happens via RDP on Win Server 2022. Is there a workaround?

edit the file with editor "C:\ProgramData\Netbird\config.json" then restart netbird and connect

**Comment by mlsmaycon** [comment]
Hello folks, the issue was fixed in 0.25.3.
