### ISSUE TITLE
Blank screen instead of web ui/ login page

### ISSUE THREAD

**Issue by hpoznanski** [netbirdio/netbird#997]
**Describe the problem**
(self-hosted)I got a blank screen instead of web ui / login page. All components are up as in the below screenshot. Below logs from docker compose logs management - no errors. Auth0 configured, I don't see any problems in Auth0 logs either. 

**Expected behavior**
Web UI / login page after enter the domain

```infrastructure_files-management-1  | time="2023-06-30T13:25:20Z" level=info msg="loading OIDC configuration from the provided IDP configuration endpoint https://dev-domain.eu.auth0.com/.well-known/openid-configuration"
infrastructure_files-management-1  | time="2023-06-30T13:25:20Z" level=info msg="loaded OIDC configuration from the provided IDP configuration endpoint: https://dev-domain.eu.auth0.com/.well-known/openid-configuration"
infrastructure_files-management-1  | time="2023-06-30T13:25:20Z" level=info msg="overriding HttpConfig.AuthIssuer with a new value https://dev-domain.eu.auth0.com/, previously configured value: https://dev-domain.eu.auth0.com/"
infrastructure_files-management-1  | time="2023-06-30T13:25:20Z" level=info msg="overriding HttpConfig.AuthKeysLocation (JWT certs) with a new value https://dev-domain.eu.auth0.com/.well-known/jwks.json, previously configured value: https://dev-domain.eu.auth0.com/.well-known/jwks.json"
infrastructure_files-management-1  | 2023-06-30T13:25:20Z INFO management/server/telemetry/app_metrics.go:161: enabled application metrics and exposing on http://0.0.0.0:8081
infrastructure_files-management-1  | 2023-06-30T13:25:20Z INFO management/server/account.go:671: single account mode enabled, accounts number 0
infrastructure_files-management-1  | 2023-06-30T13:25:20Z INFO management/cmd/management.go:233: running gRPC backward compatibility server: [::]:33073
infrastructure_files-management-1  | 2023-06-30T13:25:20Z INFO management/cmd/management.go:265: running HTTP server and gRPC server on the same port: [::]:443
infrastructure_files-management-1  | 2023-06-30T13:25:30Z INFO management/server/account.go:858: warmed up IDP cache with 0 entries

docker ps
CONTAINER ID   IMAGE                          COMMAND                  CREATED          STATUS          PORTS                                                                      NAMES
7e7929628135   netbirdio/management:latest    "/go/bin/netbird-mgm…"   16 minutes ago   Up 16 minutes   0.0.0.0:33073->443/tcp, :::33073->443/tcp                                  infrastructure_files-management-1
37cbb2b87cc0   coturn/coturn                  "docker-entrypoint.s…"   16 minutes ago   Up 16 minutes                                                                              infrastructure_files-coturn-1
3e811b79f92c   netbirdio/signal:latest        "/go/bin/netbird-sig…"   16 minutes ago   Up 16 minutes   0.0.0.0:10000->80/tcp, :::10000->80/tcp                                    infrastructure_files-signal-1
d30dc26427ea   wiretrustee/dashboard:latest   "/usr/bin/supervisor…"   16 minutes ago   Up 16 minutes   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   infrastructure_files-dashboard-1```

**Comment by UncleJ4ck** [comment]
can you drop the dashboard docker logs please ?

**Comment by hpoznanski** [comment]
> can you drop the dashboard docker logs please ?

Below this log actually shows my attempts to enter + refresh the page 

`infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:28 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:28 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:29 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:29 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:29 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:29 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:29 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:30 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:31 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"
infrastructure_files-dashboard-1  | my_ip - - [30/Jun/2023:15:25:31 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36" "-"`

**Comment by UncleJ4ck** [comment]
yes i got the same error as you it's 304, the only solution for now is to revert to the old version 0.27.1

**Comment by ps-hpoznanski** [comment]
on 0.27.1 theres still same problem

**Comment by hpoznanski** [comment]
on 0.27.1 theres still same problem :/

**Comment by hpoznanski** [comment]
Ok its weird but after 12h looks like it works but now I have "Login Error: User state: Unauthenticated"

**Comment by hpoznanski** [comment]
Ok, fixed there Token Endpoint Authentication Method wasnt "None".

**Comment by UncleJ4ck** [comment]
> Ok, fixed there Token Endpoint Authentication Method wasnt "None".

What's the ENV variable that you fixed ?

**Comment by Tiny-Wei** [comment]
+1,so how did you solved it?

**Comment by ajeanselme** [comment]
@hpoznanski can you post how you solved this problem?
